// moodfm-frontend/src/views/auth/Auth.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import Logo from '@/components/common/Logo.vue'

const router = useRouter()
const auth = useAuthStore()

const kind = ref<'login' | 'signup'>('login')

const loginId = ref('')
const loginPwd = ref('')
const remember = ref(true)

const signName = ref('')
const signEmail = ref('')
const signPwd = ref('')
const signCode = ref('')
const countdown = ref(0)
let cdTimer: ReturnType<typeof setInterval> | null = null

const loading = ref(false)
const globalError = ref('')

function sendCode() {
  if (countdown.value > 0) return
  countdown.value = 60
  cdTimer = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0 && cdTimer) { clearInterval(cdTimer); cdTimer = null }
  }, 1000)
}

async function submit() {
  loading.value = true
  globalError.value = ''
  try {
    if (kind.value === 'login') {
      await auth.login({ email: loginId.value, password: loginPwd.value })
      router.push('/home')
    } else {
      await auth.register({ username: signName.value, email: signEmail.value, password: signPwd.value })
      router.push('/onboarding')
    }
  } catch (e: any) {
    globalError.value = e?.response?.data?.message || e?.message || (kind.value === 'login' ? '登录失败，请重试' : '注册失败，请重试')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div style="display:grid;grid-template-columns:1fr 1fr;min-height:100vh;">
    <div style="position:relative;overflow:hidden;background:var(--bg);border-right:1px solid var(--rule);">
      <div class="mood-blob drift" style="width:720px;height:720px;left:-120px;top:-160px;opacity:.55;" />
      <div class="mood-blob drift" style="width:480px;height:480px;right:-100px;bottom:-120px;opacity:.4;" />
      <div style="position:absolute;inset:0;padding:56px;display:flex;flex-direction:column;justify-content:space-between;z-index:2;">
        <div class="row" style="gap:10px;">
          <Logo :size="28" />
          <span style="font-family:var(--serif-en);font-size:22px;font-style:italic;">MoodFM</span>
        </div>
        <div>
          <div class="meta">ISSUE №01 · {{ kind === 'signup' ? 'NEW LISTENERS' : 'WELCOME BACK' }}</div>
          <h1 class="display" style="font-size:96px;margin:14px 0 0;line-height:.95;">
            <template v-if="kind === 'signup'">Tune <em>in</em>.</template>
            <template v-else>Welcome <em>home</em>.</template>
          </h1>
          <div class="display-cn" style="font-size:32px;margin-top:16px;color:var(--ink-2);">
            {{ kind === 'signup' ? '今晚开始，你也有一座电台。' : '欢迎回来。电台已替你温着。' }}
          </div>
          <p style="margin-top:24px;font-size:15px;line-height:1.7;color:var(--ink-2);max-width:380px;font-family:var(--serif-cn);">
            {{ kind === 'signup'
              ? '我们读取你的情绪，跨越平台编排音乐——你只需要说一句话，或者什么都别说。'
              : '上一次你听到的是 Marconi Union 的《weightless》，进度 1:24。准备好继续了吗？' }}
          </p>
        </div>
        <div class="between" style="font-family:var(--mono);font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:var(--ink-3);">
          <span>SPRING / 2026</span><span>A PRIVATE STATION</span>
        </div>
      </div>
    </div>

    <div style="padding:64px 80px;display:flex;flex-direction:column;justify-content:center;">
      <div class="meta">{{ kind === 'signup' ? 'NEW ACCOUNT · 创建账号' : 'SIGN IN · 登录' }}</div>
      <h2 class="display" style="font-size:72px;margin:10px 0 0;">
        {{ kind === 'signup' ? 'Begin.' : 'Hi, again.' }}
      </h2>
      <div class="display-cn" style="font-size:28px;margin-top:6px;color:var(--ink-2);">
        {{ kind === 'signup' ? '注册 · 用一句话描述你' : '登录 · 继续昨晚的电台' }}
      </div>

      <div v-if="globalError" style="margin-top:16px;padding:12px 16px;border-radius:12px;background:rgba(232,90,138,0.08);border:1px solid var(--mood-b);">
        <span class="meta" style="color:var(--mood-b);">· {{ globalError }}</span>
      </div>

      <div v-if="kind === 'login'" style="margin-top:40px;">
        <div style="margin-bottom:14px;">
          <div class="meta" style="margin-bottom:8px;">邮箱 / 手机 · EMAIL OR PHONE</div>
          <input v-model="loginId" class="field" placeholder="you@somewhere.com" />
        </div>
        <div style="margin-bottom:14px;">
          <div class="meta" style="margin-bottom:8px;">密码 · PASSWORD</div>
          <input v-model="loginPwd" class="field" type="password" placeholder="·······" />
        </div>
        <label class="row" style="gap:10px;font-family:var(--serif-cn);font-size:13px;color:var(--ink-2);margin-bottom:18px;cursor:pointer;" @click="remember = !remember">
          <span :style="{ width:'16px', height:'16px', borderRadius:'4px', border:'1px solid var(--ink)',
                          background: remember ? 'var(--ink)' : 'transparent', display:'inline-flex',
                          alignItems:'center', justifyContent:'center', flexShrink:0 }">
            <span v-if="remember" style="width:8px;height:8px;background:var(--bg);border-radius:2px;" />
          </span>
          30 天内记住我 · Remember me
        </label>
        <button class="btn" style="width:100%;height:50px;" :disabled="loading" @click="submit">
          {{ loading ? '登录中...' : '登录 · SIGN IN →' }}
        </button>
        <div class="row" style="margin-top:24px;gap:12px;align-items:center;">
          <hr class="rule" style="flex:1;" /><span class="meta">OR</span><hr class="rule" style="flex:1;" />
        </div>
        <div class="row" style="gap:10px;margin-top:20px;">
          <button class="btn-pill" style="flex:1;height:44px;">网易云账号</button>
          <button class="btn-pill" style="flex:1;height:44px;">QQ 音乐账号</button>
        </div>
      </div>

      <div v-else style="margin-top:36px;">
        <div style="margin-bottom:14px;">
          <div class="meta" style="margin-bottom:8px;">昵称 · NAME</div>
          <input v-model="signName" class="field" placeholder="你叫什么" />
        </div>
        <div style="margin-bottom:14px;">
          <div class="meta" style="margin-bottom:8px;">邮箱 · EMAIL</div>
          <input v-model="signEmail" class="field" placeholder="you@somewhere.com" />
        </div>
        <div style="margin-bottom:14px;">
          <div class="meta" style="margin-bottom:8px;">密码 · PASSWORD</div>
          <input v-model="signPwd" class="field" type="password" placeholder="至少 8 位" />
        </div>
        <div style="margin-bottom:14px;position:relative;">
          <div class="meta" style="margin-bottom:8px;">验证码 · ONE-TIME CODE</div>
          <input v-model="signCode" class="field" placeholder="6 位" style="padding-right:130px;" />
          <button @click="sendCode"
            :style="{ position:'absolute', right:'6px', bottom:'6px', height:'36px', padding:'0 14px',
                      borderRadius:'999px', fontFamily:'var(--mono)', fontSize:'11px', letterSpacing:'.14em',
                      textTransform:'uppercase', border:'none', cursor: countdown > 0 ? 'not-allowed' : 'pointer',
                      background: countdown > 0 ? 'transparent' : 'var(--ink)',
                      color: countdown > 0 ? 'var(--ink-3)' : 'var(--bg)' }">
            {{ countdown > 0 ? countdown + 's' : '获取验证码' }}
          </button>
        </div>
        <button class="btn" style="width:100%;height:50px;margin-top:8px;" :disabled="loading" @click="submit">
          {{ loading ? '注册中...' : '注册并启动 · CREATE ACCOUNT →' }}
        </button>
      </div>

      <div class="between" style="margin-top:24px;font-family:var(--serif-cn);font-size:14px;color:var(--ink-2);">
        <span>
          {{ kind === 'signup' ? '已有账号？' : '还没有账号？' }}
          <a style="color:var(--ink);text-decoration:underline;text-underline-offset:3px;cursor:pointer;"
             @click="kind = kind === 'signup' ? 'login' : 'signup'">
            {{ kind === 'signup' ? '登录' : '注册' }} →
          </a>
        </span>
        <a v-if="kind === 'login'" style="color:var(--ink-3);cursor:pointer;">忘记密码？</a>
      </div>

      <div class="meta" style="margin-top:auto;padding-top:40px;color:var(--ink-3);">
        BY CONTINUING YOU AGREE TO OUR
        <span style="color:var(--ink-2);text-decoration:underline;">TERMS</span> ·
        <span style="color:var(--ink-2);text-decoration:underline;">PRIVACY</span>
      </div>
    </div>
  </div>
</template>

// Front-end styles/MoodFM · 心绪电台/screens/auth.jsx
/* global React, ScreenFrame, MoodBlob, Icon, Logo */
// P2 · Signup  |  P3 · Login
// Shared editorial split layout: left = mood blob art + manifesto · right = form

function AuthFrame({ device, theme, mood, kind = 'login', onSubmit, onSwitch }) {
  const isMobile = device === 'mobile';
  const W = isMobile ? 390 : 1440;
  const H = isMobile ? 844 : 900;
  const isSignup = kind === 'signup';

  return (
    <ScreenFrame theme={theme} mood={mood} width={W} height={H} label={isSignup ? '02a Signup' : '02b Login'} scroll={isMobile}>
      <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', minHeight: H }}>
        {/* LEFT — editorial art (cream paper + gradient blob, matches design language) */}
        {!isMobile && (
          <div style={{ position:'relative', overflow:'hidden', background:'var(--bg)', color:'var(--ink)', borderRight:'1px solid var(--rule)' }}>
            {/* Soft gradient blob, not a full dark wash */}
            <div className="mood-blob drift" style={{ width: 720, height: 720, left: -120, top: -160, opacity: 0.55 }}/>
            <div className="mood-blob drift" style={{ width: 480, height: 480, right: -100, bottom: -120, opacity: 0.4 }}/>

            <div style={{ position:'absolute', inset: 0, padding: 56, display:'flex', flexDirection:'column', justifyContent:'space-between', zIndex: 2 }}>
              <div className="row" style={{ gap: 10 }}>
                <Logo size={28}/>
                <div style={{ fontFamily:'var(--serif-en)', fontSize: 22, fontStyle:'italic' }}>MoodFM</div>
              </div>

              <div>
                <div className="meta">
                  ISSUE №01 · {isSignup ? 'NEW LISTENERS' : 'WELCOME BACK'}
                </div>
                <h1 className="display" style={{ fontSize: 96, margin:'14px 0 0', lineHeight: 0.95 }}>
                  {isSignup ? <>Tune <em>in</em>.</> : <>Welcome <em>home</em>.</>}
                </h1>
                <div className="display-cn" style={{ fontSize: 32, marginTop: 16, color:'var(--ink-2)' }}>
                  {isSignup ? '今晚开始，你也有一座电台。' : '欢迎回来。电台已替你温着。'}
                </div>
                <p style={{ marginTop: 24, fontSize: 15, lineHeight: 1.7, color:'var(--ink-2)', maxWidth: 380, fontFamily:'var(--serif-cn)' }}>
                  {isSignup
                    ? '我们读取你的情绪，跨越平台编排音乐——你只需要说一句话，或者什么都别说。'
                    : '上一次你听到的是 Marconi Union 的《weightless》，进度 1:24。准备好继续了吗？'}
                </p>
              </div>

              <div className="between" style={{ fontFamily:'var(--mono)', fontSize: 11, letterSpacing:'.18em', textTransform:'uppercase', color:'var(--ink-3)' }}>
                <span>SPRING / 2026</span>
                <span>A PRIVATE STATION</span>
              </div>
            </div>
          </div>
        )}

        {/* RIGHT — form */}
        <div style={{ padding: isMobile ? '32px 22px 60px' : '64px 80px', position:'relative', display:'flex', flexDirection:'column', justifyContent: isMobile?'flex-start':'center' }}>
          {isMobile && (
            <div className="row" style={{ gap: 10, marginBottom: 36 }}>
              <Logo size={22}/>
              <div style={{ fontFamily:'var(--serif-en)', fontSize: 18, fontStyle:'italic' }}>MoodFM</div>
            </div>
          )}

          <div className="meta">{isSignup ? 'NEW ACCOUNT · 创建账号' : 'SIGN IN · 登录'}</div>
          <h2 className="display" style={{ fontSize: isMobile?52:72, margin:'10px 0 0' }}>
            {isSignup ? <>Begin.</> : <>Hi, again.</>}
          </h2>
          <div className="display-cn" style={{ fontSize: isMobile?22:28, marginTop: 6, color:'var(--ink-2)' }}>
            {isSignup ? '注册 · 用一句话描述你' : '登录 · 继续昨晚的电台'}
          </div>

          <div style={{ marginTop: isMobile?28:40 }}>
            {isSignup ? <SignupForm/> : <LoginForm/>}
          </div>

          <div className="between" style={{ marginTop: 28, fontFamily:'var(--serif-cn)', fontSize: 14, color:'var(--ink-2)' }}>
            <span>
              {isSignup ? '已有账号？' : '还没有账号？'}{' '}
              <a onClick={onSwitch} style={{ color:'var(--ink)', textDecoration:'underline', textUnderlineOffset:3, cursor:'pointer' }}>
                {isSignup ? '登录' : '注册'} →
              </a>
            </span>
            {!isSignup && <a style={{ color:'var(--ink-3)', cursor:'pointer' }}>忘记密码？</a>}
          </div>

          {/* Footer meta */}
          <div className="meta" style={{ marginTop: 'auto', paddingTop: 40, color:'var(--ink-3)' }}>
            BY CONTINUING YOU AGREE TO OUR <span style={{ color:'var(--ink-2)', textDecoration:'underline' }}>TERMS</span> · <span style={{ color:'var(--ink-2)', textDecoration:'underline' }}>PRIVACY</span>
          </div>
        </div>
      </div>
    </ScreenFrame>
  );
}

function Field({ label, hint, type='text', value, onChange, placeholder, suffix, error }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div className="between" style={{ marginBottom: 8 }}>
        <label className="meta" style={{ color: error ? 'var(--mood-b)' : 'var(--ink-2)' }}>{label}</label>
        {hint && <span className="meta" style={{ color:'var(--ink-3)' }}>{hint}</span>}
      </div>
      <div style={{ position:'relative' }}>
        <input
          type={type}
          value={value}
          onChange={onChange}
          placeholder={placeholder}
          className="field"
          style={{
            paddingRight: suffix ? 130 : 16,
            borderColor: error ? 'var(--mood-b)' : 'var(--rule)',
          }}
        />
        {suffix && <div style={{ position:'absolute', right:6, top:6, bottom:6 }}>{suffix}</div>}
      </div>
      {error && <div className="meta" style={{ marginTop: 6, color:'var(--mood-b)' }}>· {error}</div>}
    </div>
  );
}

function SignupForm() {
  const [n, setN] = React.useState('江野');
  const [e, setE] = React.useState('jiangye@gmail.com');
  const [p, setP] = React.useState('');
  const [c, setC] = React.useState('');
  const [code, setCode] = React.useState('');
  const [count, setCount] = React.useState(0);
  const [agree, setAgree] = React.useState(true);

  const sendCode = () => { if (count===0) { setCount(60); const t=setInterval(()=>setCount(s=>{ if (s<=1){ clearInterval(t); return 0;} return s-1; }), 1000); } };

  return (
    <div>
      <Field label="昵称 · NAME" value={n} onChange={e=>setN(e.target.value)} placeholder="你叫什么"/>
      <Field label="邮箱 · EMAIL" value={e} onChange={ev=>setE(ev.target.value)} placeholder="you@somewhere.com"/>
      <Field label="密码 · PASSWORD" hint="≥ 8 位 · 字母+数字" type="password" value={p} onChange={ev=>setP(ev.target.value)} placeholder="至少 8 位"/>
      <Field label="确认密码 · CONFIRM" type="password" value={c} onChange={ev=>setC(ev.target.value)} placeholder="再输一次"/>
      <Field
        label="验证码 · ONE-TIME CODE"
        value={code}
        onChange={ev=>setCode(ev.target.value)}
        placeholder="6 位"
        suffix={
          <button onClick={sendCode} style={{
            height: 36, padding:'0 14px', borderRadius: 999,
            background: count>0 ? 'transparent' : 'var(--ink)', color: count>0 ? 'var(--ink-3)' : 'var(--bg)',
            border: count>0 ? '1px solid var(--rule)' : 'none',
            fontFamily:'var(--mono)', fontSize: 11, letterSpacing:'.14em', textTransform:'uppercase',
            cursor: count>0?'not-allowed':'pointer',
          }}>{count>0 ? `${count}s` : '获取验证码'}</button>
        }
      />
      <label className="row" style={{ gap: 10, fontFamily:'var(--serif-cn)', fontSize: 13, color:'var(--ink-2)', marginTop: 4, marginBottom: 16, cursor:'pointer' }} onClick={()=>setAgree(a=>!a)}>
        <span style={{ width:16, height:16, borderRadius: 4, border:'1px solid var(--ink)', background: agree?'var(--ink)':'transparent', display:'inline-flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
          {agree && <span style={{ width:8, height:8, background:'var(--bg)', borderRadius: 2 }}/>}
        </span>
        <span>我已阅读并同意 <span style={{ color:'var(--ink)', textDecoration:'underline' }}>服务条款</span> 与 <span style={{ color:'var(--ink)', textDecoration:'underline' }}>隐私政策</span></span>
      </label>
      <button className="btn" style={{ width:'100%', height: 50 }}>注册并启动 · CREATE ACCOUNT <Icon.arrow/></button>
    </div>
  );
}

function LoginForm() {
  const [id, setId] = React.useState('jiangye@gmail.com');
  const [p, setP] = React.useState('');
  const [remember, setRemember] = React.useState(true);

  return (
    <div>
      <Field label="邮箱 / 手机 · EMAIL OR PHONE" value={id} onChange={ev=>setId(ev.target.value)}/>
      <Field label="密码 · PASSWORD" type="password" value={p} onChange={ev=>setP(ev.target.value)} placeholder="·······"/>
      <label className="row" style={{ gap: 10, fontFamily:'var(--serif-cn)', fontSize: 13, color:'var(--ink-2)', marginBottom: 18, cursor:'pointer' }} onClick={()=>setRemember(r=>!r)}>
        <span style={{ width:16, height:16, borderRadius: 4, border:'1px solid var(--ink)', background: remember?'var(--ink)':'transparent', display:'inline-flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
          {remember && <span style={{ width:8, height:8, background:'var(--bg)', borderRadius: 2 }}/>}
        </span>
        <span>30 天内记住我 · Remember me</span>
      </label>
      <button className="btn" style={{ width:'100%', height: 50 }}>登录 · SIGN IN <Icon.arrow/></button>

      <div className="row" style={{ marginTop: 24, gap: 12, alignItems:'center' }}>
        <hr className="rule" style={{ flex:1, borderTopColor:'var(--rule)' }}/>
        <span className="meta">OR</span>
        <hr className="rule" style={{ flex:1, borderTopColor:'var(--rule)' }}/>
      </div>
      <div className="row" style={{ gap: 10, marginTop: 20 }}>
        <button className="btn-pill" style={{ flex:1, height: 44 }}>网易云账号</button>
        <button className="btn-pill" style={{ flex:1, height: 44 }}>QQ 音乐账号</button>
      </div>
    </div>
  );
}

window.AuthFrame = AuthFrame;
