// moodfm-frontend/src/views/library/Playlist.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { usePlayerStore } from '@/stores/player'
import MoodBlob from '@/components/common/MoodBlob.vue'
import { playlistApi } from '@/api/playlist'

const router = useRouter()
const route = useRoute()
const player = usePlayerStore()
const loading = ref(true)
const error = ref<string | null>(null)
const playlist = ref<any>(null)

interface TrackItem { t: string; a: string; al: string; m: string; mood: string; liked: boolean }

const tracks = ref<TrackItem[]>([])

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

const metaItems = computed(() => [
  { l: 'TRACKS',   v: String(playlist.value?.trackCount ?? tracks.value.length) },
  { l: 'DURATION', v: `${Math.round(tracks.value.length * 3.5)} MIN` },
  { l: 'UPDATED',  v: '每日同步' },
  { l: 'SOURCE',   v: playlist.value?.platform === 'netease' ? '网易云' : playlist.value?.platform === 'qqmusic' ? 'QQ 音乐' : '—' },
])

const activeIdx = ref(0)
const likedMap = ref<Record<number, boolean>>({})
const hovIdx = ref(-1)

onMounted(async () => {
  const id = route.params.id as string
  if (!id) { loading.value = false; return }
  try {
    const data = await playlistApi.getPlaylist(id)
    playlist.value = data
    tracks.value = (data.tracks ?? []).map(s => ({
      t: s.title,
      a: s.artist,
      al: s.album ?? '',
      m: formatDuration(s.duration),
      mood: 'CALM',
      liked: false,
    }))
    likedMap.value = Object.fromEntries(tracks.value.map((_, i) => [i, false]))
  } catch (e: any) {
    error.value = e?.message ?? '加载失败'
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);padding-bottom:80px;">
    <div style="position:sticky;top:0;z-index:5;background:var(--bg);padding:18px 56px;
                border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between;">
      <button class="btn-pill" @click="router.back()">← 返回</button>
      <div class="meta">PLAYLIST · 歌单详情</div>
      <button class="btn-pill">···</button>
    </div>

    <div style="position:relative;overflow:hidden;padding:56px 56px 48px;border-bottom:1px solid var(--rule);">
      <div class="mood-blob drift" style="width:800px;height:800px;right:-150px;top:-220px;opacity:.45;" />
      <div style="position:relative;z-index:2;display:grid;grid-template-columns:320px 1fr;gap:48px;align-items:end;">
        <div>
          <div style="position:relative;width:300px;height:300px;border-radius:18px;overflow:hidden;
                      box-shadow:0 24px 60px rgba(0,0,0,.18);">
            <MoodBlob :size="300" :drift="true" geometry="blob" />
            <div style="position:absolute;left:14px;bottom:12px;color:#fff;text-shadow:0 1px 4px rgba(0,0,0,.4);">
              <div class="mono" style="font-size:10px;letter-spacing:.2em;opacity:.9;">NIGHT FLOAT · 010</div>
            </div>
          </div>
        </div>
        <div>
          <div class="meta">CURATED FOR YOU · 为你编排</div>
          <h1 class="display" style="font-size:108px;margin:12px 0 0;line-height:.95;">Night <em>float</em>.</h1>
          <div class="display-cn" style="font-size:34px;margin-top:4px;color:var(--ink-2);">夜浮 · 给加完班的你</div>
          <p style="margin-top:16px;font-size:14px;line-height:1.7;color:var(--ink-2);max-width:520px;font-family:var(--serif-cn);">
            一份漂在凌晨水面上的 ambient 合集——人声极少、低频温和、不会打扰任何思绪。AI 根据你过去 30 天 23:00 后的收听偏好编排。
          </p>
          <div class="row" style="margin-top:20px;gap:24px;color:var(--ink-3);">
            <div v-for="m in metaItems" :key="m.l">
              <div class="meta">{{ m.l }}</div>
              <div class="mono" style="font-size:14px;color:var(--ink);margin-top:2px;">{{ m.v }}</div>
            </div>
          </div>
          <div class="row" style="margin-top:24px;gap:10px;flex-wrap:wrap;">
            <button class="btn" style="height:48px;padding:0 22px;" @click="player.play();router.push('/player')">▶ 播放 · PLAY ALL</button>
            <button class="btn-pill" style="height:48px;">♡ 收藏</button>
            <button class="btn-pill" style="height:48px;">↓ 下载</button>
            <button class="btn-pill" style="height:48px;">↗ 分享</button>
          </div>
        </div>
      </div>
    </div>

    <div style="padding:40px 56px;">
      <div class="between" style="margin-bottom:16px;">
        <div class="meta">TRACK LIST · 曲目</div>
        <div class="row" style="gap:8px;">
          <button class="btn-pill">排序 ↓</button>
          <button class="btn-pill">筛选</button>
        </div>
      </div>
      <div class="row" style="padding:10px 16px;color:var(--ink-3);border-bottom:1px solid var(--rule);">
        <div class="meta" style="width:32px;">#</div>
        <div class="meta" style="flex:2.5;">TITLE · 标题</div>
        <div class="meta" style="flex:1.5;">ALBUM · 专辑</div>
        <div class="meta" style="width:100px;">MOOD</div>
        <div style="width:40px;" />
        <div class="meta" style="width:60px;text-align:right;">TIME</div>
      </div>
      <div
        v-for="(t, i) in tracks"
        :key="i"
        class="row"
        :style="{
          padding: '12px 16px',
          borderRadius: '8px',
          cursor: 'pointer',
          background: i === activeIdx || i === hovIdx ? 'var(--bg-2)' : 'transparent',
          transition: 'background .1s',
        }"
        @mouseenter="hovIdx = i"
        @mouseleave="hovIdx = -1"
        @click="activeIdx = i; player.play()"
      >
        <div style="width:32px;font-family:var(--mono);font-size:13px;color:var(--ink-3);">
          {{ i === activeIdx ? '▸' : String(i + 1).padStart(2, '0') }}
        </div>
        <div style="flex:2.5;min-width:0;">
          <div style="font-family:var(--serif-en);font-style:italic;font-size:19px;">{{ t.t }}</div>
          <div class="meta" style="margin-top:2px;">{{ t.a }}</div>
        </div>
        <div style="flex:1.5;min-width:0;font-family:var(--serif-cn);font-size:13px;color:var(--ink-2);
                    white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{ t.al }}</div>
        <div style="width:100px;">
          <span class="meta" style="padding:3px 8px;border:1px solid var(--rule);border-radius:999px;color:var(--ink-2);">{{ t.mood }}</span>
        </div>
        <div style="width:40px;text-align:center;">
          <button
            @click.stop="likedMap[i] = !likedMap[i]"
            style="background:none;border:none;cursor:pointer;font-size:18px;line-height:1;"
            :style="{ color: likedMap[i] ? 'var(--mood-b)' : 'var(--ink-3)' }"
          >{{ likedMap[i] ? '♥' : '♡' }}</button>
        </div>
        <div class="mono" style="width:60px;text-align:right;font-size:12px;color:var(--ink-3);">{{ t.m }}</div>
      </div>
    </div>
  </div>
</template>

// Front-end styles/MoodFM · 心绪电台/screens/playlist.jsx
/* global React, ScreenFrame, MoodBlob, Icon, Logo */
// P10 · Playlist Detail

function PlaylistDetail({ device='desktop', theme, mood, onBack, onPlay }) {
  const isMobile = device === 'mobile';
  const W = isMobile ? 390 : 1440;
  const H = isMobile ? 844 : 900;

  const tracks = [
    { t:'weightless', a:'Marconi Union', al:'Ambient Transmissions', m:'8:09', mood:'CALM', liked:true },
    { t:'晚安', a:'Mong Tong', al:'桃源乡', m:'4:21', mood:'TENDER', liked:true },
    { t:'Re: Stacks', a:'Bon Iver', al:'For Emma, Forever Ago', m:'6:42', mood:'BLUE' },
    { t:'Petrichor', a:'Ólafur Arnalds', al:'re:member', m:'5:18', mood:'FOCUS', liked:true },
    { t:'Ferry', a:'Cigarettes After Sex', al:'X\'s', m:'4:55', mood:'BLUE' },
    { t:'Saman', a:'Ólafur Arnalds', al:'Island Songs', m:'5:23', mood:'CALM' },
    { t:'夜空中最闪亮的星', a:'逃跑计划', al:'世界', m:'4:38', mood:'TENDER', liked:true },
    { t:'Holocene', a:'Bon Iver', al:'Bon Iver, Bon Iver', m:'5:36', mood:'BLUE' },
    { t:'秋意上心头', a:'丝芭乐队', al:'秋意上心头', m:'3:48', mood:'TENDER' },
    { t:'Lost in Yesterday', a:'Tame Impala', al:'The Slow Rush', m:'4:15', mood:'FOCUS' },
  ];

  return (
    <ScreenFrame theme={theme} mood={mood} width={W} height={H} label="04d Playlist" scroll={true}>
      {/* Top bar */}
      <div style={{ position:'sticky', top:0, zIndex:5, background:'var(--bg)', padding: isMobile?'14px 18px':'18px 56px', borderBottom:'1px solid var(--rule)', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
        <button onClick={onBack} className="btn-pill"><Icon.chevL/> 返回</button>
        {!isMobile && <div className="meta">PLAYLIST · 歌单详情</div>}
        <div className="row" style={{ gap: 8 }}>
          <button className="btn-pill">···</button>
        </div>
      </div>

      {/* Hero */}
      <div style={{ position:'relative', overflow:'hidden', padding: isMobile?'28px 22px 32px':'56px 56px 48px', borderBottom:'1px solid var(--rule)' }}>
        <div className="mood-blob drift" style={{ width: isMobile?500:800, height: isMobile?500:800, right: isMobile?-220:-150, top: isMobile?-200:-220, opacity: 0.45 }}/>

        <div style={{ position:'relative', zIndex: 2, display:'grid', gridTemplateColumns: isMobile?'1fr':'320px 1fr', gap: isMobile?28:48, alignItems:'end' }}>
          {/* Cover */}
          <div style={{ display:'flex', justifyContent: isMobile?'center':'flex-start' }}>
            <div style={{ position:'relative', width: isMobile?220:300, height: isMobile?220:300, borderRadius: 18, overflow:'hidden', boxShadow: '0 24px 60px rgba(0,0,0,0.18)' }}>
              <MoodBlob size={isMobile?220:300} drift={true} geometry="blob"/>
              <div style={{ position:'absolute', left: 14, bottom: 12, color:'#fff', textShadow:'0 1px 4px rgba(0,0,0,0.4)' }}>
                <div className="mono" style={{ fontSize: 10, letterSpacing:'.2em', opacity: 0.9 }}>NIGHT FLOAT · 010</div>
              </div>
            </div>
          </div>

          {/* Meta */}
          <div>
            <div className="meta">CURATED FOR YOU · 为你编排</div>
            <h1 className="display" style={{ fontSize: isMobile?56:108, margin: '12px 0 0', lineHeight: 0.95 }}>
              Night <em>float</em>.
            </h1>
            <div className="display-cn" style={{ fontSize: isMobile?22:34, marginTop: 4, color:'var(--ink-2)' }}>
              夜浮 · 给加完班的你
            </div>
            <p style={{ marginTop: 16, fontSize: 14, lineHeight: 1.7, color:'var(--ink-2)', maxWidth: 520, fontFamily:'var(--serif-cn)' }}>
              一份漂在凌晨水面上的 ambient 合集——人声极少、低频温和、不会打扰任何思绪。AI 根据你过去 30 天 23:00 后的收听偏好编排。
            </p>

            <div className="row" style={{ marginTop: 20, gap: 24, color:'var(--ink-3)' }}>
              <div><div className="meta">TRACKS</div><div className="mono" style={{ fontSize: 14, color:'var(--ink)', marginTop: 2 }}>{tracks.length}</div></div>
              <div><div className="meta">DURATION</div><div className="mono" style={{ fontSize: 14, color:'var(--ink)', marginTop: 2 }}>52 MIN</div></div>
              <div><div className="meta">UPDATED</div><div className="mono" style={{ fontSize: 14, color:'var(--ink)', marginTop: 2 }}>每日 23:00</div></div>
              <div><div className="meta">DOMINANT</div><div className="mono" style={{ fontSize: 14, color:'var(--ink)', marginTop: 2 }}>CALM · BLUE</div></div>
            </div>

            <div className="row" style={{ marginTop: 24, gap: 10, flexWrap:'wrap' }}>
              <button className="btn" onClick={onPlay} style={{ height: 48, padding:'0 22px', fontSize: 14 }}>
                <Icon.play/> 播放 · PLAY ALL
              </button>
              <button className="btn-pill" style={{ height: 48 }}>♡ 收藏</button>
              <button className="btn-pill" style={{ height: 48 }}>↓ 下载</button>
              <button className="btn-pill" style={{ height: 48 }}>↗ 分享</button>
            </div>
          </div>
        </div>
      </div>

      {/* Track list */}
      <div style={{ padding: isMobile?'24px 18px 80px':'40px 56px 80px' }}>
        <div className="between" style={{ marginBottom: 16 }}>
          <div className="meta">TRACK LIST · 曲目</div>
          <div className="row" style={{ gap: 8 }}>
            <button className="btn-pill" style={{ whiteSpace:'nowrap' }}>排序 ↓</button>
            <button className="btn-pill" style={{ whiteSpace:'nowrap' }}>筛选</button>
          </div>
        </div>

        {/* Header row */}
        {!isMobile && (
          <div className="row" style={{ padding:'10px 16px', color:'var(--ink-3)', borderBottom:'1px solid var(--rule)' }}>
            <div className="meta" style={{ width: 32 }}>#</div>
            <div className="meta" style={{ flex: 2.5 }}>TITLE · 标题</div>
            <div className="meta" style={{ flex: 1.5 }}>ALBUM · 专辑</div>
            <div className="meta" style={{ width: 100 }}>MOOD</div>
            <div className="meta" style={{ width: 40 }}></div>
            <div className="meta" style={{ width: 60, textAlign:'right' }}>TIME</div>
          </div>
        )}

        {tracks.map((t,i)=>(
          <Track key={i} t={t} i={i} isMobile={isMobile} active={i===0}/>
        ))}
      </div>
    </ScreenFrame>
  );
}

function Track({ t, i, isMobile, active }) {
  const [hover, setHover] = React.useState(false);
  const [liked, setLiked] = React.useState(t.liked);

  if (isMobile) {
    return (
      <div className="row" style={{ gap: 12, padding:'12px 6px', borderBottom: '1px solid var(--rule)' }}>
        <span className="mono" style={{ color: active?'var(--ink)':'var(--ink-3)', width: 22, fontSize: 12 }}>
          {active ? '▸' : String(i+1).padStart(2,'0')}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div className="serif-en" style={{ fontSize: 16, fontStyle:'italic', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{t.t}</div>
          <div className="meta" style={{ marginTop: 2, whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{t.a} · {t.mood}</div>
        </div>
        <button onClick={()=>setLiked(!liked)} style={{ background:'none', border:'none', color: liked?'var(--mood-b)':'var(--ink-3)', cursor:'pointer', fontSize: 18, lineHeight: 1 }}>{liked?'♥':'♡'}</button>
        <div className="mono" style={{ color:'var(--ink-3)', fontSize: 12, width: 36, textAlign:'right' }}>{t.m}</div>
      </div>
    );
  }

  return (
    <div
      onMouseEnter={()=>setHover(true)}
      onMouseLeave={()=>setHover(false)}
      className="row"
      style={{
        padding: '12px 16px', borderRadius: 8,
        background: active ? 'var(--bg-2)' : hover ? 'var(--bg-2)' : 'transparent',
        cursor:'pointer',
      }}
    >
      <div style={{ width: 32, color: active?'var(--ink)':'var(--ink-3)', fontFamily:'var(--mono)', fontSize: 13 }}>
        {active ? '▸' : hover ? <Icon.play/> : String(i+1).padStart(2,'0')}
      </div>
      <div style={{ flex: 2.5, minWidth: 0 }}>
        <div className="serif-en" style={{ fontSize: 19, fontStyle:'italic', color: active?'var(--ink)':'var(--ink)' }}>{t.t}</div>
        <div className="meta" style={{ marginTop: 2 }}>{t.a}</div>
      </div>
      <div style={{ flex: 1.5, minWidth: 0, fontFamily:'var(--serif-cn)', fontSize: 13, color:'var(--ink-2)', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{t.al}</div>
      <div style={{ width: 100 }}>
        <span className="meta" style={{ padding:'3px 8px', border:'1px solid var(--rule)', borderRadius: 999, color:'var(--ink-2)' }}>{t.mood}</span>
      </div>
      <div style={{ width: 40, textAlign:'center' }}>
        <button onClick={(e)=>{e.stopPropagation(); setLiked(!liked);}} style={{ background:'none', border:'none', color: liked?'var(--mood-b)':'var(--ink-3)', cursor:'pointer', fontSize: 18, lineHeight: 1 }}>{liked?'♥':'♡'}</button>
      </div>
      <div style={{ width: 60, textAlign:'right', fontFamily:'var(--mono)', fontSize: 12, color:'var(--ink-3)' }}>{t.m}</div>
    </div>
  );
}

window.PlaylistDetail = PlaylistDetail;
