// moodfm-frontend/src/screens/Home.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { MoodBlob, MoodWheel, Icon, Logo } from '../components/atoms';
import { radioApi } from '../api/radio';
import { useAuthStore } from '../store/authStore';
import { usePlayerStore } from '../store/playerStore';

const SCENES = ['通勤', '学习', '跑步', '写作', '睡前', '派对', '深夜'];

function formatRelTime(t) {
  if (!t) return '—';
  const diff = Date.now() - new Date(t).getTime();
  if (diff < 3600000) return `${Math.floor(diff / 60000)} 分钟前`;
  if (diff < 86400000) return `${Math.floor(diff / 3600000)} 小时前`;
  return new Date(t).toLocaleDateString('zh-CN', { month: 'long', day: 'numeric' });
}

function MiniPlayer({ song, playing, onPlay, onNext, onPrev, onToggle }) {
  if (!song) return null;
  return (
    <div style={{
      position:'fixed', left:24, right:24, bottom:18, height:64,
      background:'var(--ink)', color:'var(--bg)', borderRadius:999,
      padding:'0 8px', display:'flex', alignItems:'center', gap:12,
      cursor:'pointer', boxShadow:'0 12px 40px rgba(0,0,0,0.18)', zIndex:10,
    }}>
      <MoodBlob size={48} drift={true} geometry="circle"/>
      <div style={{ flex:1, minWidth:0 }}>
        <div style={{ fontFamily:'var(--serif-cn)', fontSize:14, fontWeight:500, whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>
          {song.title || song.name || '—'}
        </div>
        <div className="mono" style={{ fontSize:10, letterSpacing:'.14em', opacity:.7, marginTop:2 }}>
          {song.artist || song.artistName || '—'} · {song.platform || 'NETEASE'}
        </div>
      </div>
      <div className="row" style={{ gap:4, paddingRight:4 }}>
        <button onClick={onPrev} style={iconBtnDark}><Icon.prev/></button>
        <button onClick={onToggle} style={{ ...iconBtnDark, background:'var(--bg)', color:'var(--ink)' }}>
          {playing ? <Icon.pause/> : <Icon.play/>}
        </button>
        <button onClick={onNext} style={iconBtnDark}><Icon.next/></button>
      </div>
    </div>
  );
}
const iconBtnDark = { width:36, height:36, borderRadius:'50%', border:'none', background:'transparent', color:'var(--bg)', cursor:'pointer', display:'inline-flex', alignItems:'center', justifyContent:'center' };

export default function Home() {
  const navigate = useNavigate();
  const user = useAuthStore(s => s.user);
  const logout = useAuthStore(s => s.logout);
  const { session, queue, currentIndex, playing, setSession, setPlaying, next, prev } = usePlayerStore();
  const currentSong = queue[currentIndex] || null;

  const [input, setInput] = useState('');
  const [scene, setScene] = useState('通勤');
  const [moodPos, setMoodPos] = useState({ x: 0.62, y: 0.32 });
  const [loading, setLoading] = useState(false);
  const [sessions, setSessions] = useState([]);

  useEffect(() => {
    radioApi.getSessions(4).then(res => {
      if (res.code === 200) setSessions(res.data || []);
    }).catch(() => {});
  }, []);

  const hour = new Date().getHours();
  const greet = hour < 11 ? '早安' : hour < 18 ? '下午好' : hour < 23 ? '晚上好' : '深夜好';
  const greetEn = hour < 11 ? 'Good morning' : hour < 18 ? 'Good afternoon' : hour < 23 ? 'Good evening' : 'Late night';

  const FOR_THE_HOUR = hour < 6
    ? { range: '00:00 – 06:00', name: '深夜信号', desc: '静下来，只剩你和音乐。', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%)', light: false }
    : hour < 11
    ? { range: '06:00 – 11:00', name: '晨间电台', desc: '新的一天，从一段旋律开始。', gradient: 'linear-gradient(135deg, #ffd89b 0%, #f5a623 50%, #f093fb 100%)', light: true }
    : hour < 18
    ? { range: '11:00 – 18:00', name: '午后频率', desc: '专注与漫游之间的那道频率。', gradient: 'linear-gradient(135deg, #4facfe 0%, #43e97b 100%)', light: true }
    : hour < 23
    ? { range: '18:00 – 23:00', name: '黄昏电台', desc: '城市开始沉下去，音乐浮起来。', gradient: 'linear-gradient(135deg, #f7971e 0%, #f64f59 100%)', light: false }
    : { range: '23:00 – 00:00', name: '深夜信号', desc: '让呼吸放慢到音乐的速度。', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%)', light: false };

  const startRadio = async (method = 'text') => {
    setLoading(true);
    try {
      const payload =
        method === 'text'  ? { inputType: 'TEXT', textInput: input || '随机心情' } :
        method === 'scene' ? { inputType: 'SCENE', scene } :
        method === 'mood'  ? { inputType: 'MOOD_WHEEL', moodX: moodPos.x, moodY: moodPos.y } :
                             { inputType: 'SILENT' };
      const res = await radioApi.startRadio(payload);
      if (res.code === 200) {
        const { sessionId, moodSummary, scene, playlistId, songs } = res.data;
        setSession({ id: sessionId, moodSummary, scene, playlistId }, songs || []);
        navigate('/player');
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div data-mood="dusk" className="mfm" style={{ minHeight:'100vh' }}>
      <div className="mood-blob drift" style={{ width:760, height:760, right:-220, top:-260, opacity:0.4 }}/>

      {/* Nav */}
      <div style={{
        position:'sticky', top:0, zIndex:5, background:'var(--bg)',
        padding:'22px 56px', borderBottom:'1px solid var(--rule)',
        display:'flex', alignItems:'center', justifyContent:'space-between',
      }}>
        <div className="row" style={{ gap:10 }}>
          <Logo size={24}/>
          <div style={{ fontFamily:'var(--serif-en)', fontSize:20, fontStyle:'italic' }}>MoodFM</div>
          <div className="row mono" style={{ marginLeft:32, gap:22, fontSize:11, letterSpacing:'.16em', textTransform:'uppercase', color:'var(--ink-2)' }}>
            <span style={{ color:'var(--ink)' }}>· 电台 Radio</span>
            <span style={{ cursor:'pointer' }} onClick={() => navigate('/bind')}>绑定 Bind</span>
            <span style={{ cursor:'pointer' }} onClick={() => navigate('/calendar')}>历史 History</span>
            <span style={{ cursor:'pointer' }} onClick={() => navigate('/insights')}>画像 Insights</span>
          </div>
        </div>
        <div className="row" style={{ gap:14 }}>
          <span className="mono" style={{ fontSize:10, letterSpacing:'.14em', color:'var(--ink-3)' }}>NETEASE · 默认</span>
          <Icon.search/>
          <div style={{ width:30, height:30, borderRadius:'50%', background:'var(--bg-2)', border:'1px solid var(--rule)', fontSize:12, display:'flex', alignItems:'center', justifyContent:'center', fontFamily:'var(--serif-cn)', cursor:'pointer' }} onClick={logout}>
            {user?.nickname?.[0] || '我'}
          </div>
        </div>
      </div>

      <div style={{
        position:'relative', zIndex:2, padding:'40px 56px 80px',
        display:'grid', gridTemplateColumns:'1.3fr 1fr', gap:56,
      }}>
        {/* LEFT */}
        <div>
          <div className="meta">{greetEn.toUpperCase()} · {new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</div>
          <h1 className="display" style={{ fontSize:96, margin:'8px 0 0' }}>
            {greetEn}<em style={{ color:'var(--ink-3)' }}>,</em>
          </h1>
          <div className="display-cn" style={{ fontSize:40, marginTop:4 }}>
            {greet}，{user?.nickname || '朋友'}。<span style={{ color:'var(--ink-3)' }}>今晚想听点什么？</span>
          </div>

          {/* Text input */}
          <div style={{ marginTop:36 }}>
            <div className="meta" style={{ marginBottom:10 }}>方式 A · IN YOUR OWN WORDS</div>
            <div style={{ position:'relative' }}>
              <textarea className="field" placeholder="此刻你在哪里、心里是什么颜色？比如：加班到很晚，需要一点不打扰我的电流声…"
                value={input} onChange={e=>setInput(e.target.value)}
                style={{ paddingRight:120, fontSize:16, minHeight:120 }}/>
              <button className="btn" onClick={() => startRadio('text')} disabled={loading}
                style={{ position:'absolute', right:10, bottom:10, height:40, padding:'0 16px', opacity:loading?0.7:1 }}>
                {loading ? '调台中…' : <>调台 <Icon.arrow/></>}
              </button>
            </div>
          </div>

          {/* Scenes */}
          <div style={{ marginTop:28 }}>
            <div className="meta" style={{ marginBottom:10 }}>方式 B · PRESET SCENES</div>
            <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
              {SCENES.map(s => (
                <button key={s} className={'btn-pill'+(s===scene?' active':'')} onClick={() => { setScene(s); startRadio('scene'); }}>
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Silent start */}
          <div style={{ marginTop:28, padding:'22px 26px', border:'1px solid var(--rule)', borderRadius:18, display:'flex', justifyContent:'space-between', alignItems:'center', gap:16, background:'var(--paper)' }}>
            <div>
              <div className="serif-en" style={{ fontSize:30 }}>Just play.</div>
              <div style={{ fontFamily:'var(--serif-cn)', fontSize:14, color:'var(--ink-2)', marginTop:2 }}>什么都别问 · 直接给我一个电台</div>
            </div>
            <button className="btn" onClick={() => startRadio('silent')} disabled={loading}>
              启动 <Icon.play/>
            </button>
          </div>
        </div>

        {/* RIGHT */}
        <div>
          <div className="meta" style={{ marginBottom:12 }}>方式 C · MOOD COMPASS · 心情色盘</div>
          <div style={{ display:'flex', justifyContent:'center' }}>
            <MoodWheel size={340} geometry="circle" value={moodPos} onChange={setMoodPos}/>
          </div>
          <div className="meta" style={{ textAlign:'center', marginTop:14, color:'var(--ink-2)' }}>
            DRAG · 拖动球点选择此刻的心情坐标
          </div>
          <div style={{ marginTop:16, textAlign:'center' }}>
            <button className="btn" onClick={() => startRadio('mood')} disabled={loading}>
              按心情调台 <Icon.arrow/>
            </button>
          </div>

          {/* FOR THE HOUR */}
          <div style={{ marginTop:28 }}>
            <div className="meta" style={{ marginBottom:10 }}>今日推荐 · FOR THE HOUR</div>
            <div style={{
              borderRadius:18, padding:'20px 22px', background:FOR_THE_HOUR.gradient,
              color: FOR_THE_HOUR.light ? 'rgba(0,0,0,0.85)' : '#fff',
              position:'relative', overflow:'hidden',
            }}>
              <div style={{ fontSize:10, letterSpacing:'.16em', fontFamily:'var(--mono)', opacity:0.7, textTransform:'uppercase' }}>
                {FOR_THE_HOUR.range}
              </div>
              <div style={{ fontFamily:'var(--serif-en)', fontSize:32, fontStyle:'italic', marginTop:6, lineHeight:1.1 }}>
                {FOR_THE_HOUR.name}
              </div>
              <div style={{ fontFamily:'var(--serif-cn)', fontSize:13, marginTop:8, opacity:0.85, lineHeight:1.6 }}>
                {FOR_THE_HOUR.desc}
              </div>
              <button
                className="btn"
                onClick={() => startRadio('scene')}
                disabled={loading}
                style={{
                  marginTop:16, height:36, padding:'0 14px', fontSize:12,
                  background: FOR_THE_HOUR.light ? 'rgba(0,0,0,0.15)' : 'rgba(255,255,255,0.2)',
                  color: FOR_THE_HOUR.light ? 'rgba(0,0,0,0.85)' : '#fff',
                  border: `1px solid ${FOR_THE_HOUR.light ? 'rgba(0,0,0,0.2)' : 'rgba(255,255,255,0.3)'}`,
                  backdropFilter:'blur(8px)',
                }}
              >
                播放此时段 <Icon.arrow/>
              </button>
            </div>
          </div>

          {/* Continue current session */}
          <div style={{ marginTop:28 }}>
            <div className="meta" style={{ marginBottom:10 }}>继续 · CONTINUE</div>
            {session ? (
              <div className="row" style={{ gap:12, padding:14, border:'1px solid var(--rule)', borderRadius:16, alignItems:'center', cursor:'pointer' }} onClick={() => navigate('/player')}>
                <MoodBlob size={56} drift={false} geometry="circle"/>
                <div style={{ flex:1 }}>
                  <div style={{ fontFamily:'var(--serif-cn)', fontSize:15, fontWeight:500 }}>当前电台</div>
                  <div className="meta" style={{ marginTop:2 }}>剩 {queue.length - currentIndex} 首</div>
                </div>
                <button className="btn-pill"><Icon.play/></button>
              </div>
            ) : (
              <div style={{ padding:14, border:'1px dashed var(--rule)', borderRadius:16, textAlign:'center', fontFamily:'var(--serif-cn)', fontSize:14, color:'var(--ink-3)' }}>
                尚无进行中的电台
              </div>
            )}
          </div>

          {/* Recent sessions — 2×2 grid */}
          {sessions.length > 0 && (
            <div style={{ marginTop:28 }}>
              <div className="meta" style={{ marginBottom:10 }}>最近 · RECENT</div>
              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>
                {sessions.map((s, i) => {
                  const moods = ['dusk','night','dawn','day'];
                  return (
                    <div key={s.id} data-mood={moods[i % moods.length]}
                      style={{ padding:'14px 16px', border:'1px solid var(--rule)', borderRadius:16, cursor:'default', background:'var(--paper)' }}>
                      <MoodBlob size={36} drift={false} geometry="circle"/>
                      <div className="meta" style={{ marginTop:10, opacity:0.6 }}>{s.scene || '—'}</div>
                      <div style={{ fontFamily:'var(--serif-cn)', fontSize:13, fontWeight:500, marginTop:4, whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>
                        {s.moodSummary || s.scene || '即兴电台'}
                      </div>
                      <div className="meta" style={{ marginTop:6, opacity:0.5 }}>
                        {formatRelTime(s.startedAt)}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      <MiniPlayer song={currentSong} playing={playing} onToggle={() => setPlaying(!playing)} onNext={next} onPrev={prev}/>
    </div>
  );
}

// moodfm-frontend/src/views/home/Home.vue
<template>
  <div class="home-page" :data-mood="currentMoodPreset">
    <!-- Background mood blob decoration -->
    <div
      class="mood-blob drift"
      style="width: 760px; height: 760px; right: -220px; top: -260px; opacity: 0.4; z-index: 0;"
    />

    <!-- Top nav -->
    <NavBar />

    <!-- Main two-column content -->
    <div class="home-content">
      <!-- LEFT — Input area -->
      <div class="home-left">
        <div class="meta">{{ greetEnUpper }} · {{ todayLabel }}</div>
        <h1 class="display home-headline">
          {{ greetEn }}<em style="color: var(--ink-3)">,</em>
        </h1>
        <div class="display-cn home-subheadline">
          {{ greetCn }}，{{ userName }}。<span style="color: var(--ink-3)">今晚想听点什么？</span>
        </div>

        <!-- Method A: text input -->
        <div class="home-section">
          <div class="meta" style="margin-bottom: 10px">方式 A · IN YOUR OWN WORDS</div>
          <div class="textarea-wrap">
            <textarea
              v-model="moodInput"
              class="field"
              placeholder="此刻你在哪里、心里是什么颜色？比如：加班到很晚，需要一点不打扰我的电流声…"
              rows="4"
            />
            <button
              class="btn btn-inline"
              :disabled="radio.isLoading"
              @click="handleStartRadio"
            >
              {{ radio.isLoading ? '调台中…' : '调台' }}
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
            </button>
          </div>
        </div>

        <!-- Method B: preset scenes -->
        <div class="home-section">
          <div class="meta" style="margin-bottom: 10px">方式 B · PRESET SCENES</div>
          <div class="scene-tags">
            <button
              v-for="s in scenes"
              :key="s"
              class="btn-pill"
              :class="{ active: selectedScene === s }"
              @click="handleSceneSelect(s)"
            >
              {{ s }}
            </button>
          </div>
        </div>

        <!-- Method C: Just play -->
        <div class="just-play-card">
          <div>
            <div class="just-play-title" style="font-family: var(--serif-en); font-style: italic">Just play.</div>
            <div style="font-family: var(--serif-cn); font-size: 14px; color: var(--ink-2); margin-top: 2px">什么都别问 · 直接给我一个电台</div>
          </div>
          <button class="btn" :disabled="radio.isLoading" @click="handleJustPlay">
            启动
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>
          </button>
        </div>

        <!-- Session duration selector -->
        <div class="home-section">
          <div class="meta" style="margin-bottom: 10px">电台时长 · SESSION DURATION</div>
          <div class="duration-ctrl">
            <button
              v-for="opt in durationOptions"
              :key="opt.value"
              class="duration-opt"
              :class="{ 'duration-opt--active': sessionDuration === opt.value }"
              @click="sessionDuration = opt.value"
            >{{ opt.label }}</button>
          </div>
        </div>
      </div>

      <!-- RIGHT — MoodWheel + Resume + Recommendation -->
      <div class="home-right">
        <!-- Mood compass (SVG-based) -->
        <div class="meta" style="margin-bottom: 12px">方式 C · MOOD COMPASS · 心情色盘</div>
        <div class="mood-wheel-wrap">
          <MoodWheel :size="340" @change="onWheelChange" />
        </div>
        <div class="meta" style="text-align: center; margin-top: 14px; color: var(--ink-2)">
          DRAG · 拖动球点选择此刻的心情坐标
        </div>

        <!-- Resume last session -->
        <div class="home-section">
          <div class="meta" style="margin-bottom: 10px">继续 · CONTINUE</div>
          <div v-if="lastSession" class="resume-card">
            <MoodBlob :size="56" :drift="false" geometry="circle" />
            <div class="resume-info">
              <div style="font-family: var(--serif-cn); font-size: 15px; font-weight: 500">
                {{ lastSession.moodText || '上次的电台' }}
              </div>
              <div class="meta" style="margin-top: 2px">
                {{ lastSession.scene ? lastSession.scene + ' · ' : '' }}{{ formatSessionDate(lastSession.createdAt) }}
              </div>
            </div>
            <button class="btn-pill" @click="resumeSession(lastSession)">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>
            </button>
          </div>
          <div v-else class="resume-card resume-card--empty">
            <div class="meta" style="color: var(--ink-3)">暂无最近电台记录</div>
          </div>
        </div>

        <!-- Today's recommendation -->
        <div class="home-section">
          <div class="meta" style="margin-bottom: 10px">今日推荐 · FOR THE HOUR</div>
          <div class="recommend-card" style="cursor:pointer;" @click="handleRecommendPlay">
            <div class="recommend-bg" />
            <div class="recommend-content">
              <div class="mono" style="font-size: 10px; letter-spacing: .16em; opacity: .85">{{ recommendTimeLabel }}</div>
              <div class="serif-en recommend-title">{{ recommendTitle }}</div>
              <div style="font-size: 14px; margin-top: 4px; opacity: .9">{{ recommendSubtitle }}</div>
              <div class="mono" style="font-size: 10px; letter-spacing: .12em; opacity: .7; margin-top: 8px">▶ 立即播放</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Recent sessions strip -->
    <div class="home-recent">
      <div class="between" style="margin-bottom: 14px">
        <div class="meta">最近的电台 · RECENT STATIONS</div>
        <RouterLink to="/history" class="meta" style="color: var(--ink-2); text-decoration: none">查看全部 →</RouterLink>
      </div>
      <div class="recent-grid">
        <div
          v-for="(s, i) in displayedSessions"
          :key="s.sessionId"
          class="recent-card"
          :data-mood="s.moodPreset || 'dusk'"
          @click="resumeSession(s)"
        >
          <MoodBlob :size="260" :drift="false" geometry="blob" style="margin-bottom: 10px; pointer-events: none" />
          <div class="meta">№ 0{{ i + 1 }} · {{ (s.scene || s.moodPreset || '电台').toUpperCase() }}</div>
          <div style="font-family: var(--serif-cn); font-size: 18px; font-weight: 500; margin-top: 4px">
            {{ s.moodText || '情绪电台' }}
          </div>
          <div class="meta" style="margin-top: 6px; color: var(--ink-2)">{{ formatSessionDate(s.createdAt) }}</div>
        </div>

        <!-- Placeholder cards when not enough sessions -->
        <template v-if="displayedSessions.length < 4">
          <div
            v-for="p in placeholders"
            :key="'ph-' + p.id"
            class="recent-card recent-card--placeholder"
            :data-mood="p.mood"
          >
            <MoodBlob :size="260" :drift="false" geometry="blob" style="margin-bottom: 10px; pointer-events: none" />
            <div class="meta">{{ p.tag }}</div>
            <div style="font-family: var(--serif-cn); font-size: 18px; font-weight: 500; margin-top: 4px">{{ p.title }}</div>
            <div class="meta" style="margin-top: 6px; color: var(--ink-2)">{{ p.sub }}</div>
          </div>
        </template>
      </div>
    </div>

    <!-- Mini player (fixed bottom) -->
    <MiniPlayer />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useRadioStore } from '@/stores/radio'
import { usePlayerStore } from '@/stores/player'
import { useUiStore } from '@/stores/ui'
import NavBar from '@/components/common/NavBar.vue'
import MoodBlob from '@/components/common/MoodBlob.vue'
import MiniPlayer from '@/components/common/MiniPlayer.vue'
import MoodWheel from './MoodWheel.vue'
import type { RadioSession } from '@/types'

const router = useRouter()
const auth = useAuthStore()
const radio = useRadioStore()
const player = usePlayerStore()
const ui = useUiStore()

// ── Greeting ───────────────────────────────────────────────────────────────
const hour = new Date().getHours()
const greetEn = hour < 11 ? 'Good morning' : hour < 18 ? 'Good afternoon' : hour < 23 ? 'Good evening' : 'Late night'
const greetCn = hour < 11 ? '早安' : hour < 18 ? '下午好' : hour < 23 ? '晚上好' : '深夜好'
const greetEnUpper = greetEn.toUpperCase()
const todayLabel = new Date().toLocaleDateString('zh-CN', { month: 'long', day: 'numeric' })

const userName = computed(() => auth.user?.username ?? '旅人')

// ── Mood input ──────────────────────────────────────────────────────────────
const moodInput = ref('')
const selectedScene = ref('')
const sessionDuration = ref(30)

const scenes = ['通勤', '学习', '跑步', '写作', '睡前', '派对', '深夜', '+ 自定义']

const durationOptions = [
  { value: 15, label: '15min' },
  { value: 30, label: '30min' },
  { value: 60, label: '60min' },
  { value: 120, label: '120min' },
  { value: 0, label: '无限' },
]

function handleSceneSelect(scene: string) {
  if (scene === '+ 自定义') return
  selectedScene.value = scene === selectedScene.value ? '' : scene
  radio.setScene(selectedScene.value)
}

// ── MoodWheel callback ──────────────────────────────────────────────────────
function onWheelChange(_x: number, _y: number) {
  // Future: map coordinates to mood preset
}

// ── Radio actions ───────────────────────────────────────────────────────────
async function handleStartRadio() {
  const text = moodInput.value.trim() || selectedScene.value || '随机'
  radio.setMoodText(text)
  try {
    await radio.startRadio({ moodText: text, scene: selectedScene.value || undefined, durationMinutes: sessionDuration.value || undefined })
    router.push('/player')
  } catch {
    // silently fail – backend may not be running in dev
    router.push('/player')
  }
}

async function handleRecommendPlay() {
  const text = recommendTitle.value
  radio.setMoodText(text)
  try {
    await radio.startRadio({ moodText: text, durationMinutes: sessionDuration.value || undefined })
  } catch {}
  router.push('/player')
}

async function handleJustPlay() {
  radio.setMoodText('随机')
  try {
    await radio.startRadio({ moodText: '随机', durationMinutes: sessionDuration.value || undefined })
  } catch {
    // dev: navigate anyway
  }
  router.push('/player')
}

async function resumeSession(session: RadioSession) {
  radio.setMoodText(session.moodText)
  if (session.scene) radio.setScene(session.scene)
  try {
    await radio.startRadio({
      moodText: session.moodText || '随机',
      scene: session.scene || undefined,
      durationMinutes: sessionDuration.value || undefined,
    })
    router.push('/player')
  } catch {
    // failed to load songs — stay on home
  }
}

// ── Sessions ────────────────────────────────────────────────────────────────
const lastSession = computed<RadioSession | null>(() => radio.recentSessions[0] ?? null)
const displayedSessions = computed(() => radio.recentSessions.slice(0, 4))

const currentMoodPreset = computed(() => ui.moodPreset)

// Placeholder cards shown when no sessions yet
const placeholderData = [
  { id: 1, title: '通勤的余光', tag: '平静 · 中能量', sub: '14 首 · 52 MIN', mood: 'dusk' },
  { id: 2, title: '雨打窗台',   tag: '忧郁 · 低能量', sub: '9 首 · 34 MIN',  mood: 'melancholy' },
  { id: 3, title: '清晨慢跑',   tag: '明亮 · 高能量', sub: '18 首 · 61 MIN', mood: 'energetic' },
  { id: 4, title: '专注写作',   tag: '冷静 · 中能量', sub: '12 首 · 48 MIN', mood: 'focused' },
]
const placeholders = computed(() =>
  placeholderData.slice(0, Math.max(0, 4 - displayedSessions.value.length)),
)

function formatSessionDate(isoStr: string): string {
  try {
    const d = new Date(isoStr)
    return d.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  } catch {
    return ''
  }
}

// ── Recommendation card (time-based) ───────────────────────────────────────
const recommendTimeLabel = computed(() => {
  if (hour >= 5 && hour < 12) return '05:00 — 12:00'
  if (hour >= 12 && hour < 18) return '12:00 — 18:00'
  if (hour >= 18 && hour < 23) return '18:00 — 23:00'
  return '23:00 — 02:00'
})
const recommendTitle = computed(() => {
  if (hour >= 5 && hour < 12) return 'morning haze'
  if (hour >= 12 && hour < 18) return 'afternoon float'
  if (hour >= 18 && hour < 23) return 'evening drift'
  return 'night float'
})
const recommendSubtitle = computed(() => {
  if (hour >= 5 && hour < 12) return '晨雾漂浮电台 · 10 首 · 38 min'
  if (hour >= 12 && hour < 18) return '午后漫游电台 · 15 首 · 55 min'
  if (hour >= 18 && hour < 23) return '黄昏流浪电台 · 12 首 · 46 min'
  return '深夜漂浮电台 · 13 首 · 49 min'
})

// ── Lifecycle ───────────────────────────────────────────────────────────────
onMounted(async () => {
  try {
    await radio.fetchRecentSessions()
  } catch {
    // no-op in dev
  }
})
</script>

<style scoped>
/* ── Page wrapper ─────────────────────────────────────────────────── */
.home-page {
  min-height: 100vh;
  position: relative;
  overflow-x: hidden;
  padding-bottom: 100px; /* room for MiniPlayer */
}

/* ── Two-column main content ─────────────────────────────────────── */
.home-content {
  position: relative;
  z-index: 2;
  padding: 40px 56px 80px;
  display: grid;
  grid-template-columns: 1.3fr 1fr;
  gap: 56px;
}

@media (max-width: 900px) {
  .home-content {
    grid-template-columns: 1fr;
    padding: 24px 22px 80px;
    gap: 28px;
  }
}

/* ── Greeting ─────────────────────────────────────────────────────── */
.home-headline {
  font-size: 96px;
  margin: 8px 0 0;
  line-height: 0.92;
}

.home-subheadline {
  font-size: 40px;
  margin-top: 4px;
}

@media (max-width: 900px) {
  .home-headline    { font-size: 52px; }
  .home-subheadline { font-size: 28px; }
}

/* ── Section spacer ──────────────────────────────────────────────── */
.home-section {
  margin-top: 28px;
}

/* ── Textarea with inline button ─────────────────────────────────── */
.textarea-wrap {
  position: relative;
}

.textarea-wrap .field {
  padding-right: 120px;
  font-size: 16px;
  min-height: 120px;
  resize: none;
}

.btn-inline {
  position: absolute;
  right: 10px;
  bottom: 10px;
  height: 40px;
  padding: 0 16px;
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

@media (max-width: 900px) {
  .textarea-wrap .field {
    padding-right: 16px;
    font-size: 15px;
    min-height: 110px;
  }

  .btn-inline {
    position: static;
    width: 100%;
    justify-content: center;
    margin-top: 10px;
    height: 46px;
  }
}

/* ── Scene tags ──────────────────────────────────────────────────── */
.scene-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

/* ── Just play card ──────────────────────────────────────────────── */
.just-play-card {
  margin-top: 28px;
  padding: 22px 26px;
  border: 1px solid var(--rule);
  border-radius: 18px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
  background: var(--paper);
  transition: box-shadow 0.22s ease, border-color 0.22s ease;
}

.just-play-card:hover {
  border-color: var(--ink-3);
  box-shadow: 0 4px 20px rgba(110, 92, 217, 0.1);
}

.just-play-title {
  font-size: 30px;
  line-height: 1.1;
}

@media (max-width: 900px) {
  .just-play-card {
    padding: 18px;
  }
  .just-play-title { font-size: 24px; }
}

/* ── MoodWheel wrapper ───────────────────────────────────────────── */
.mood-wheel-wrap {
  display: flex;
  justify-content: center;
}

/* ── Resume card ─────────────────────────────────────────────────── */
.resume-card {
  display: flex;
  gap: 12px;
  padding: 14px;
  border: 1px solid var(--rule);
  border-radius: 16px;
  align-items: center;
  background: var(--paper);
  cursor: pointer;
  transition: border-color 0.15s;
}

.resume-card:hover {
  border-color: var(--ink-3);
  box-shadow: 0 4px 16px rgba(110, 92, 217, 0.12);
}

.resume-card--empty {
  justify-content: center;
  cursor: default;
}

.resume-card--empty:hover {
  border-color: var(--rule);
}

.resume-info {
  flex: 1;
  min-width: 0;
}

/* ── Recommendation card ─────────────────────────────────────────── */
.recommend-card {
  position: relative;
  overflow: hidden;
  border-radius: 16px;
  min-height: 120px;
  color: var(--paper);
}

.recommend-bg {
  position: absolute;
  inset: 0;
  background:
    radial-gradient(circle at 20% 20%, var(--mood-a) 0%, transparent 60%),
    radial-gradient(circle at 80% 30%, var(--mood-b) 0%, transparent 60%),
    radial-gradient(circle at 60% 90%, var(--mood-d) 0%, transparent 70%);
  background-color: var(--mood-c);
}

.recommend-content {
  position: relative;
  padding: 16px;
}

.recommend-title {
  font-size: 36px;
  line-height: 1;
  margin-top: 6px;
}

/* ── Recent sessions strip ───────────────────────────────────────── */
.home-recent {
  position: relative;
  padding: 0 56px 100px;
}

@media (max-width: 900px) {
  .home-recent {
    padding: 0 22px 140px;
  }
}

.recent-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
}

@media (max-width: 900px) {
  .recent-grid {
    grid-template-columns: repeat(3, 240px);
    overflow-x: auto;
    padding-bottom: 8px;
  }
}

@media (max-width: 600px) {
  .recent-grid {
    grid-template-columns: repeat(3, 200px);
  }
}

.recent-card {
  border: 1px solid var(--rule);
  border-radius: 16px;
  padding: 14px;
  background: var(--paper);
  cursor: pointer;
  transition: border-color 0.18s ease,
            transform 0.2s cubic-bezier(0.34, 1.56, 0.64, 1),
            box-shadow 0.22s ease;
  overflow: hidden;
}

.recent-card:hover {
  border-color: var(--ink-3);
  transform: translateY(-3px);
  box-shadow: 0 8px 28px rgba(110, 92, 217, 0.14), 0 2px 8px rgba(26,23,20,0.06);
}

.recent-card--placeholder {
  cursor: default;
  opacity: 0.6;
}

.recent-card--placeholder:hover {
  border-color: var(--rule);
  transform: none;
}

/* ── Duration selector ─────────────────────────────────────────────── */
.duration-ctrl {
  display: flex;
  gap: 0;
  border: 1px solid var(--rule);
  border-radius: 999px;
  padding: 2px;
  width: fit-content;
}

.duration-opt {
  padding: 6px 14px;
  border-radius: 999px;
  border: none;
  cursor: pointer;
  background: transparent;
  color: var(--ink-2);
  font-family: var(--mono);
  font-size: 12px;
  letter-spacing: 0.05em;
  white-space: nowrap;
  transition: background 0.15s, color 0.15s;
}

.duration-opt--active {
  background: var(--ink);
  color: var(--bg);
}

/* ── Home enter animations ─────────────────────────── */
@keyframes home-rise {
  from { opacity: 0; transform: translateY(12px); }
  to   { opacity: 1; transform: translateY(0); }
}

.home-left {
  animation: home-rise 0.5s cubic-bezier(0.16, 1, 0.3, 1) 0.08s both;
}

.home-right {
  animation: home-rise 0.5s cubic-bezier(0.16, 1, 0.3, 1) 0.18s both;
}

/* ── Recent cards stagger ─────────────────────────── */
@keyframes card-rise {
  from { opacity: 0; transform: translateY(10px); }
  to   { opacity: 1; transform: translateY(0); }
}

.recent-card:nth-child(1) { animation: card-rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) 0.12s both; }
.recent-card:nth-child(2) { animation: card-rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) 0.19s both; }
.recent-card:nth-child(3) { animation: card-rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) 0.26s both; }
.recent-card:nth-child(4) { animation: card-rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) 0.33s both; }
</style>
