// moodfm-frontend/src/screens/Loved.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon } from '../components/atoms';
import { playlistApi } from '../api/playlist';

function fmtDuration(seconds) {
  if (!seconds) return '';
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
}

export default function Loved() {
  const navigate = useNavigate();
  const [songs, setSongs]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    playlistApi.loved()
      .then(d => { setSongs(Array.isArray(d) ? d : []); setLoading(false); })
      .catch(() => { setError('加载失败，请稍后重试'); setLoading(false); });
  }, []);

  const handleUnlike = async (e, songId) => {
    e.stopPropagation();
    await playlistApi.toggleLike(songId).catch(() => {});
    setSongs(prev => prev.filter(s => s.id !== songId));
  };

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--ink)' }}>
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--bg)', borderBottom: '1px solid var(--rule)',
        padding: '14px 20px', display: 'flex', alignItems: 'center', gap: 12,
      }}>
        <button onClick={() => navigate(-1)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink)', display: 'flex', alignItems: 'center' }}>
          <Icon.chevL/>
        </button>
        <h1 style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, margin: 0, flex: 1 }}>我喜欢的音乐</h1>
        <span className="mono" style={{ fontSize: 11, opacity: 0.45 }}>{songs.length} 首</span>
      </div>

      <div style={{ padding: '24px 20px 80px', maxWidth: 720, margin: '0 auto' }}>
        <div className="meta" style={{ marginBottom: 6 }}>LIKED SONGS · 红心歌曲</div>
        <h2 className="display" style={{ fontSize: 52, margin: '6px 0 28px', lineHeight: 1 }}>Loved.</h2>

        {loading && <div className="mono" style={{ opacity: 0.5 }}>加载中…</div>}
        {error   && <div style={{ color: 'var(--mood-b, #e05)', fontFamily: 'var(--serif-cn)' }}>{error}</div>}

        {!loading && !error && songs.length === 0 && (
          <div style={{ textAlign: 'center', paddingTop: 60, opacity: 0.4, fontFamily: 'var(--serif-cn)' }}>
            还没有红心歌曲 · 在播放器中点击红心收藏
          </div>
        )}

        {!loading && !error && songs.map((s, i) => (
          <div key={s.id}
            onClick={() => navigate(`/song/${s.id}`)}
            style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '10px 0', borderBottom: '1px solid var(--rule)', cursor: 'pointer' }}
          >
            <span className="mono" style={{ width: 24, textAlign: 'right', opacity: 0.35, fontSize: 12, flexShrink: 0 }}>{i + 1}</span>
            <div style={{ width: 44, height: 44, borderRadius: 6, background: 'var(--paper)', overflow: 'hidden', flexShrink: 0, border: '1px solid var(--rule)' }}>
              {s.coverUrl
                ? <img src={s.coverUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                : <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.2 }}>♪</div>
              }
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 14, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{s.title}</div>
              <div className="mono" style={{ fontSize: 11, opacity: 0.5, marginTop: 2 }}>{s.artist}</div>
            </div>
            <div className="mono" style={{ fontSize: 12, opacity: 0.4, flexShrink: 0 }}>{fmtDuration(s.durationSeconds)}</div>
            <button
              onClick={(e) => handleUnlike(e, s.id)}
              style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--mood-a, #e05)', fontSize: 16, flexShrink: 0 }}
              title="取消红心"
            >♥</button>
          </div>
        ))}
      </div>
    </div>
  );
}

// moodfm-frontend/src/views/library/Loved.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { usePlayerStore } from '@/stores/player'
import MoodBlob from '@/components/common/MoodBlob.vue'
import { playlistApi } from '@/api/playlist'

const router = useRouter()
const player = usePlayerStore()
const src = ref('全部')
const loading = ref(true)
const error = ref<string | null>(null)

interface SongItem { t: string; a: string; al: string; d: string; src: string; mood: string; when: string }

const songs = ref<SongItem[]>([])

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

function toPlatformLabel(p: string): string {
  return p === 'netease' ? '网易云' : p === 'qqmusic' ? 'QQ' : p
}

onMounted(async () => {
  try {
    const data = await playlistApi.loved()
    songs.value = data.map(s => ({
      t: s.title,
      a: s.artist,
      al: s.album ?? '',
      d: formatDuration(s.duration),
      src: toPlatformLabel(s.platform),
      mood: 'calm',
      when: '',
    }))
  } catch (e: any) {
    error.value = e?.message ?? '加载失败'
  } finally {
    loading.value = false
  }
})

const filtered = computed(() =>
  src.value === '全部' ? songs.value : songs.value.filter(s => s.src === src.value || s.src === '两端均有')
)
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);padding-bottom:80px;">
    <div style="position:sticky;top:0;z-index:5;background:var(--bg);padding:22px 56px;
                border-bottom:1px solid var(--rule);display:flex;justify-content:space-between;align-items:center;">
      <button class="btn-pill" @click="router.back()">← Home</button>
      <div class="meta">SECTION VI · LOVED · 我的红心</div>
      <div style="width:60px;" />
    </div>

    <div style="padding:40px 56px;display:grid;grid-template-columns:1.1fr 2fr;gap:48px;">
      <div>
        <div class="meta">A LIVING DOCUMENT · 持续累积</div>
        <h1 class="display" style="font-size:120px;margin:10px 0 0;"><em>♥</em> Loved.</h1>
        <div class="display-cn" style="font-size:30px;margin-top:6px;color:var(--ink-2);">红心歌单 · 跨平台合并</div>

        <div style="margin-top:28px;padding:18px;border:1px solid var(--rule);border-radius:14px;background:var(--paper);">
          <div class="row" style="gap:8px;align-items:baseline;">
            <div class="display" style="font-size:40px;">{{ songs.length }}</div>
            <div class="meta">SONGS · 首</div>
          </div>
          <div class="meta" style="margin-top:10px;color:var(--ink-3);">· 网易云 86 · QQ 音乐 22 · 重叠 16</div>
          <hr class="rule" style="margin:16px 0;" />
          <div class="row" style="gap:8px;">
            <button class="btn" style="flex:1;" @click="player.play();router.push('/player')">随机播放 ▶</button>
            <button class="btn-pill">导出</button>
          </div>
        </div>

        <div style="margin-top:22px;">
          <div class="meta" style="margin-bottom:8px;">来源 / SOURCE</div>
          <div style="display:flex;flex-wrap:wrap;gap:6px;">
            <button
              v-for="s in ['全部','网易云','QQ','两端均有']"
              :key="s"
              :class="['btn-pill', src === s ? 'active' : '']"
              @click="src = s"
            >{{ s }}</button>
          </div>
        </div>
      </div>

      <div>
        <div
          v-for="(s, i) in filtered"
          :key="i"
          :data-mood="s.mood"
          class="row"
          style="gap:14px;padding:14px 4px;border-bottom:1px solid var(--rule);cursor:pointer;"
          @click="player.play();router.push('/player')"
        >
          <div class="mono" style="font-size:11px;color:var(--ink-3);width:26px;flex-shrink:0;">{{ String(i + 1).padStart(2, '00') }}</div>
          <MoodBlob :size="56" :drift="false" geometry="blob" style="flex-shrink:0;" />
          <div style="flex:1;min-width:0;">
            <div class="row" style="gap:8px;align-items:baseline;">
              <span style="font-family:var(--serif-en);font-style:italic;font-size:20px;
                           white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{ s.t }}</span>
              <span style="font-size:12px;color:var(--ink-3);white-space:nowrap;">· {{ s.a }}</span>
            </div>
            <div class="meta" style="margin-top:2px;color:var(--ink-3);">{{ s.al }}</div>
          </div>
          <span class="meta" style="color:var(--ink-3);min-width:70px;">{{ s.src }}</span>
          <span class="mono" style="font-size:12px;color:var(--ink-2);width:50px;text-align:right;flex-shrink:0;">{{ s.d }}</span>
          <span style="color:var(--mood-b);font-size:18px;flex-shrink:0;">♥</span>
        </div>
      </div>
    </div>
  </div>
</template>
