// moodfm-frontend/src/screens/Playlist.jsx
import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { MoodBlob, Icon, Logo } from '../components/atoms';
import { playlistApi } from '../api/playlist';
import { usePlayerStore } from '../store/playerStore';

function formatDuration(minutes) {
  if (!minutes) return '—';
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return h > 0 ? `${h}H ${m}M` : `${m} MIN`;
}

function TrackRow({ track, index, active, onPlay, onLikeToggle }) {
  const [hover, setHover] = useState(false);
  const [liked, setLiked] = useState(track.liked ?? false);

  const toggleLike = (e) => {
    e.stopPropagation();
    setLiked(l => !l);
    onLikeToggle?.(track.id, !liked);
  };

  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      onClick={() => onPlay(index)}
      className="row"
      style={{
        padding: '12px 16px', borderRadius: 8, cursor: 'pointer',
        background: active ? 'var(--bg-2)' : hover ? 'var(--bg-2)' : 'transparent',
        transition: 'background .15s',
      }}
    >
      {/* # */}
      <div style={{ width: 32, fontFamily: 'var(--mono)', fontSize: 13, color: active ? 'var(--ink)' : 'var(--ink-3)', flexShrink: 0 }}>
        {active ? '▸' : hover ? <Icon.play /> : String(index + 1).padStart(2, '0')}
      </div>

      {/* Title + Artist */}
      <div style={{ flex: 2.5, minWidth: 0 }}>
        <div style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 18, color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
          {track.title}
        </div>
        <div className="meta" style={{ marginTop: 2 }}>{track.artist}</div>
      </div>

      {/* Album */}
      <div style={{ flex: 1.5, minWidth: 0, fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--ink-2)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
        {track.album || '—'}
      </div>

      {/* Mood tag */}
      <div style={{ width: 100, flexShrink: 0 }}>
        {track.mood && (
          <span className="meta" style={{ padding: '3px 8px', border: '1px solid var(--rule)', borderRadius: 999, color: 'var(--ink-2)' }}>
            {track.mood}
          </span>
        )}
      </div>

      {/* Like */}
      <div style={{ width: 40, textAlign: 'center', flexShrink: 0 }}>
        <button onClick={toggleLike} style={{ background: 'none', border: 'none', color: liked ? 'var(--mood-b)' : 'var(--ink-3)', cursor: 'pointer', fontSize: 18, lineHeight: 1 }}>
          {liked ? '♥' : '♡'}
        </button>
      </div>

      {/* Duration */}
      <div style={{ width: 60, textAlign: 'right', fontFamily: 'var(--mono)', fontSize: 12, color: 'var(--ink-3)', flexShrink: 0 }}>
        {track.durationFormatted || '—'}
      </div>
    </div>
  );
}

function TrackRowMobile({ track, index, active, onPlay, onLikeToggle }) {
  const [liked, setLiked] = useState(track.liked ?? false);

  const toggleLike = (e) => {
    e.stopPropagation();
    setLiked(l => !l);
    onLikeToggle?.(track.id, !liked);
  };

  return (
    <div onClick={() => onPlay(index)} className="row" style={{ gap: 12, padding: '12px 6px', borderBottom: '1px solid var(--rule)', cursor: 'pointer' }}>
      <span className="mono" style={{ color: active ? 'var(--ink)' : 'var(--ink-3)', width: 22, fontSize: 12, flexShrink: 0 }}>
        {active ? '▸' : String(index + 1).padStart(2, '0')}
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 16, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{track.title}</div>
        <div className="meta" style={{ marginTop: 2 }}>{track.artist} {track.mood ? `· ${track.mood}` : ''}</div>
      </div>
      <button onClick={toggleLike} style={{ background: 'none', border: 'none', color: liked ? 'var(--mood-b)' : 'var(--ink-3)', cursor: 'pointer', fontSize: 18, lineHeight: 1, flexShrink: 0 }}>
        {liked ? '♥' : '♡'}
      </button>
      <div className="mono" style={{ color: 'var(--ink-3)', fontSize: 12, width: 36, textAlign: 'right', flexShrink: 0 }}>
        {track.durationFormatted || '—'}
      </div>
    </div>
  );
}

export default function Playlist() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { setSession } = usePlayerStore();

  const [playlist, setPlaylist] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [playingIndex, setPlayingIndex] = useState(-1);
  const [starting, setStarting] = useState(false);

  useEffect(() => {
    setLoading(true);
    playlistApi.getPlaylist(id)
      .then(res => {
        if (res.code === 200) setPlaylist(res.data);
        else setError(res.message || '歌单加载失败');
      })
      .catch(() => setError('网络错误，请刷新重试'))
      .finally(() => setLoading(false));
  }, [id]);

  const startPlay = async (startIndex = 0) => {
    setStarting(true);
    try {
      const res = await playlistApi.playFromPlaylist(id, startIndex);
      if (res.code === 200) {
        const { sessionId, moodSummary, scene, playlistId, songs } = res.data;
        setSession({ id: sessionId, moodSummary, scene, playlistId }, songs || []);
        navigate('/player');
      }
    } catch (e) {
      console.error(e);
    } finally {
      setStarting(false);
    }
  };

  if (loading) {
    return (
      <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, color: 'var(--ink-2)' }}>加载中…</div>
      </div>
    );
  }

  if (error || !playlist) {
    return (
      <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 20 }}>
        <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, color: 'var(--ink-2)' }}>{error || '歌单不存在'}</div>
        <button className="btn" onClick={() => navigate(-1)}><Icon.chevL /> 返回</button>
      </div>
    );
  }

  const tracks = playlist.tracks || [];
  const dominantMoods = playlist.dominantMoods || [];

  return (
    <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh' }}>
      {/* Top bar */}
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--bg)', padding: '18px 56px',
        borderBottom: '1px solid var(--rule)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <button onClick={() => navigate(-1)} className="btn-pill"><Icon.chevL /> 返回</button>
        <div className="meta">PLAYLIST · 歌单详情</div>
        <div className="row" style={{ gap: 8 }}>
          <div className="row" style={{ gap: 10 }}>
            <Logo size={20} />
            <div style={{ fontFamily: 'var(--serif-en)', fontSize: 18, fontStyle: 'italic' }}>MoodFM</div>
          </div>
        </div>
      </div>

      {/* Hero */}
      <div style={{ position: 'relative', overflow: 'hidden', padding: '56px 56px 48px', borderBottom: '1px solid var(--rule)' }}>
        <div className="mood-blob drift" style={{ width: 800, height: 800, right: -150, top: -220, opacity: 0.45 }} />

        <div style={{ position: 'relative', zIndex: 2, display: 'grid', gridTemplateColumns: '300px 1fr', gap: 48, alignItems: 'end' }}>
          {/* Cover */}
          <div>
            <div style={{ position: 'relative', width: 300, height: 300, borderRadius: 18, overflow: 'hidden', boxShadow: '0 24px 60px rgba(0,0,0,0.18)' }}>
              {playlist.coverUrl
                ? <img src={playlist.coverUrl} alt="cover" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                : <MoodBlob size={300} drift={true} geometry="blob" />
              }
              {playlist.name && (
                <div style={{ position: 'absolute', left: 14, bottom: 12, color: '#fff', textShadow: '0 1px 4px rgba(0,0,0,0.4)' }}>
                  <div className="mono" style={{ fontSize: 10, letterSpacing: '.2em', opacity: 0.9 }}>
                    {playlist.name.toUpperCase().slice(0, 20)}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Meta */}
          <div>
            <div className="meta">CURATED FOR YOU · 为你编排</div>
            <h1 className="display" style={{ fontSize: 108, margin: '12px 0 0', lineHeight: 0.95 }}>
              {playlist.name}<em style={{ opacity: 0.4 }}>.</em>
            </h1>
            {playlist.nameCn && (
              <div className="display-cn" style={{ fontSize: 32, marginTop: 4, color: 'var(--ink-2)' }}>{playlist.nameCn}</div>
            )}
            {playlist.description && (
              <p style={{ marginTop: 16, fontSize: 14, lineHeight: 1.7, color: 'var(--ink-2)', maxWidth: 520, fontFamily: 'var(--serif-cn)' }}>
                {playlist.description}
              </p>
            )}

            {/* Stats */}
            <div className="row" style={{ marginTop: 20, gap: 24, color: 'var(--ink-3)' }}>
              <div>
                <div className="meta">TRACKS</div>
                <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>{playlist.trackCount ?? tracks.length}</div>
              </div>
              {playlist.totalDurationMinutes && (
                <div>
                  <div className="meta">DURATION</div>
                  <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>{formatDuration(playlist.totalDurationMinutes)}</div>
                </div>
              )}
              {playlist.updatedAt && (
                <div>
                  <div className="meta">UPDATED</div>
                  <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>
                    {new Date(playlist.updatedAt).toLocaleDateString('zh-CN', { month: 'long', day: 'numeric' })}
                  </div>
                </div>
              )}
              {dominantMoods.length > 0 && (
                <div>
                  <div className="meta">DOMINANT</div>
                  <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>{dominantMoods.join(' · ')}</div>
                </div>
              )}
              {playlist.platform && (
                <div>
                  <div className="meta">SOURCE</div>
                  <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>{playlist.platform.toUpperCase()}</div>
                </div>
              )}
            </div>

            {/* Actions */}
            <div className="row" style={{ marginTop: 24, gap: 10, flexWrap: 'wrap' }}>
              <button className="btn" onClick={() => startPlay(0)} disabled={starting} style={{ height: 48, padding: '0 22px', opacity: starting ? 0.7 : 1 }}>
                <Icon.play /> {starting ? '加载中…' : '播放 · PLAY ALL'}
              </button>
              <button className="btn-pill" style={{ height: 48 }}>♡ 收藏</button>
              <button className="btn-pill" style={{ height: 48 }}><Icon.share /> 分享</button>
            </div>
          </div>
        </div>
      </div>

      {/* Track list */}
      <div style={{ padding: '40px 56px 80px' }}>
        <div className="between" style={{ marginBottom: 16 }}>
          <div className="meta">TRACK LIST · 曲目</div>
          <div className="meta" style={{ color: 'var(--ink-3)' }}>{tracks.length} 首</div>
        </div>

        {/* Header row */}
        <div className="row" style={{ padding: '10px 16px', color: 'var(--ink-3)', borderBottom: '1px solid var(--rule)', marginBottom: 4 }}>
          <div className="meta" style={{ width: 32 }}>#</div>
          <div className="meta" style={{ flex: 2.5 }}>TITLE · 标题</div>
          <div className="meta" style={{ flex: 1.5 }}>ALBUM · 专辑</div>
          <div className="meta" style={{ width: 100 }}>MOOD</div>
          <div className="meta" style={{ width: 40 }}></div>
          <div className="meta" style={{ width: 60, textAlign: 'right' }}>TIME</div>
        </div>

        {tracks.length === 0 ? (
          <div style={{ padding: '40px 16px', textAlign: 'center', fontFamily: 'var(--serif-cn)', fontSize: 15, color: 'var(--ink-3)' }}>
            暂无曲目
          </div>
        ) : (
          tracks.map((track, i) => (
            <TrackRow
              key={track.id ?? i}
              track={track}
              index={i}
              active={playingIndex === i}
              onPlay={(idx) => startPlay(idx)}
              onLikeToggle={() => {}}
            />
          ))
        )}
      </div>
    </div>
  );
}

// moodfm-frontend/src/views/library/Playlist.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { usePlayerStore } from '@/stores/player'
import MoodBlob from '@/components/common/MoodBlob.vue'
import { playlistApi } from '@/api/playlist'

const router = useRouter()
const route = useRoute()
const player = usePlayerStore()
const loading = ref(true)
const error = ref<string | null>(null)
const playlist = ref<any>(null)

interface TrackItem { t: string; a: string; al: string; m: string; mood: string; liked: boolean }

const tracks = ref<TrackItem[]>([])

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

const metaItems = computed(() => [
  { l: 'TRACKS',   v: String(playlist.value?.trackCount ?? tracks.value.length) },
  { l: 'DURATION', v: `${Math.round(tracks.value.length * 3.5)} MIN` },
  { l: 'UPDATED',  v: '每日同步' },
  { l: 'SOURCE',   v: playlist.value?.platform === 'netease' ? '网易云' : playlist.value?.platform === 'qqmusic' ? 'QQ 音乐' : '—' },
])

const activeIdx = ref(0)
const likedMap = ref<Record<number, boolean>>({})
const hovIdx = ref(-1)

onMounted(async () => {
  const id = route.params.id as string
  if (!id) { loading.value = false; return }
  try {
    const data = await playlistApi.getPlaylist(id)
    playlist.value = data
    tracks.value = (data.tracks ?? []).map(s => ({
      t: s.title,
      a: s.artist,
      al: s.album ?? '',
      m: formatDuration(s.duration),
      mood: 'CALM',
      liked: false,
    }))
    likedMap.value = Object.fromEntries(tracks.value.map((_, i) => [i, false]))
  } catch (e: any) {
    error.value = e?.message ?? '加载失败'
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);padding-bottom:80px;">
    <div style="position:sticky;top:0;z-index:5;background:var(--bg);padding:18px 56px;
                border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between;">
      <button class="btn-pill" @click="router.back()">← 返回</button>
      <div class="meta">PLAYLIST · 歌单详情</div>
      <button class="btn-pill">···</button>
    </div>

    <div style="position:relative;overflow:hidden;padding:56px 56px 48px;border-bottom:1px solid var(--rule);">
      <div class="mood-blob drift" style="width:800px;height:800px;right:-150px;top:-220px;opacity:.45;" />
      <div style="position:relative;z-index:2;display:grid;grid-template-columns:320px 1fr;gap:48px;align-items:end;">
        <div>
          <div style="position:relative;width:300px;height:300px;border-radius:18px;overflow:hidden;
                      box-shadow:0 24px 60px rgba(0,0,0,.18);">
            <MoodBlob :size="300" :drift="true" geometry="blob" />
            <div style="position:absolute;left:14px;bottom:12px;color:#fff;text-shadow:0 1px 4px rgba(0,0,0,.4);">
              <div class="mono" style="font-size:10px;letter-spacing:.2em;opacity:.9;">NIGHT FLOAT · 010</div>
            </div>
          </div>
        </div>
        <div>
          <div class="meta">CURATED FOR YOU · 为你编排</div>
          <h1 class="display" style="font-size:108px;margin:12px 0 0;line-height:.95;">Night <em>float</em>.</h1>
          <div class="display-cn" style="font-size:34px;margin-top:4px;color:var(--ink-2);">夜浮 · 给加完班的你</div>
          <p style="margin-top:16px;font-size:14px;line-height:1.7;color:var(--ink-2);max-width:520px;font-family:var(--serif-cn);">
            一份漂在凌晨水面上的 ambient 合集——人声极少、低频温和、不会打扰任何思绪。AI 根据你过去 30 天 23:00 后的收听偏好编排。
          </p>
          <div class="row" style="margin-top:20px;gap:24px;color:var(--ink-3);">
            <div v-for="m in metaItems" :key="m.l">
              <div class="meta">{{ m.l }}</div>
              <div class="mono" style="font-size:14px;color:var(--ink);margin-top:2px;">{{ m.v }}</div>
            </div>
          </div>
          <div class="row" style="margin-top:24px;gap:10px;flex-wrap:wrap;">
            <button class="btn" style="height:48px;padding:0 22px;" @click="player.play();router.push('/player')">▶ 播放 · PLAY ALL</button>
            <button class="btn-pill" style="height:48px;">♡ 收藏</button>
            <button class="btn-pill" style="height:48px;">↓ 下载</button>
            <button class="btn-pill" style="height:48px;">↗ 分享</button>
          </div>
        </div>
      </div>
    </div>

    <div style="padding:40px 56px;">
      <div class="between" style="margin-bottom:16px;">
        <div class="meta">TRACK LIST · 曲目</div>
        <div class="row" style="gap:8px;">
          <button class="btn-pill">排序 ↓</button>
          <button class="btn-pill">筛选</button>
        </div>
      </div>
      <div class="row" style="padding:10px 16px;color:var(--ink-3);border-bottom:1px solid var(--rule);">
        <div class="meta" style="width:32px;">#</div>
        <div class="meta" style="flex:2.5;">TITLE · 标题</div>
        <div class="meta" style="flex:1.5;">ALBUM · 专辑</div>
        <div class="meta" style="width:100px;">MOOD</div>
        <div style="width:40px;" />
        <div class="meta" style="width:60px;text-align:right;">TIME</div>
      </div>
      <div
        v-for="(t, i) in tracks"
        :key="i"
        class="row"
        :style="{
          padding: '12px 16px',
          borderRadius: '8px',
          cursor: 'pointer',
          background: i === activeIdx || i === hovIdx ? 'var(--bg-2)' : 'transparent',
          transition: 'background .1s',
        }"
        @mouseenter="hovIdx = i"
        @mouseleave="hovIdx = -1"
        @click="activeIdx = i; player.play()"
      >
        <div style="width:32px;font-family:var(--mono);font-size:13px;color:var(--ink-3);">
          {{ i === activeIdx ? '▸' : String(i + 1).padStart(2, '0') }}
        </div>
        <div style="flex:2.5;min-width:0;">
          <div style="font-family:var(--serif-en);font-style:italic;font-size:19px;">{{ t.t }}</div>
          <div class="meta" style="margin-top:2px;">{{ t.a }}</div>
        </div>
        <div style="flex:1.5;min-width:0;font-family:var(--serif-cn);font-size:13px;color:var(--ink-2);
                    white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{ t.al }}</div>
        <div style="width:100px;">
          <span class="meta" style="padding:3px 8px;border:1px solid var(--rule);border-radius:999px;color:var(--ink-2);">{{ t.mood }}</span>
        </div>
        <div style="width:40px;text-align:center;">
          <button
            @click.stop="likedMap[i] = !likedMap[i]"
            style="background:none;border:none;cursor:pointer;font-size:18px;line-height:1;"
            :style="{ color: likedMap[i] ? 'var(--mood-b)' : 'var(--ink-3)' }"
          >{{ likedMap[i] ? '♥' : '♡' }}</button>
        </div>
        <div class="mono" style="width:60px;text-align:right;font-size:12px;color:var(--ink-3);">{{ t.m }}</div>
      </div>
    </div>
  </div>
</template>
