// moodfm-frontend/src/views/player/components/QueueDrawer.vue
<template>
  <Transition name="fade">
    <div
      v-if="ui.queueDrawerOpen"
      class="queue-drawer-backdrop"
      @click="ui.toggleQueueDrawer()"
    >
      <div class="queue-drawer-panel" @click.stop>
        <div class="mono queue-drawer-title">
          UP NEXT · 接下来播放 · {{ player.queue.length }} 首
        </div>
        <div v-if="player.queue.length === 0" class="queue-drawer-empty">
          队列为空
        </div>
        <div
          v-for="(song, i) in player.queue.slice(0, 12)"
          :key="song.id ?? i"
          class="row queue-drawer-item"
        >
          <span class="mono queue-drawer-index">{{ String(i + 1).padStart(2,'0') }}</span>
          <div class="queue-drawer-song">
            <div class="queue-drawer-song-title">{{ song.title }}</div>
            <div class="meta queue-drawer-song-artist">{{ song.artist }}</div>
          </div>
          <span class="mono queue-drawer-duration">{{ formatTime(song.duration) }}</span>
        </div>
      </div>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { usePlayerStore } from '@/stores/player'
import { useUiStore } from '@/stores/ui'
import { formatTime } from '../utils/formatTime'

const player = usePlayerStore()
const ui = useUiStore()
</script>

<style scoped>
.queue-drawer-backdrop {
  position: fixed;
  inset: 0;
  z-index: 50;
  background: rgba(0,0,0,0.55);
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.queue-drawer-panel {
  background: var(--bg);
  border-radius: 20px 20px 0 0;
  padding: 24px 24px 48px;
  max-height: 65vh;
  overflow-y: auto;
}

.queue-drawer-title {
  font-size: 10px;
  letter-spacing: .2em;
  opacity: .5;
  text-align: center;
  margin-bottom: 20px;
}

.queue-drawer-empty {
  text-align: center;
  padding: 32px 0;
  font-family: var(--serif-cn);
  font-size: 15px;
  color: var(--ink-3);
}

.queue-drawer-item {
  gap: 14px;
  padding: 12px 0;
  border-bottom: 1px solid var(--rule);
  align-items: center;
}

.queue-drawer-index {
  font-size: 11px;
  color: var(--ink-3);
  width: 24px;
  flex-shrink: 0;
}

.queue-drawer-song {
  flex: 1;
  min-width: 0;
}

.queue-drawer-song-title {
  font-family: var(--serif-en);
  font-style: italic;
  font-size: 17px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.queue-drawer-song-artist {
  margin-top: 2px;
}

.queue-drawer-duration {
  font-size: 11px;
  color: var(--ink-3);
  flex-shrink: 0;
}

.fade-enter-active,
.fade-leave-active { transition: opacity 0.25s ease; }
.fade-enter-from,
.fade-leave-to     { opacity: 0; }
</style>

// moodfm-frontend/src/components/player/QueueDrawer.jsx
import { usePlayerStore } from '../../store/playerStore';

export function QueueDrawer({ open, onClose }) {
  const { queue, currentIndex } = usePlayerStore();
  const upcoming = queue.slice(currentIndex + 1, currentIndex + 21);

  if (!open) return null;

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, zIndex: 100,
        background: 'rgba(0,0,0,0.55)',
        display: 'flex', flexDirection: 'column', justifyContent: 'flex-end',
      }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          background: 'var(--bg)', borderRadius: '20px 20px 0 0',
          padding: '20px 20px 48px',
          maxHeight: '65vh', overflowY: 'auto',
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <div className="mono" style={{ fontSize: 11, letterSpacing: '.16em', opacity: 0.45 }}>
            UP NEXT · 接下来 {upcoming.length > 0 ? `· ${upcoming.length} 首` : ''}
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink)', opacity: 0.4, fontSize: 18, lineHeight: 1 }}>✕</button>
        </div>

        {upcoming.length === 0 ? (
          <div style={{ textAlign: 'center', paddingTop: 24, opacity: 0.35, fontFamily: 'var(--serif-cn)', fontSize: 14 }}>队列为空</div>
        ) : (
          upcoming.map((s, i) => (
            <div key={s.id ?? i} style={{
              display: 'flex', alignItems: 'center', gap: 14,
              padding: '10px 0', borderBottom: '1px solid var(--rule)',
            }}>
              <span className="mono" style={{ width: 24, textAlign: 'right', opacity: 0.35, fontSize: 12, flexShrink: 0 }}>
                {currentIndex + i + 2}
              </span>
              <div style={{ width: 40, height: 40, borderRadius: 6, background: 'var(--paper)', overflow: 'hidden', flexShrink: 0, border: '1px solid var(--rule)' }}>
                {s.coverUrl
                  ? <img src={s.coverUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                  : <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.15 }}>♪</div>
                }
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 14, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{s.title}</div>
                <div className="mono" style={{ fontSize: 11, opacity: 0.5, marginTop: 2 }}>{s.artist}</div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
