// moodfm-frontend/src/views/insights/Calendar.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import NavBar from '@/components/common/NavBar.vue'
import MiniPlayer from '@/components/common/MiniPlayer.vue'
import { insightsApi } from '@/api/insights'

const MOOD_PALETTE: Record<string, [string, string]> = {
  calm:       ['#e9f0e6', '#9bb1a4'],
  dusk:       ['#f3d7c6', '#d28a9a'],
  blue:       ['#cbd6e8', '#6b7c9a'],
  energy:     ['#f8c87b', '#d96343'],
  focus:      ['#cfe1d8', '#6f9a87'],
  melancholy: ['#cbd6e8', '#6b7c9a'],
  energetic:  ['#f8c87b', '#d96343'],
  focused:    ['#cfe1d8', '#6f9a87'],
  empty:      ['transparent', 'transparent'],
}

const now      = new Date()
const year     = ref(now.getFullYear())
const month    = ref(now.getMonth() + 1)
const todayDay = now.getDate()

interface DayCell { day: number; future: boolean; empty: boolean; mood: string; tracks: number; minutes: number; isToday: boolean }

const days     = ref<DayCell[]>([])
const selected = ref(todayDay)
const viewMode = ref<'mood'|'volume'>('mood')
const loading  = ref(true)
const topTracks = ref<{ t: string; a: string; m: string }[]>([])

const sel = computed(() => days.value[selected.value - 1])

const lead = computed(() => new Date(year.value, month.value - 1, 1).getDay())

const cells = computed(() => {
  const c: (DayCell | null)[] = [...Array(lead.value).fill(null), ...days.value]
  while (c.length % 7) c.push(null)
  return c
})

const MOOD_LABELS: Record<string, string> = {
  calm: '平静 · CALM', dusk: '温柔 · TENDER', blue: '忧郁 · MELANCHOLY',
  energy: '高能 · ENERGETIC', focus: '专注 · FOCUSED',
  melancholy: '忧郁 · MELANCHOLY', energetic: '高能 · ENERGETIC', focused: '专注 · FOCUSED',
}
const DAY_CN = ['日','一','二','三','四','五','六']

const legendMoods = [
  { k:'calm',   l:'平静' },
  { k:'dusk',   l:'温柔' },
  { k:'blue',   l:'忧郁' },
  { k:'energy', l:'高能' },
  { k:'focus',  l:'专注' },
]

function daysInMonth(y: number, m: number) {
  return new Date(y, m, 0).getDate()
}

function buildGrid(apiData: any[]): DayCell[] {
  const total = daysInMonth(year.value, month.value)
  const sameMonth = now.getFullYear() === year.value && now.getMonth() + 1 === month.value
  const map = new Map<number, any>(apiData.map(d => [new Date(d.date).getDate(), d]))
  return Array.from({ length: total }, (_, i) => {
    const d = i + 1
    const future = sameMonth ? d > todayDay : (
      year.value > now.getFullYear() ||
      (year.value === now.getFullYear() && month.value > now.getMonth() + 1)
    )
    const entry = map.get(d)
    const hasMood = !!entry?.hasMood
    return {
      day: d,
      future,
      empty: future || !hasMood,
      mood: entry?.mood ?? 'empty',
      tracks: entry?.songCount ?? 0,
      minutes: Math.round((entry?.songCount ?? 0) * 3.5),
      isToday: sameMonth && d === todayDay,
    }
  })
}

async function loadDayDetail(day: number) {
  const dateStr = `${year.value}-${String(month.value).padStart(2,'0')}-${String(day).padStart(2,'0')}`
  try {
    const detail = await insightsApi.getDayDetail(dateStr)
    topTracks.value = ((detail as any).songs ?? []).slice(0, 4).map((s: any) => ({
      t: s.title ?? s.name ?? '—',
      a: s.artist ?? '—',
      m: '—',
    }))
  } catch {
    topTracks.value = []
  }
}

async function selectDay(day: number) {
  selected.value = day
  await loadDayDetail(day)
}

function cellBg(cell: DayCell) {
  if (viewMode.value === 'mood') return MOOD_PALETTE[cell.mood]?.[0] ?? 'transparent'
  const intensity = Math.min(1, cell.minutes / 80)
  return cell.empty ? 'transparent' : `rgba(33,30,28,${0.15 + intensity * 0.7})`
}

function cellBorder(cell: DayCell, isSel: boolean) {
  if (isSel || cell.isToday) return '2px solid var(--ink)'
  if (viewMode.value === 'mood' && !cell.empty) return `1.5px solid ${MOOD_PALETTE[cell.mood]?.[1] ?? 'var(--rule)'}`
  return '1px solid var(--rule)'
}

onMounted(async () => {
  try {
    const apiData = await insightsApi.getCalendar(year.value, month.value)
    days.value = buildGrid(apiData as any[])
    if (days.value[todayDay - 1] && !days.value[todayDay - 1].empty) {
      await loadDayDetail(todayDay)
    }
  } catch {
    days.value = buildGrid([])
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);">
    <NavBar />

    <div style="position:sticky;top:62px;z-index:5;background:var(--bg);padding:22px 56px;
                border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between;">
      <RouterLink to="/insights" class="btn-pill" style="text-decoration:none;">← Home</RouterLink>
      <div class="meta">SECTION V · MOOD CALENDAR · 心情日历</div>
      <div class="row" style="gap:6px;">
        <button :class="['btn-pill', viewMode==='mood'?'active':'']" @click="viewMode='mood'">心情</button>
        <button :class="['btn-pill', viewMode==='volume'?'active':'']" @click="viewMode='volume'">时长</button>
      </div>
    </div>

    <div style="display:grid;grid-template-columns:1.4fr 1fr;">
      <div style="padding:40px 56px;border-right:1px solid var(--rule);">
        <div class="meta">YOUR EMOTIONAL MONTH · 2026</div>
        <h1 class="display" style="font-size:120px;margin:8px 0 0;line-height:.95;"><em>May.</em></h1>
        <div class="display-cn" style="font-size:28px;margin-top:4px;color:var(--ink-2);">五月 · 五月让人想睡。</div>

        <div class="row" style="margin-top:20px;gap:16px;flex-wrap:wrap;">
          <button class="btn-pill">‹</button>
          <div class="meta" style="min-width:120px;">MAY 2026 · 五月</div>
          <button class="btn-pill">›</button>
        </div>

        <div style="display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:22px;">
          <div
            v-for="d in ['SUN','MON','TUE','WED','THU','FRI','SAT']"
            :key="d"
            class="meta"
            style="text-align:center;color:var(--ink-3);"
          >{{ d }}</div>
        </div>

        <div style="display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:8px;">
          <template v-for="(cell,i) in cells" :key="i">
            <div v-if="!cell" style="aspect-ratio:1;min-height:56px;" />
            <button
              v-else
              :disabled="cell.future"
              :style="{
                aspectRatio:'1', minHeight:'56px', borderRadius:'6px',
                background: cellBg(cell),
                border: cellBorder(cell, cell.day===selected),
                color: cell.empty?'var(--ink-3)':'var(--ink)',
                cursor: cell.future?'default':'pointer',
                opacity: cell.future?0.35:1,
                padding:'6px', display:'flex', flexDirection:'column',
                justifyContent:'space-between', alignItems:'flex-start',
                fontFamily:'var(--mono)',
                transform: cell.day===selected ? 'scale(1.06)' : 'scale(1)',
                transition: 'transform .15s',
              }"
              @click="!cell.future && selectDay(cell.day)"
            >
              <span :style="{ fontSize:'14px', fontWeight: cell.isToday?700:500 }">{{ cell.day }}</span>
              <span v-if="!cell.empty" style="font-size:9px;opacity:.7;">{{ cell.tracks }}♪</span>
            </button>
          </template>
        </div>

        <div style="margin-top:28px;">
          <div class="meta" style="margin-bottom:10px;">LEGEND · {{ viewMode==='mood'?'按心情上色':'按收听时长' }}</div>
          <div v-if="viewMode==='mood'" class="row" style="gap:14px;flex-wrap:wrap;">
            <div v-for="m in legendMoods" :key="m.k" class="row" style="gap:8px;align-items:center;">
              <div :style="{ width:'14px',height:'14px',borderRadius:'4px',
                             background:MOOD_PALETTE[m.k][0],
                             border:`1.5px solid ${MOOD_PALETTE[m.k][1]}` }" />
              <span :style="{ fontFamily:'var(--serif-cn)',fontSize:'13px' }">{{ m.l }}</span>
            </div>
          </div>
          <div v-else class="row" style="gap:6px;align-items:center;">
            <span class="meta">LESS</span>
            <div
              v-for="o in [0.15,0.35,0.55,0.75,0.95]"
              :key="o"
              :style="{ width:'18px',height:'18px',borderRadius:'4px',background:`rgba(33,30,28,${o})` }"
            />
            <span class="meta">MORE</span>
          </div>
        </div>
      </div>

      <div style="padding:40px 40px;background:var(--bg-2);min-height:calc(100vh - 73px);">
        <template v-if="sel && !sel.empty">
          <div class="meta">SELECTED · 选中</div>
          <div class="row" style="margin-top:10px;align-items:baseline;gap:14px;">
            <h2 class="display" style="font-size:80px;margin:0;">{{ sel.day }}</h2>
            <div>
              <div :style="{ fontFamily:'var(--serif-cn)',fontSize:'18px' }">五月 · 周{{ DAY_CN[(sel.day+4)%7] }}</div>
              <div class="meta" style="margin-top:4px;">MAY {{ String(sel.day).padStart(2,'0') }} · 2026</div>
            </div>
          </div>

          <div style="margin-top:20px;padding:22px;background:var(--paper);border-radius:16px;border:1px solid var(--rule);">
            <div class="row" style="gap:16px;align-items:center;">
              <div :style="{
                width:'76px',height:'76px',borderRadius:'50%',flexShrink:0,
                background:`radial-gradient(circle at 30% 30%,${MOOD_PALETTE[sel.mood][0]},${MOOD_PALETTE[sel.mood][1]})`,
                boxShadow:'0 6px 24px rgba(0,0,0,.06)',
              }" />
              <div>
                <div class="meta">DOMINANT MOOD</div>
                <div :style="{ fontFamily:'var(--serif-en)',fontStyle:'italic',fontSize:'28px',marginTop:'4px' }">
                  {{ MOOD_LABELS[sel.mood]?.split(' · ')[1] }}
                </div>
                <div :style="{ fontFamily:'var(--serif-cn)',fontSize:'16px',color:'var(--ink-2)' }">
                  {{ MOOD_LABELS[sel.mood]?.split(' · ')[0] }}
                </div>
              </div>
            </div>
            <div class="row" style="margin-top:18px;padding-top:16px;border-top:1px dashed var(--rule);gap:28px;">
              <div><div class="meta">TRACKS</div><div class="mono" style="font-size:18px;margin-top:4px;">{{ sel.tracks }}</div></div>
              <div><div class="meta">MINUTES</div><div class="mono" style="font-size:18px;margin-top:4px;">{{ sel.minutes }}</div></div>
              <div><div class="meta">SESSIONS</div><div class="mono" style="font-size:18px;margin-top:4px;">{{ Math.max(1,Math.floor(sel.tracks/4)) }}</div></div>
            </div>
          </div>

          <div style="margin-top:24px;">
            <div class="meta" style="margin-bottom:12px;">TOP TRACKS · 当天最常听</div>
            <div
              v-for="(t,i) in topTracks"
              :key="t.t"
              class="row"
              :style="{ gap:'12px',padding:'10px 0',borderBottom:i<topTracks.length-1?'1px solid var(--rule)':'none' }"
            >
              <span class="mono" style="color:var(--ink-3);width:22px;flex-shrink:0;">0{{ i+1 }}</span>
              <div style="flex:1;min-width:0;">
                <div :style="{ fontFamily:'var(--serif-en)',fontStyle:'italic',fontSize:'18px' }">{{ t.t }}</div>
                <div class="meta" style="margin-top:2px;">{{ t.a }}</div>
              </div>
              <div class="mono" style="color:var(--ink-3);flex-shrink:0;">{{ t.m }}</div>
            </div>
          </div>
          <button class="btn" style="margin-top:24px;width:100%;height:46px;">重听这一天 ▶</button>
        </template>
        <div v-else class="meta" style="text-align:center;padding:60px;color:var(--ink-3);">
          · NO DATA · 这一天没有听
        </div>
      </div>
    </div>

    <MiniPlayer />
  </div>
</template>

// moodfm-frontend/src/screens/Calendar.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon, Logo } from '../components/atoms';
import { insightsApi } from '../api/insights';

// ─── Constants ────────────────────────────────────────────────

const MOOD_PALETTE = {
  calm:   ['#e9f0e6', '#9bb1a4'],
  dusk:   ['#f3d7c6', '#d28a9a'],
  blue:   ['#cbd6e8', '#6b7c9a'],
  energy: ['#f8c87b', '#d96343'],
  focus:  ['#cfe1d8', '#6f9a87'],
  empty:  ['transparent', 'transparent'],
};
const MOOD_LABELS = { calm:'平静', dusk:'温柔', blue:'忧郁', energy:'高能', focus:'专注' };
const WEEKDAYS = ['SUN','MON','TUE','WED','THU','FRI','SAT'];
const CN_WEEKDAYS = ['日','一','二','三','四','五','六'];

// ─── Day Cell ────────────────────────────────────────────────

function DayCell({ cell, viewMode, isSelected, onClick, today }) {
  if (!cell) return <div style={{ aspectRatio: '1', minHeight: 56 }} />;

  const [bg, border] = MOOD_PALETTE[cell.mood] || ['transparent','transparent'];
  const intensity = Math.min(1, (cell.minutes ?? 0) / 80);
  const isFuture = cell.future;
  const isEmpty  = cell.empty || isFuture;

  const showBg = viewMode === 'mood'
    ? (isEmpty ? 'transparent' : bg)
    : (isEmpty ? 'transparent' : `rgba(26,23,20,${0.1 + intensity * 0.75})`);
  const isToday = cell.day === today;
  const borderStyle = isToday || isSelected
    ? '2px solid var(--ink)'
    : viewMode === 'mood' && !isEmpty
    ? `1.5px solid ${border}`
    : '1px solid var(--rule)';
  const txtColor = viewMode === 'volume' && intensity > 0.6 ? 'var(--bg)' : 'var(--ink)';

  return (
    <button
      onClick={() => !isFuture && !isEmpty && onClick(cell.day)}
      disabled={isFuture}
      style={{
        aspectRatio: '1', minHeight: 56,
        borderRadius: 6,
        background: showBg,
        border: borderStyle,
        color: isEmpty ? 'var(--ink-3)' : txtColor,
        cursor: isFuture ? 'default' : isEmpty ? 'default' : 'pointer',
        opacity: isFuture ? 0.3 : 1,
        padding: 6,
        display: 'flex', flexDirection: 'column', justifyContent: 'space-between', alignItems: 'flex-start',
        fontFamily: 'var(--mono)',
        transition: 'transform .12s',
        transform: isSelected ? 'scale(1.06)' : 'scale(1)',
      }}
    >
      <span style={{ fontSize: 13, fontWeight: isToday ? 700 : 400 }}>{cell.day}</span>
      {!isEmpty && <span style={{ fontSize: 9, opacity: 0.65 }}>{cell.tracks ?? 0}♪</span>}
    </button>
  );
}

// ─── Day Detail Panel ────────────────────────────────────────

function DayDetail({ calCell, detail, loading, year, month, onReplay }) {
  const cell = detail ?? calCell;
  if (!cell) {
    return (
      <div className="meta" style={{ textAlign: 'center', padding: 60, color: 'var(--ink-3)' }}>
        · NO DATA · 这一天没有收听记录
      </div>
    );
  }

  const [moodBg, moodBorder] = MOOD_PALETTE[cell.mood] || ['var(--bg-2)', 'var(--rule)'];
  const moodLabel = MOOD_LABELS[cell.mood] ?? cell.mood ?? '—';
  const moodEn = (cell.mood ?? '').toUpperCase();
  const weekday = CN_WEEKDAYS[new Date(year, month - 1, cell.day).getDay()];
  const topTracks = detail?.topTracks ?? [];

  return (
    <div>
      <div className="meta">SELECTED · 选中</div>
      <div className="row" style={{ marginTop: 10, alignItems: 'baseline', gap: 14 }}>
        <h2 className="display" style={{ fontSize: 80, margin: 0 }}>{String(cell.day).padStart(2,'0')}</h2>
        <div>
          <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 18 }}>
            {new Date(year, month - 1).toLocaleString('zh-CN', { month: 'long' })} · 周{weekday}
          </div>
          <div className="meta" style={{ marginTop: 4 }}>
            {new Date(year, month - 1).toLocaleString('en-US', { month: 'short' }).toUpperCase()} {String(cell.day).padStart(2,'0')} · {year}
          </div>
        </div>
      </div>

      {/* Mood card */}
      <div style={{ marginTop: 20, padding: 22, background: 'var(--paper)', borderRadius: 16, border: '1px solid var(--rule)' }}>
        <div className="row" style={{ gap: 16 }}>
          <div style={{
            width: 76, height: 76, borderRadius: '50%', flexShrink: 0,
            background: `radial-gradient(circle at 30% 30%, ${moodBg}, ${moodBorder})`,
            boxShadow: '0 6px 24px rgba(0,0,0,0.06)',
          }} />
          <div>
            <div className="meta">DOMINANT MOOD</div>
            <div style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 28, marginTop: 4 }}>{moodEn}</div>
            <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 16, color: 'var(--ink-2)' }}>{moodLabel}</div>
          </div>
        </div>
        <div className="row" style={{ marginTop: 18, paddingTop: 16, borderTop: '1px dashed var(--rule)', gap: 28 }}>
          <div><div className="meta">TRACKS</div><div className="mono" style={{ fontSize: 18, marginTop: 4 }}>{cell.tracks ?? 0}</div></div>
          <div><div className="meta">MINUTES</div><div className="mono" style={{ fontSize: 18, marginTop: 4 }}>{cell.minutes ?? 0}</div></div>
          <div><div className="meta">SESSIONS</div><div className="mono" style={{ fontSize: 18, marginTop: 4 }}>{cell.sessions ?? Math.max(1, Math.floor((cell.tracks ?? 0) / 4))}</div></div>
        </div>
      </div>

      {/* Top tracks */}
      {loading && (
        <div className="meta" style={{ marginTop: 20, color: 'var(--ink-3)' }}>加载曲目中…</div>
      )}
      {topTracks.length > 0 && (
        <div style={{ marginTop: 24 }}>
          <div className="meta" style={{ marginBottom: 12 }}>TOP TRACKS · 当天最常听</div>
          {topTracks.map((t, i) => (
            <div key={i} className="row" style={{ gap: 12, padding: '10px 0', borderBottom: i < topTracks.length - 1 ? '1px solid var(--rule)' : 'none' }}>
              <span className="mono" style={{ color: 'var(--ink-3)', width: 22, flexShrink: 0 }}>{String(i + 1).padStart(2, '0')}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 17, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{t.title}</div>
                <div className="meta" style={{ marginTop: 2 }}>{t.artist}</div>
              </div>
              <div className="mono" style={{ color: 'var(--ink-3)', flexShrink: 0 }}>{t.duration ?? t.durationFormatted ?? ''}</div>
            </div>
          ))}
        </div>
      )}

      <button className="btn" style={{ marginTop: 24, width: '100%', height: 46 }} onClick={onReplay}>
        重听这一天 <Icon.play />
      </button>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────

export default function Calendar() {
  const navigate = useNavigate();
  const now = new Date();

  const [year, setYear]   = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [viewMode, setViewMode] = useState('mood');
  const [calData, setCalData]   = useState(null);
  const [loading, setLoading]   = useState(true);
  const [error, setError]       = useState('');

  const [selectedDay, setSelectedDay]       = useState(now.getDate());
  const [dayDetail, setDayDetail]           = useState(null);
  const [detailLoading, setDetailLoading]   = useState(false);

  // Fetch month data
  useEffect(() => {
    setLoading(true);
    setError('');
    setCalData(null);
    insightsApi.getCalendar(year, month)
      .then(res => {
        if (res.code === 200) setCalData(res.data);
        else setError(res.message || '加载失败');
      })
      .catch(() => setError('网络错误，请刷新'))
      .finally(() => setLoading(false));
  }, [year, month]);

  // Fetch day detail when selection changes
  useEffect(() => {
    if (!selectedDay) return;
    const date = `${year}-${String(month).padStart(2,'0')}-${String(selectedDay).padStart(2,'0')}`;
    setDetailLoading(true);
    setDayDetail(null);
    insightsApi.getDayDetail(date)
      .then(res => { if (res.code === 200) setDayDetail(res.data); })
      .catch(() => {})
      .finally(() => setDetailLoading(false));
  }, [selectedDay, year, month]);

  const navigate_month = (delta) => {
    let m = month + delta, y = year;
    if (m > 12) { m = 1;  y++; }
    if (m < 1)  { m = 12; y--; }
    setMonth(m); setYear(y); setSelectedDay(null); setDayDetail(null);
  };

  // Build grid cells
  const days = calData?.days ?? [];
  const firstDOW = calData?.firstDayOfWeek ?? new Date(year, month - 1, 1).getDay();
  const daysInMonth = calData?.daysInMonth ?? new Date(year, month, 0).getDate();
  const today = (year === now.getFullYear() && month === now.getMonth() + 1) ? now.getDate() : -1;

  const dayMap = {};
  days.forEach(d => { dayMap[d.day] = d; });

  const cells = [
    ...Array(firstDOW).fill(null),
    ...Array.from({ length: daysInMonth }, (_, i) => {
      const d = i + 1;
      return dayMap[d] ?? {
        day: d,
        mood: 'empty',
        tracks: 0,
        minutes: 0,
        future: new Date(year, month - 1, d) > now,
        empty: true,
      };
    }),
  ];
  while (cells.length % 7) cells.push(null);

  const monthName   = new Date(year, month - 1).toLocaleString('en-US', { month: 'long' });
  const monthNameCn = new Date(year, month - 1).toLocaleString('zh-CN', { month: 'long' });
  const selectedCalCell = selectedDay ? (dayMap[selectedDay] ?? null) : null;

  return (
    <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh' }}>
      {/* Top bar */}
      <div style={{ position: 'sticky', top: 0, zIndex: 5, background: 'var(--bg)', padding: '22px 56px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div className="row" style={{ gap: 10 }}>
          <button onClick={() => navigate('/insights')} className="btn-pill"><Icon.chevL /> Insights</button>
          <div className="meta" style={{ marginLeft: 8 }}>SECTION V · MOOD CALENDAR · 心情日历</div>
        </div>
        <div className="row" style={{ gap: 6 }}>
          <button onClick={() => setViewMode('mood')}   className={`btn-pill${viewMode === 'mood'   ? ' active' : ''}`}>心情</button>
          <button onClick={() => setViewMode('volume')} className={`btn-pill${viewMode === 'volume' ? ' active' : ''}`}>时长</button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr' }}>
        {/* LEFT: calendar */}
        <div style={{ padding: '40px 56px', borderRight: '1px solid var(--rule)' }}>
          <div className="meta">YOUR EMOTIONAL MONTH · {year}</div>
          <h1 className="display" style={{ fontSize: 120, margin: '8px 0 0', lineHeight: 0.95 }}>
            <em>{monthName}.</em>
          </h1>
          <div className="display-cn" style={{ fontSize: 26, marginTop: 4, color: 'var(--ink-2)' }}>
            {monthNameCn}
          </div>

          {/* Month nav */}
          <div className="row" style={{ marginTop: 20, gap: 12 }}>
            <button className="btn-pill" onClick={() => navigate_month(-1)}><Icon.chevL /></button>
            <div className="meta" style={{ minWidth: 160 }}>
              {monthName.toUpperCase()} {year} · {monthNameCn}
            </div>
            <button className="btn-pill" onClick={() => navigate_month(1)}>›</button>
          </div>

          {error && <div style={{ margin: '16px 0', fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--mood-b)' }}>{error}</div>}

          {/* Weekday header */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 8, marginTop: 22 }}>
            {WEEKDAYS.map(d => <div key={d} className="meta" style={{ textAlign: 'center', color: 'var(--ink-3)' }}>{d}</div>)}
          </div>

          {/* Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 8, marginTop: 8 }}>
            {loading
              ? Array(35).fill(null).map((_, i) => (
                <div key={i} style={{ aspectRatio: '1', minHeight: 56, borderRadius: 6, background: 'var(--rule)', opacity: 0.4 }} />
              ))
              : cells.map((c, i) => (
                <DayCell key={i} cell={c} viewMode={viewMode}
                  isSelected={c?.day === selectedDay}
                  today={today}
                  onClick={setSelectedDay} />
              ))
            }
          </div>

          {/* Legend */}
          <div style={{ marginTop: 28 }}>
            <div className="meta" style={{ marginBottom: 10 }}>
              LEGEND · {viewMode === 'mood' ? '按心情上色' : '按收听时长'}
            </div>
            {viewMode === 'mood' ? (
              <div className="row" style={{ gap: 14, flexWrap: 'wrap' }}>
                {Object.entries(MOOD_LABELS).map(([k, l]) => (
                  <div key={k} className="row" style={{ gap: 8 }}>
                    <div style={{ width: 14, height: 14, borderRadius: 4, background: MOOD_PALETTE[k][0], border: `1.5px solid ${MOOD_PALETTE[k][1]}` }} />
                    <span style={{ fontFamily: 'var(--serif-cn)', fontSize: 13 }}>{l}</span>
                  </div>
                ))}
              </div>
            ) : (
              <div className="row" style={{ gap: 6 }}>
                <span className="meta">LESS</span>
                {[0.15, 0.35, 0.55, 0.75, 0.95].map((o, i) => (
                  <div key={i} style={{ width: 18, height: 18, borderRadius: 4, background: `rgba(26,23,20,${o})` }} />
                ))}
                <span className="meta">MORE</span>
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: day detail */}
        <div style={{ padding: '40px 40px', background: 'var(--bg-2)', minHeight: 'calc(100vh - 73px)' }}>
          {selectedDay
            ? <DayDetail
                calCell={selectedCalCell}
                detail={dayDetail}
                loading={detailLoading}
                year={year}
                month={month}
                onReplay={() => navigate('/home')}
              />
            : <div className="meta" style={{ textAlign: 'center', padding: 60, color: 'var(--ink-3)' }}>
                · 点击左侧日期查看详情
              </div>
          }
        </div>
      </div>
    </div>
  );
}
