// moodfm-frontend/src/views/insights/Insights.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { RouterLink } from 'vue-router'
import MiniPlayer from '@/components/common/MiniPlayer.vue'
import MoodBlob from '@/components/common/MoodBlob.vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { LineChart, RadarChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { insightsApi } from '@/api/insights'
import html2canvas from 'html2canvas'

use([LineChart, RadarChart, GridComponent, TooltipComponent, LegendComponent, CanvasRenderer])

const period = ref('7天')
const loading = ref(true)
const error = ref<string | null>(null)
const contentRef = ref<HTMLElement | null>(null)

async function handleShare() {
  const el = contentRef.value
  if (!el) return
  try {
    const canvas = await html2canvas(el, {
      backgroundColor: '#f4efe6',
      scale: 2,
      useCORS: true,
    })
    const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png'))
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `moodfm-insights-${period.value}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (e) {
    console.error('Share image generation failed:', e)
  }
}

// Reactive data — populated from API; fallback values shown until loaded
const statCards = ref([
  { en: 'TOTAL · LISTENING', value: '—', cn: '本周听歌时长', sub: '—' },
  { en: 'TOP · GENRE',       value: '—', cn: '最常听的流派', sub: '—' },
  { en: 'AI · ACCURACY',     value: '—', cn: 'AI 推荐准确率', sub: '红心 ÷ 跳过' },
  { en: 'MOOD · KEY',        value: '—', cn: '心情主旋律',   sub: '—' },
])

const artists = ref<Array<{ n: string; en: string; t: string; p: number }>>([])

// ── Dynamic week / date labels ────────────────────────────────────
function getISOWeek(d: Date): number {
  const tmp = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()))
  tmp.setUTCDate(tmp.getUTCDate() + 4 - (tmp.getUTCDay() || 7))
  const yearStart = new Date(Date.UTC(tmp.getUTCFullYear(), 0, 1))
  return Math.ceil(((tmp.getTime() - yearStart.getTime()) / 86400000 + 1) / 7)
}
function computeDateRange(d: number): string {
  const end = new Date()
  const start = new Date(); start.setDate(end.getDate() - d + 1)
  const fmt = (dt: Date) => `${dt.getMonth() + 1}/${String(dt.getDate()).padStart(2, '0')}`
  return `${fmt(start)} → ${fmt(end)}`
}
const now = new Date()
const headerWeekLabel = ref(`WEEK ${getISOWeek(now)} / ${now.getFullYear()}`)
const headerDateRange = ref(computeDateRange(7))

const headline = ref('tender')
const headlineAlt = ref('awake')
const headlineCn = ref('温柔的清醒')
const essayBody = ref('')
const weeklyReportId = ref<number | null>(null)
const previousReports = ref<Array<{ id: number; week: number; year: number; title: string; mood: string }>>([])

// Chart data refs — initialized empty, filled by API
const trendDates = ref<string[]>([])
const trendMood  = ref<number[]>([])
const trendSong  = ref<number[]>([])
const genreValues = ref<number[]>([0, 0, 0, 0, 0, 0, 0, 0])

const RADAR_AXES = ['Ambient 环境', 'Classical 古典', 'Folk 民谣', 'Indie 独立', 'Electronic 电子', 'Jazz 爵士', 'Pop 流行', 'Rock 摇滚']
const GENRE_KEY: Record<string, string> = {
  ambient: 'Ambient 环境', classical: 'Classical 古典', folk: 'Folk 民谣',
  indie: 'Indie 独立', electronic: 'Electronic 电子', jazz: 'Jazz 爵士',
  pop: 'Pop 流行', rock: 'Rock 摇滚',
}

const moodLineOption = computed(() => ({
  grid: { left: 40, right: 24, top: 16, bottom: 28 },
  tooltip: {
    trigger: 'axis',
    backgroundColor: '#f4efe6',
    borderColor: '#d9d3c8',
    textStyle: { color: '#1a1714', fontFamily: 'var(--serif-cn)', fontSize: 13 },
  },
  xAxis: {
    type: 'category',
    data: trendDates.value,
    axisLine: { lineStyle: { color: '#d9d3c8' } },
    axisLabel: { color: '#8a8276', fontFamily: 'var(--mono)', fontSize: 10 },
    axisTick: { show: false },
    boundaryGap: false,
  },
  yAxis: {
    type: 'value',
    min: 0,
    max: 10,
    splitLine: { lineStyle: { color: '#d9d3c8', type: 'dashed' } },
    axisLabel: { color: '#8a8276', fontFamily: 'var(--mono)', fontSize: 10 },
  },
  series: [
    {
      name: '用户心情',
      type: 'line',
      data: trendMood.value,
      smooth: true,
      symbol: 'circle',
      symbolSize: 5,
      lineStyle: { color: '#e85a8a', width: 2 },
      itemStyle: { color: '#e85a8a' },
      areaStyle: {
        color: {
          type: 'linear', x: 0, y: 0, x2: 0, y2: 1,
          colorStops: [{ offset: 0, color: 'rgba(232,90,138,0.18)' }, { offset: 1, color: 'rgba(232,90,138,0)' }],
        },
      },
    },
    {
      name: '听歌情绪',
      type: 'line',
      data: trendSong.value,
      smooth: true,
      symbol: 'none',
      lineStyle: { color: '#6e5cd9', width: 1.5, type: 'dashed' },
    },
  ],
}))

const radarOption = computed(() => ({
  tooltip: {
    backgroundColor: '#f4efe6',
    borderColor: '#d9d3c8',
    textStyle: { color: '#1a1714', fontFamily: 'var(--serif-cn)', fontSize: 13 },
  },
  radar: {
    indicator: RADAR_AXES.map(name => ({ name, max: 100 })),
    radius: '62%',
    splitLine: { lineStyle: { color: '#d9d3c8' } },
    axisLine: { lineStyle: { color: '#d9d3c8' } },
    axisName: { color: '#4a443c', fontFamily: 'var(--serif-cn)', fontSize: 11 },
    splitArea: { show: false },
  },
  series: [{
    type: 'radar',
    data: [{ value: genreValues.value, name: '流派分布' }],
    lineStyle: { color: '#e85a8a', width: 1.5 },
    areaStyle: {
      color: {
        type: 'radial', x: 0.5, y: 0.5, r: 0.5,
        colorStops: [{ offset: 0, color: 'rgba(255,138,91,0.55)' }, { offset: 1, color: 'rgba(110,92,217,0.25)' }],
      },
    },
    symbol: 'none',
  }],
}))

const days = computed(() => period.value === '7天' ? 7 : period.value === '30天' ? 30 : 90)

async function fetchInsights() {
  loading.value = true
  try {
    const d = days.value
    const [trend, radar, topItems, summary] = await Promise.all([
      insightsApi.getMoodTrend(d).catch(() => null as any),
      insightsApi.getGenreRadar(d).catch(() => [] as any[]),
      insightsApi.getTopItems(d).catch(() => null as any),
      insightsApi.getSummary(d).catch(() => null as any),
    ])

    // MoodTrendVO: { labels, userMood, songMood } — values are 0-1, scale to 0-10 for chart
    if (trend?.labels?.length) {
      trendDates.value = trend.labels
      trendMood.value = trend.userMood.map((v: number) => Math.round(v * 100) / 10)
      trendSong.value = trend.songMood.map((v: number) => Math.round(v * 100) / 10)
    }

    // GenreRadarItemVO[]: { genre, value(0-1) }
    if (radar.length > 0) {
      const map: Record<string, number> = {}
      for (const r of radar) {
        const key = GENRE_KEY[(r.genre as string).toLowerCase()] ?? r.genre
        map[key] = Math.round(r.value * 100)
      }
      genreValues.value = RADAR_AXES.map(a => map[a] ?? 0)
    }

    // TopItemsVO: { artists: [{ name, tag, totalTime, proportion }] }
    if (topItems?.artists?.length) {
      artists.value = topItems.artists.slice(0, 5).map((a: any) => ({
        n: a.name,
        en: a.tag || 'ARTIST',
        t: a.totalTime || '—',
        p: a.proportion ?? 0,
      }))
    }

    // InsightsSummaryVO: { headline, headlineAlt, headlineCn, stats, aiSummary, previousReports, essayBody }
    if (summary) {
      headline.value = summary.headline || 'tender'
      headlineAlt.value = summary.headlineAlt || 'awake'
      headlineCn.value = summary.headlineCn || '温柔的清醒'
      essayBody.value = summary.essayBody || ''
      weeklyReportId.value = summary.weeklyReportId ?? null
      previousReports.value = summary.previousReports || []

      const s = summary.stats
      if (s) {
        statCards.value[0].value = s.totalListeningTime || '—'
        statCards.value[0].sub = s.weekLabel || '—'
        statCards.value[1].value = s.topGenre || '—'
        statCards.value[1].sub = s.topGenreRatio ? `${s.topGenreRatio} 占比` : '—'
        statCards.value[2].value = s.aiAccuracy || '—'
        statCards.value[3].value = s.moodKey || '—'
        statCards.value[3].sub = s.moodSub || '—'
        if (s.weekRange) headerDateRange.value = s.weekRange.replace(' — ', ' → ')
      }
    }
  } catch {
  } finally {
    loading.value = false
  }
}

watch(period, () => {
  headerDateRange.value = computeDateRange(days.value)
  fetchInsights()
})

onMounted(() => { fetchInsights() })
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);position:relative;padding-bottom:100px;">
    <div class="mood-blob drift" style="width:680px;height:680px;left:-180px;top:-200px;opacity:.35;" />


    <div style="position:sticky;top:62px;z-index:5;background:var(--bg);padding:22px 56px;
                border-bottom:1px solid var(--rule);display:flex;justify-content:space-between;align-items:center;">
      <div class="row" style="gap:10px;">
        <RouterLink to="/home" class="btn-pill" style="text-decoration:none;">← Home</RouterLink>
        <div class="meta" style="margin-left:8px;">SECTION IV · INSIGHTS</div>
      </div>
      <div class="row" style="gap:6px;">
        <button
          v-for="p in ['7天','30天','90天']"
          :key="p"
          :class="['btn-pill', period===p ? 'active' : '']"
          @click="period=p"
        >{{ p }}</button>
      </div>
    </div>

    <div ref="contentRef" style="padding:40px 56px;">
      <div class="meta">YOUR EMOTIONAL ATLAS · 个人情绪图鉴 · {{ headerWeekLabel }}</div>
      <h1 class="display" style="font-size:144px;margin:12px 0 0;">You felt</h1>
      <h1 class="display" style="font-size:144px;margin:0;color:var(--ink-3);">
        <em :style="{ background:'linear-gradient(120deg,var(--mood-a),var(--mood-b),var(--mood-c))',WebkitBackgroundClip:'text',color:'transparent' }">{{ headline }}</em>
        <span style="color:var(--ink);"> &amp; </span>
        <em :style="{ background:'linear-gradient(120deg,var(--mood-c),var(--mood-d))',WebkitBackgroundClip:'text',color:'transparent' }">{{ headlineAlt }}</em>.
      </h1>
      <div class="display-cn" style="font-size:32px;margin-top:16px;color:var(--ink-2);">
        这一周，你的心情主旋律是<span style="color:var(--ink);">「{{ headlineCn }}」</span>。
      </div>

      <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:1px;margin-top:40px;
                  background:var(--rule);border:1px solid var(--rule);">
        <div v-for="s in statCards" :key="s.en" style="background:var(--bg);padding:24px;">
          <div class="meta">{{ s.en }}</div>
          <div class="display" style="font-size:60px;margin-top:8px;">{{ s.value }}</div>
          <div :style="{ fontFamily:'var(--serif-cn)',fontSize:'14px',color:'var(--ink-2)',marginTop:'4px' }">{{ s.cn }}</div>
          <div class="meta" style="margin-top:6px;color:var(--ink-3);">{{ s.sub }}</div>
        </div>
      </div>

      <div style="margin-top:56px;">
        <div class="between">
          <div>
            <div class="meta">FIG. 01 · MOOD CURVE</div>
            <div class="display-cn" style="font-size:30px;margin-top:4px;">心情曲线 vs 听歌情绪</div>
          </div>
          <div class="meta">{{ headerDateRange }}</div>
        </div>
        <div style="margin-top:20px;height:280px;border:1px solid var(--rule);border-radius:18px;
                    padding:24px 24px 8px;background:var(--paper);">
          <VChart :option="moodLineOption" autoresize style="width:100%;height:100%;" />
        </div>
        <div class="row" style="gap:18px;margin-top:12px;font-family:var(--serif-cn);font-size:13px;color:var(--ink-2);">
          <div class="row" style="gap:6px;align-items:center;">
            <span style="width:18px;height:2px;background:var(--mood-b);display:inline-block;" />
            用户心情
          </div>
          <div class="row" style="gap:6px;align-items:center;">
            <span style="width:18px;height:0;border-top:2px dashed var(--mood-c);display:inline-block;" />
            听歌情绪
          </div>
        </div>
      </div>

      <div style="margin-top:56px;display:grid;grid-template-columns:1fr 1fr;gap:48px;">
        <div>
          <div class="meta">FIG. 02 · GENRE</div>
          <div class="display-cn" style="font-size:30px;margin-top:4px;">流派分布</div>
          <div style="margin-top:20px;height:360px;">
            <VChart :option="radarOption" autoresize style="width:100%;height:100%;" />
          </div>
        </div>
        <div>
          <div class="meta">FIG. 03 · TOP ARTISTS</div>
          <div class="display-cn" style="font-size:30px;margin-top:4px;">本周 TOP 艺人</div>
          <div style="margin-top:20px;">
            <div v-if="artists.length === 0 && !loading"
              style="padding:32px 0;text-align:center;font-family:var(--serif-cn);font-size:14px;color:var(--ink-3);">
              暂无数据 · 开始听歌后将自动更新
            </div>
            <div v-for="(a,i) in artists" :key="a.n" style="padding:14px 0;border-bottom:1px solid var(--rule);">
              <div class="between">
                <div class="row" style="gap:12px;">
                  <div class="display" style="font-size:28px;color:var(--ink-3);width:32px;">0{{ i+1 }}</div>
                  <div>
                    <div :style="{ fontFamily:'var(--serif-cn)',fontSize:'17px',fontWeight:500 }">{{ a.n }}</div>
                    <div class="meta" style="margin-top:2px;">{{ a.en }}</div>
                  </div>
                </div>
                <div class="meta" style="color:var(--ink-2);">{{ a.t }}</div>
              </div>
              <div style="margin-top:10px;height:2px;background:var(--rule);position:relative;">
                <div :style="{ position:'absolute',left:0,top:0,bottom:0,width:(a.p*100)+'%',
                               background:'linear-gradient(90deg,var(--mood-a),var(--mood-c))' }" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div style="margin-top:56px;position:relative;overflow:hidden;border-radius:24px;padding:40px;color:#fff;">
        <div style="position:absolute;inset:0;background:radial-gradient(circle at 15% 20%,var(--mood-a) 0%,transparent 55%),
                    radial-gradient(circle at 85% 30%,var(--mood-b) 0%,transparent 55%),
                    radial-gradient(circle at 70% 90%,var(--mood-c) 0%,transparent 60%);background-color:var(--mood-d);" />
        <div style="position:relative;">
          <div class="mono" style="font-size:10px;letter-spacing:.2em;opacity:.85;">AI · WEEKLY ESSAY · 周报节选</div>
          <h2 class="display" style="font-size:60px;margin:12px 0 16px;text-shadow:0 2px 30px rgba(0,0,0,.2);">
            "{{ headline }}, but never {{ headlineAlt }}."
          </h2>
          <p v-if="essayBody" :style="{ fontFamily:'var(--serif-cn)',fontSize:'18px',lineHeight:1.7,maxWidth:'720px' }">
            {{ essayBody }}
          </p>
          <p v-else :style="{ fontFamily:'var(--serif-cn)',fontSize:'18px',lineHeight:1.7,maxWidth:'720px' }">
            继续使用后，AI 将为你生成专属周报。
          </p>
          <div class="row" style="margin-top:24px;gap:10px;">
            <RouterLink to="/insights/weekly" class="btn" style="background:#fff;color:var(--ink);border-color:#fff;text-decoration:none;">查看完整周报 →</RouterLink>
            <button class="btn btn-ghost btn-ghost--on-dark" style="color:#fff;border-color:rgba(255,255,255,.4);" @click="handleShare">生成分享长图</button>
          </div>
        </div>
      </div>

      <div style="margin-top:56px;">
        <div class="meta">PREVIOUS ISSUES · 历史报告</div>
        <div class="display-cn" style="font-size:30px;margin-top:4px;margin-bottom:20px;">过往周报</div>
        <div v-if="previousReports.length" style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;">
          <div
            v-for="r in previousReports"
            :key="r.id"
            :data-mood="r.mood"
            style="padding:14px;border:1px solid var(--rule);border-radius:16px;background:var(--paper);cursor:pointer;"
          >
            <MoodBlob :size="240" :drift="false" geometry="blob" style="margin-bottom:12px;" />
            <div class="meta">WEEK {{ r.week }} · {{ r.year }}</div>
            <div :style="{ fontFamily:'var(--serif-cn)',fontSize:'17px',fontWeight:500,marginTop:'4px' }">{{ r.title }}</div>
          </div>
        </div>
        <div v-else style="padding:40px 0;text-align:center;border:1px solid var(--rule);border-radius:16px;background:var(--paper);">
          <div style="font-family:var(--serif-en);font-style:italic;font-size:22px;color:var(--ink-3);">No reports yet.</div>
          <div style="font-family:var(--serif-cn);font-size:13px;color:var(--ink-3);margin-top:6px;">持续使用后，系统将每周自动生成一份专属周报</div>
        </div>
      </div>
    </div>

    <MiniPlayer />
  </div>
</template>

// moodfm-frontend/src/screens/Insights.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { MoodBlob, Icon, Logo } from '../components/atoms';
import { insightsApi } from '../api/insights';
import { reportsApi } from '../api/reports';

// ─── SVG Charts ───────────────────────────────────────────────

function MoodCurveSVG({ trend }) {
  const W = 1100, H = 220;

  if (!trend) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-3)' }}>
        暂无数据
      </div>
    );
  }

  const { labels = [], userMood = [], songMood = [], lowPointIndex = -1 } = trend;
  const n = labels.length;
  const px = (i) => (i / Math.max(n - 1, 1)) * (W - 60) + 30;
  const py = (v) => H - 30 - (v ?? 0.5) * (H - 60);
  const path = (pts) => pts.map((v, i) => `${i === 0 ? 'M' : 'L'} ${px(i)} ${py(v)}`).join(' ');

  return (
    <svg viewBox={`0 0 ${W} ${H}`} width="100%" height="100%" style={{ overflow: 'visible' }}>
      {[0, 0.25, 0.5, 0.75, 1].map((v, i) => (
        <line key={i} x1="30" y1={py(v)} x2={W - 30} y2={py(v)} stroke="var(--rule)" strokeDasharray="2 4" />
      ))}
      {labels.map((d, i) => (
        <text key={d} x={px(i)} y={H - 8} textAnchor="middle"
          style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '.18em', fill: 'var(--ink-3)' }}>{d}</text>
      ))}
      {songMood.length > 0 && (
        <path d={path(songMood)} fill="none" stroke="var(--mood-c)" strokeWidth="1.5" strokeDasharray="4 4" />
      )}
      {userMood.length > 0 && (
        <>
          <path d={path(userMood)} fill="none" stroke="var(--mood-b)" strokeWidth="2" />
          {userMood.map((v, i) => (
            <circle key={i} cx={px(i)} cy={py(v)} r="3" fill="var(--mood-b)" />
          ))}
          {lowPointIndex >= 0 && lowPointIndex < userMood.length && (
            <>
              <circle cx={px(lowPointIndex)} cy={py(userMood[lowPointIndex])} r="7"
                fill="none" stroke="var(--mood-b)" opacity="0.6" />
              <text x={px(lowPointIndex)} y={py(userMood[lowPointIndex]) - 14}
                textAnchor="middle"
                style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 13, fill: 'var(--ink)' }}>
                low point
              </text>
            </>
          )}
        </>
      )}
    </svg>
  );
}

function RadarSVG({ genres }) {
  const data = genres?.length
    ? genres
    : [
        { genre: 'Ambient',    genreCn: '环境', value: 0 },
        { genre: 'Classical',  genreCn: '古典', value: 0 },
        { genre: 'Folk',       genreCn: '民谣', value: 0 },
        { genre: 'Indie',      genreCn: '独立', value: 0 },
        { genre: 'Electronic', genreCn: '电子', value: 0 },
        { genre: 'Jazz',       genreCn: '爵士', value: 0 },
        { genre: 'Pop',        genreCn: '流行', value: 0 },
        { genre: 'Rock',       genreCn: '摇滚', value: 0 },
      ];

  const cx = 180, cy = 180, R = 130;
  const point = (i, r) => {
    const a = (i / data.length) * Math.PI * 2 - Math.PI / 2;
    return [cx + Math.cos(a) * r, cy + Math.sin(a) * r];
  };
  const poly = data.map((d, i) => point(i, R * (d.value ?? 0)).join(',')).join(' ');
  const empty = data.every(d => !d.value);

  return (
    <svg viewBox="0 0 360 360" width="100%" height="320" style={{ maxWidth: 360 }}>
      <defs>
        <radialGradient id="radarFill">
          <stop offset="0%" stopColor="var(--mood-a)" stopOpacity="0.6" />
          <stop offset="100%" stopColor="var(--mood-c)" stopOpacity="0.3" />
        </radialGradient>
      </defs>
      {[0.25, 0.5, 0.75, 1].map((s, i) => (
        <polygon key={i}
          points={data.map((_, j) => point(j, R * s).join(',')).join(' ')}
          fill="none" stroke="var(--rule)" />
      ))}
      {data.map((_, i) => {
        const [x, y] = point(i, R);
        return <line key={i} x1={cx} y1={cy} x2={x} y2={y} stroke="var(--rule)" />;
      })}
      {!empty && (
        <polygon points={poly} fill="url(#radarFill)" stroke="var(--mood-b)" strokeWidth="1.5" />
      )}
      {data.map((d, i) => {
        const [x, y] = point(i, R + 22);
        return (
          <g key={d.genre}>
            <text x={x} y={y} textAnchor="middle"
              style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 13, fill: 'var(--ink)' }}>
              {d.genre}
            </text>
            <text x={x} y={y + 14} textAnchor="middle"
              style={{ fontFamily: 'var(--serif-cn)', fontSize: 10, fill: 'var(--ink-3)' }}>
              {d.genreCn}
            </text>
          </g>
        );
      })}
      {empty && (
        <text x={cx} y={cy + 5} textAnchor="middle"
          style={{ fontFamily: 'var(--serif-cn)', fontSize: 13, fill: 'var(--ink-3)' }}>
          暂无数据
        </text>
      )}
    </svg>
  );
}

// ─── Sub-sections ─────────────────────────────────────────────

function StatCards({ stats }) {
  const items = stats
    ? [
        { l: '本周听歌时长', v: stats.totalListeningTime ?? '—',  en: 'TOTAL · LISTENING', d: stats.listeningVsLast ?? '' },
        { l: '最常听的流派', v: stats.topGenre ?? '—',            en: 'TOP · GENRE',       d: stats.topGenreRatio ?? '' },
        { l: 'AI 推荐准确率', v: stats.aiAccuracy ?? '—',         en: 'AI · ACCURACY',     d: '红心 ÷ 跳过' },
        { l: '心情主旋律',    v: stats.moodKey ?? '—',            en: 'MOOD · KEY',        d: stats.moodSub ?? '' },
      ]
    : Array(4).fill({ l: '—', v: '…', en: '· · ·', d: '' });

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 1, marginTop: 40, background: 'var(--rule)', border: '1px solid var(--rule)' }}>
      {items.map((s, i) => (
        <div key={i} style={{ background: 'var(--bg)', padding: '24px 24px' }}>
          <div className="meta">{s.en}</div>
          <div className="display" style={{ fontSize: 60, marginTop: 8 }}>{s.v}</div>
          <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-2)', marginTop: 4 }}>{s.l}</div>
          {s.d && <div className="meta" style={{ marginTop: 6, color: 'var(--ink-3)' }}>{s.d}</div>}
        </div>
      ))}
    </div>
  );
}

function TopArtists({ artists }) {
  if (!artists?.length) {
    return (
      <div style={{ marginTop: 20, padding: '32px 0', textAlign: 'center', fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-3)' }}>
        暂无数据
      </div>
    );
  }

  const maxTime = artists[0]?.proportion ?? 1;

  return (
    <div style={{ marginTop: 20 }}>
      {artists.map((a, i) => (
        <div key={i} style={{ padding: '14px 0', borderBottom: '1px solid var(--rule)' }}>
          <div className="between">
            <div className="row" style={{ gap: 12 }}>
              <div className="display" style={{ fontSize: 28, color: 'var(--ink-3)', width: 32, flexShrink: 0 }}>
                {String(i + 1).padStart(2, '0')}
              </div>
              <div>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 17, fontWeight: 500 }}>{a.name}</div>
                <div className="meta" style={{ marginTop: 2 }}>{a.genre ?? a.tag ?? ''}</div>
              </div>
            </div>
            <div className="meta" style={{ color: 'var(--ink-2)', flexShrink: 0 }}>{a.totalTime ?? a.playTime ?? ''}</div>
          </div>
          <div style={{ marginTop: 10, height: 2, background: 'var(--rule)', position: 'relative' }}>
            <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: `${(a.proportion ?? 0) * 100}%`, background: 'linear-gradient(90deg, var(--mood-a), var(--mood-c))', transition: 'width 0.6s ease' }} />
          </div>
        </div>
      ))}
    </div>
  );
}

function TopSongs({ songs }) {
  if (!songs?.length) return null;

  return (
    <div style={{ marginTop: 48 }}>
      <div className="meta">FIG. 04 · TOP SONGS</div>
      <div className="display-cn" style={{ fontSize: 30, marginTop: 4 }}>本周 TOP 曲目</div>
      <div style={{ marginTop: 20 }}>
        {songs.map((s, i) => (
          <div key={i} style={{ padding: '12px 0', borderBottom: '1px solid var(--rule)' }}>
            <div className="between">
              <div className="row" style={{ gap: 12 }}>
                <div className="display" style={{ fontSize: 26, color: 'var(--ink-3)', width: 32, flexShrink: 0 }}>
                  {String(i + 1).padStart(2, '0')}
                </div>
                <div>
                  <div style={{ fontFamily: 'var(--serif-en)', fontStyle: 'italic', fontSize: 16 }}>{s.title}</div>
                  <div className="meta" style={{ marginTop: 2 }}>{s.artist}</div>
                </div>
              </div>
              <div className="meta" style={{ color: 'var(--ink-2)', flexShrink: 0 }}>{s.playCount ? `${s.playCount} 次` : ''}</div>
            </div>
            <div style={{ marginTop: 8, height: 2, background: 'var(--rule)', position: 'relative' }}>
              <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: `${(s.proportion ?? 0) * 100}%`, background: 'linear-gradient(90deg, var(--mood-b), var(--mood-c))', transition: 'width 0.6s ease' }} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function AISummaryCard({ summary, navigate, onReportGenerated }) {
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError]     = useState('');

  if (!summary) return null;

  const { essayTitle, essayBody, weeklyReportId } = summary;
  const hasReport = !!weeklyReportId;

  const handleGenerate = async () => {
    setGenerating(true);
    setGenError('');
    try {
      const res = await reportsApi.generate();
      if (res.code === 200 && res.data?.id) {
        onReportGenerated(res.data.id);
        navigate(`/weekly/${res.data.id}`);
      } else {
        setGenError(res.message || '生成失败，请稍后重试');
      }
    } catch {
      setGenError('网络错误，请重试');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div style={{ marginTop: 56, position: 'relative', overflow: 'hidden', borderRadius: 24, padding: 40, color: '#fff' }}>
      <div style={{
        position: 'absolute', inset: 0,
        background: `
          radial-gradient(circle at 15% 20%, var(--mood-a) 0%, transparent 55%),
          radial-gradient(circle at 85% 30%, var(--mood-b) 0%, transparent 55%),
          radial-gradient(circle at 70% 90%, var(--mood-c) 0%, transparent 60%),
          radial-gradient(circle at 5%  80%, var(--mood-d) 0%, transparent 60%)`,
        backgroundColor: 'var(--mood-d)',
      }} />
      <div style={{ position: 'relative' }}>
        <div className="mono" style={{ fontSize: 10, letterSpacing: '.2em', opacity: .85 }}>AI · WEEKLY ESSAY · 周报节选</div>
        {hasReport ? (
          <>
            {essayTitle && (
              <h2 className="display" style={{ fontSize: 60, margin: '12px 0 16px', textShadow: '0 2px 30px rgba(0,0,0,0.2)' }}>
                {essayTitle}
              </h2>
            )}
            {essayBody && (
              <p style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, lineHeight: 1.7, maxWidth: 720 }}>
                {essayBody}
              </p>
            )}
            <div className="row" style={{ marginTop: 24, gap: 10 }}>
              <button className="btn"
                onClick={() => navigate(`/weekly/${weeklyReportId}`)}
                style={{ background: '#fff', color: 'var(--ink)', borderColor: '#fff' }}>
                查看完整周报 →
              </button>
            </div>
          </>
        ) : (
          <>
            <h2 className="display" style={{ fontSize: 60, margin: '12px 0 16px', opacity: 0.8 }}>
              This week,<br/><em>untold.</em>
            </h2>
            <p style={{ fontFamily: 'var(--serif-cn)', fontSize: 16, lineHeight: 1.7, maxWidth: 560, opacity: 0.85 }}>
              AI 将分析你过去一周的收听记录，生成专属周报。
            </p>
            {genError && (
              <p style={{ fontFamily: 'var(--serif-cn)', fontSize: 13, marginTop: 8, opacity: 0.8 }}>{genError}</p>
            )}
            <div className="row" style={{ marginTop: 24, gap: 10 }}>
              <button className="btn"
                onClick={handleGenerate}
                disabled={generating}
                style={{ background: '#fff', color: 'var(--ink)', borderColor: '#fff', opacity: generating ? 0.7 : 1 }}>
                {generating ? 'AI 生成中…' : '生成本周周报 →'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function PreviousReports({ reports, navigate }) {
  if (!reports?.length) return null;

  const moodPalettes = ['energetic', 'focused', 'melancholy', 'dusk', 'calm'];

  return (
    <div style={{ marginTop: 56 }}>
      <div className="meta">PREVIOUS ISSUES · 历史报告</div>
      <div className="display-cn" style={{ fontSize: 30, marginTop: 4, marginBottom: 20 }}>过往周报</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 }}>
        {reports.map((r, i) => (
          <div key={r.id ?? i}
            onClick={() => r.id && navigate(`/weekly/${r.id}`)}
            style={{ padding: 14, border: '1px solid var(--rule)', borderRadius: 16, background: 'var(--paper)', cursor: r.id ? 'pointer' : 'default' }}>
            <div data-mood={r.mood ?? moodPalettes[i % moodPalettes.length]}>
              <MoodBlob size={240} drift={false} geometry="blob" />
            </div>
            <div className="meta" style={{ marginTop: 12 }}>WEEK {r.week} · {r.year ?? new Date().getFullYear()}</div>
            <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 17, fontWeight: 500, marginTop: 4 }}>{r.title}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Main Page ─────────────────────────────────────────────────

export default function Insights() {
  const navigate = useNavigate();
  const [days, setDays] = useState(7);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [summary, setSummary] = useState(null);
  const [trend, setTrend] = useState(null);
  const [genres, setGenres] = useState(null);
  const [topItems, setTopItems] = useState(null);

  useEffect(() => {
    setLoading(true);
    setError('');

    Promise.all([
      insightsApi.getSummary(days),
      insightsApi.getMoodTrend(days),
      insightsApi.getGenreRadar(days),
      insightsApi.getTopItems(days),
    ])
      .then(([sumRes, trendRes, genreRes, topRes]) => {
        if (sumRes.code === 200)   setSummary(sumRes.data);
        if (trendRes.code === 200) setTrend(trendRes.data);
        if (genreRes.code === 200) setGenres(genreRes.data);
        if (topRes.code === 200)   setTopItems(topRes.data);
      })
      .catch(() => setError('数据加载失败，请刷新重试'))
      .finally(() => setLoading(false));
  }, [days]);

  const stats     = summary?.stats;
  const headline  = summary?.headline  ?? '—';
  const headlineAlt = summary?.headlineAlt ?? '—';
  const headlineCn  = summary?.headlineCn  ?? '';
  const weekLabel   = stats?.weekLabel   ?? '';
  const weekRange   = stats?.weekRange   ?? '';

  return (
    <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh' }}>
      <div className="mood-blob drift" style={{ width: 680, height: 680, left: -180, top: -200, opacity: 0.35 }} />

      {/* Sticky top bar */}
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--bg)', padding: '22px 56px',
        borderBottom: '1px solid var(--rule)',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10,
      }}>
        <div className="row" style={{ gap: 10 }}>
          <button onClick={() => navigate('/home')} className="btn-pill"><Icon.chevL /> Home</button>
          <div className="meta" style={{ marginLeft: 8 }}>SECTION IV · INSIGHTS</div>
        </div>
        <div className="row" style={{ gap: 6 }}>
          <button onClick={() => navigate('/calendar')} className="btn-pill">日历 →</button>
          <div style={{ width: 1, height: 18, background: 'var(--rule)', margin: '0 2px' }} />
          {[7, 30, 90].map(d => (
            <button key={d} onClick={() => setDays(d)} className={`btn-pill${days === d ? ' active' : ''}`}>
              {d}天
            </button>
          ))}
        </div>
      </div>

      <div style={{ position: 'relative', zIndex: 2, padding: '40px 56px 100px' }}>

        {/* Error */}
        {error && (
          <div style={{ padding: '14px 20px', background: 'rgba(232,90,138,0.08)', border: '1px solid var(--mood-b)', borderRadius: 12, fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--mood-b)', marginBottom: 32 }}>
            {error}
          </div>
        )}

        {/* Editorial heading */}
        <div className="meta">YOUR EMOTIONAL ATLAS · 个人情绪图鉴{weekLabel ? ` · ${weekLabel}` : ''}</div>
        <h1 className="display" style={{ fontSize: 144, margin: '12px 0 0' }}>You felt</h1>
        <h1 className="display" style={{ fontSize: 144, margin: 0 }}>
          <em style={{ background: 'linear-gradient(120deg, var(--mood-a), var(--mood-b), var(--mood-c))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
            {headline}
          </em>
          <span style={{ color: 'var(--ink)' }}> &amp; </span>
          <em style={{ background: 'linear-gradient(120deg, var(--mood-c), var(--mood-d))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
            {headlineAlt}
          </em>.
        </h1>
        {headlineCn && (
          <div className="display-cn" style={{ fontSize: 32, marginTop: 16, color: 'var(--ink-2)' }}>
            这{days === 7 ? '一周' : days === 30 ? '个月' : '三个月'}，你的心情主旋律是
            <span style={{ color: 'var(--ink)' }}>「{headlineCn}」</span>。
          </div>
        )}

        {/* Stat cards */}
        <StatCards stats={stats} />

        {/* FIG.01 Mood curve */}
        <div style={{ marginTop: 56 }}>
          <div className="between">
            <div>
              <div className="meta">FIG. 01 · MOOD CURVE</div>
              <div className="display-cn" style={{ fontSize: 30, marginTop: 4 }}>心情曲线 vs 听歌情绪</div>
            </div>
            {weekRange && <div className="meta">{weekRange}</div>}
          </div>
          <div style={{ marginTop: 20, height: 280, position: 'relative', border: '1px solid var(--rule)', borderRadius: 18, padding: 24, background: 'var(--paper)' }}>
            {loading
              ? <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-3)' }}>加载中…</div>
              : <MoodCurveSVG trend={trend} />
            }
          </div>
          <div className="row" style={{ gap: 18, marginTop: 12, fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--ink-2)' }}>
            <div className="row" style={{ gap: 6 }}>
              <span style={{ width: 18, height: 2, background: 'var(--mood-b)', display: 'inline-block' }} />
              用户心情
            </div>
            <div className="row" style={{ gap: 6 }}>
              <span style={{ width: 18, height: 0, borderTop: '2px dashed var(--mood-c)', display: 'inline-block' }} />
              听歌情绪
            </div>
          </div>
        </div>

        {/* FIG.02 + FIG.03 two columns */}
        <div style={{ marginTop: 56, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 48 }}>
          {/* Genre radar */}
          <div>
            <div className="meta">FIG. 02 · GENRE</div>
            <div className="display-cn" style={{ fontSize: 30, marginTop: 4 }}>流派分布</div>
            <div style={{ marginTop: 20, display: 'flex', justifyContent: 'center' }}>
              {loading
                ? <div style={{ width: 320, height: 320, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-3)' }}>加载中…</div>
                : <RadarSVG genres={genres} />
              }
            </div>
          </div>

          {/* Top artists */}
          <div>
            <div className="meta">FIG. 03 · TOP ARTISTS</div>
            <div className="display-cn" style={{ fontSize: 30, marginTop: 4 }}>
              {days === 7 ? '本周' : days === 30 ? '本月' : '近三月'} TOP 艺人
            </div>
            {loading
              ? <div style={{ marginTop: 20, fontFamily: 'var(--serif-cn)', fontSize: 14, color: 'var(--ink-3)' }}>加载中…</div>
              : <TopArtists artists={topItems?.artists} />
            }
          </div>
        </div>

        {/* Top songs */}
        {!loading && topItems?.songs?.length > 0 && (
          <TopSongs songs={topItems.songs} />
        )}

        {/* AI Summary */}
        {!loading && (
          <AISummaryCard
            summary={summary}
            navigate={navigate}
            onReportGenerated={(id) => setSummary(s => s ? { ...s, weeklyReportId: id } : s)}
          />
        )}

        {/* Previous reports */}
        {!loading && (
          <PreviousReports reports={summary?.previousReports} navigate={navigate} />
        )}
      </div>
    </div>
  );
}
