// moodfm-frontend/src/views/library/PlaylistList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import MoodBlob from '@/components/common/MoodBlob.vue'
import { playlistApi } from '@/api/playlist'

const router = useRouter()
const tab = ref('我的')
const loading = ref(true)
const error = ref<string | null>(null)

interface PlaylistItem { id: string; t: string; en: string; n: number; m: number; src: string; mood: string; desc: string; ai: boolean }

const lists = ref<PlaylistItem[]>([])

function toPlatformLabel(p: string): string {
  return p === 'netease' ? '网易云' : p === 'qqmusic' ? 'QQ' : p
}

onMounted(async () => {
  try {
    const data = await playlistApi.list()
    lists.value = data.map(pl => ({
      id: pl.id,
      t: pl.name,
      en: pl.name.toUpperCase().slice(0, 16),
      n: pl.trackCount,
      m: Math.round(pl.trackCount * 3.5),
      src: toPlatformLabel(pl.platform),
      mood: 'calm',
      desc: pl.description ?? '',
      ai: false,
    }))
  } catch (e: any) {
    error.value = e?.message ?? '加载失败'
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div style="min-height:100vh;background:var(--bg);padding-bottom:80px;">
    <div style="position:sticky;top:0;z-index:5;background:var(--bg);padding:22px 56px;
                border-bottom:1px solid var(--rule);display:flex;justify-content:space-between;align-items:center;">
      <button class="btn-pill" @click="router.back()">← Home</button>
      <div class="meta">SECTION V · LIBRARY · 我的歌单</div>
      <button class="btn-pill">+ 新建</button>
    </div>

    <div style="padding:40px 56px;">
      <div class="meta">YOUR LIBRARY · {{ lists.length }} 个歌单</div>
      <h1 class="display" style="font-size:120px;margin:10px 0 8px;">Your <em>library</em>.</h1>
      <div class="display-cn" style="font-size:28px;color:var(--ink-2);margin-bottom:24px;">跨平台合并 · 一处看完</div>

      <div class="row" style="gap:0;border-bottom:1px solid var(--rule);margin-bottom:28px;overflow-x:auto;">
        <button
          v-for="t in ['我的','收藏','AI 生成','网易云','QQ 音乐']"
          :key="t"
          :style="{
            background: 'transparent',
            border: 'none',
            padding: '12px 16px',
            cursor: 'pointer',
            fontFamily: 'var(--serif-cn)',
            fontSize: '15px',
            whiteSpace: 'nowrap',
            color: tab === t ? 'var(--ink)' : 'var(--ink-3)',
            borderBottom: tab === t ? '2px solid var(--ink)' : '2px solid transparent',
            marginBottom: '-1px'
          }"
          @click="tab = t"
        >{{ t }}</button>
      </div>

      <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:20px;">
        <div
          v-for="(l, i) in lists"
          :key="i"
          :data-mood="l.mood"
          style="cursor:pointer;"
          @click="router.push('/playlists/' + l.id)"
        >
          <div style="position:relative;">
            <MoodBlob :size="230" :drift="false" geometry="blob" />
            <div
              v-if="l.ai"
              class="meta"
              style="position:absolute;top:8px;left:8px;padding:3px 8px;
                     background:var(--ink);color:var(--bg);border-radius:999px;"
            >AI</div>
            <div
              class="meta"
              style="position:absolute;bottom:8px;right:8px;padding:3px 8px;
                     background:rgba(255,255,255,.86);color:var(--ink);border-radius:999px;"
            >{{ l.src }}</div>
          </div>
          <div class="meta" style="margin-top:10px;">№ {{ String(i + 1).padStart(2, '0') }} · {{ l.en }}</div>
          <div style="font-family:var(--serif-cn);font-size:18px;font-weight:500;margin-top:4px;text-wrap:pretty;">{{ l.t }}</div>
          <div class="meta" style="margin-top:4px;color:var(--ink-3);">{{ l.n }} 首 · {{ l.m }} MIN</div>
        </div>
      </div>
    </div>
  </div>
</template>

// moodfm-frontend/src/screens/PlaylistList.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon } from '../components/atoms';
import { playlistApi } from '../api/playlist';

export default function PlaylistList() {
  const navigate = useNavigate();
  const [playlists, setPlaylists] = useState([]);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState(null);

  useEffect(() => {
    playlistApi.list()
      .then(d => { setPlaylists(Array.isArray(d) ? d : []); setLoading(false); })
      .catch(() => { setError('加载失败，请稍后重试'); setLoading(false); });
  }, []);

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--ink)' }}>
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--bg)', borderBottom: '1px solid var(--rule)',
        padding: '14px 20px', display: 'flex', alignItems: 'center', gap: 12,
      }}>
        <button onClick={() => navigate(-1)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink)', display: 'flex', alignItems: 'center' }}>
          <Icon.chevL/>
        </button>
        <h1 style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, margin: 0, flex: 1 }}>我的歌单</h1>
        <span className="mono" style={{ fontSize: 11, opacity: 0.45 }}>{playlists.length} 个</span>
      </div>

      <div style={{ padding: '24px 20px 80px', maxWidth: 720, margin: '0 auto' }}>
        <div className="meta" style={{ marginBottom: 6 }}>MY PLAYLISTS · 歌单</div>
        <h2 className="display" style={{ fontSize: 52, margin: '6px 0 28px', lineHeight: 1 }}>Playlists.</h2>

        {loading && <div className="mono" style={{ opacity: 0.5 }}>加载中…</div>}
        {error   && <div style={{ color: 'var(--mood-b, #e05)', fontFamily: 'var(--serif-cn)' }}>{error}</div>}

        {!loading && !error && playlists.length === 0 && (
          <div style={{ textAlign: 'center', paddingTop: 60, opacity: 0.4, fontFamily: 'var(--serif-cn)' }}>还没有歌单</div>
        )}

        {!loading && !error && playlists.length > 0 && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 20 }}>
            {playlists.map(pl => (
              <div key={pl.id} onClick={() => navigate(`/playlist/${pl.id}`)} style={{ cursor: 'pointer' }}>
                <div style={{
                  aspectRatio: '1', background: 'var(--paper)', borderRadius: 12,
                  overflow: 'hidden', marginBottom: 10, border: '1px solid var(--rule)',
                }}>
                  {pl.coverUrl
                    ? <img src={pl.coverUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    : <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.2, fontSize: 32 }}>♪</div>
                  }
                </div>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 14, lineHeight: 1.4, marginBottom: 2 }}>{pl.name}</div>
                <div className="mono" style={{ fontSize: 11, opacity: 0.5 }}>{pl.trackCount ?? 0} 首</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
