// moodfm-frontend/src/views/Profile.vue
<template>
  <div style="min-height: 100vh; background: var(--bg); padding-bottom: 100px;">

    <div class="page-pad" style="max-width: 640px;">
      <div class="row" style="align-items: center; gap: 12px; margin-bottom: 8px;">
        <button class="btn-pill" @click="$router.back()">‹ 返回</button>
        <div class="meta">SECTION · PROFILE · 个人信息</div>
      </div>
      <h1 class="display" style="font-size: clamp(48px, 6vw, 96px); margin: 8px 0 0; line-height: 0.95;">Profile.</h1>
      <div class="display-cn" style="font-size: clamp(18px, 2vw, 26px); color: var(--ink-2); margin-bottom: 36px;">
        你的信息 · 个人设置
      </div>

      <div v-if="loading" class="meta" style="color: var(--ink-3); padding: 24px 0;">加载中…</div>

      <div v-else>
        <div class="section-card" style="margin-bottom: 32px;">
          <div class="section-header">
            <span class="meta">AVATAR · 头像</span>
          </div>
          <div class="row" style="gap: 20px; align-items: center; padding: 20px;">
            <div style="position: relative; display: inline-block;">
              <div
                v-if="!avatarPreview"
                style="width: 80px; height: 80px; border-radius: 50%; overflow: hidden; border: 2px solid var(--rule); flex-shrink: 0; cursor: pointer;"
                @click="triggerAvatarInput"
              >
                <MoodBlob :size="80" geometry="circle" :drift="false" />
              </div>
              <img
                v-else
                :src="avatarPreview"
                alt="avatar"
                style="width: 80px; height: 80px; border-radius: 50%; object-fit: cover; border: 2px solid var(--rule); display: block; cursor: pointer;"
                @click="triggerAvatarInput"
              />
              <button
                class="avatar-upload-btn"
                aria-label="上传头像"
                @click="triggerAvatarInput"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="17 8 12 3 7 8" />
                  <line x1="12" y1="3" x2="12" y2="15" />
                </svg>
              </button>
              <input ref="avatarInput" type="file" accept="image/*" style="display: none;" @change="onAvatarChange" />
            </div>
            <div>
              <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '18px', fontWeight: 500 }">{{ form.username || '未设置' }}</div>
              <div class="meta" style="margin-top: 4px; color: var(--ink-3);">{{ form.email }}</div>
            </div>
          </div>
        </div>

        <div class="section-card" style="margin-bottom: 32px;">
          <div class="section-header">
            <span class="meta">PROFILE INFO · 基本信息</span>
          </div>
          <div style="padding: 20px; display: flex; flex-direction: column; gap: 16px;">
            <div class="field">
              <label class="field-label">用户名</label>
              <input
                v-model="form.username"
                type="text"
                class="field-input"
                placeholder="你的用户名"
                maxlength="32"
              />
            </div>
            <div class="field">
              <label class="field-label">邮箱 · Email</label>
              <input
                :value="form.email"
                type="email"
                class="field-input field-input--readonly"
                readonly
                tabindex="-1"
              />
            </div>
            <div class="field">
              <label class="field-label">个人简介</label>
              <textarea
                v-model="form.bio"
                class="field-input"
                style="height: 80px; resize: vertical;"
                placeholder="写点什么…"
                maxlength="200"
              />
            </div>
          </div>
          <div style="padding: 0 20px 20px;">
            <button class="btn" :disabled="savingProfile" @click="saveProfile">
              {{ savingProfile ? '保存中…' : '保存信息' }}
            </button>
            <span v-if="profileSaved" class="meta" style="margin-left: 12px; color: var(--mood-a);">已保存 ✓</span>
          </div>
        </div>

        <div class="section-card" style="margin-bottom: 32px;">
          <div class="section-header">
            <span class="meta">SECURITY · 账号安全</span>
          </div>
          <div style="padding: 20px; display: flex; flex-direction: column; gap: 16px;">
            <div class="field">
              <label class="field-label">旧密码</label>
              <input v-model="pwForm.old" type="password" class="field-input" placeholder="当前密码" autocomplete="current-password" />
            </div>
            <div class="field">
              <label class="field-label">新密码</label>
              <input v-model="pwForm.new1" type="password" class="field-input" placeholder="至少 8 位" autocomplete="new-password" />
            </div>
            <div class="field">
              <label class="field-label">确认新密码</label>
              <input v-model="pwForm.new2" type="password" class="field-input" placeholder="再次输入新密码" autocomplete="new-password" />
            </div>
            <div v-if="pwError" class="meta" style="color: var(--mood-b);">{{ pwError }}</div>
          </div>
          <div style="padding: 0 20px 20px;">
            <button class="btn" :disabled="savingPw" @click="changePassword">
              {{ savingPw ? '修改中…' : '修改密码' }}
            </button>
            <span v-if="pwSaved" class="meta" style="margin-left: 12px; color: var(--mood-a);">密码已修改 ✓</span>
          </div>
        </div>

        <div class="section-card danger-zone">
          <div class="section-header">
            <span class="meta" style="color: var(--mood-b);">DANGER ZONE · 危险区</span>
          </div>
          <div style="padding: 20px;">
            <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '14px', color: 'var(--ink-2)', marginBottom: '16px', lineHeight: 1.6 }">
              注销账号将永久删除你的所有数据，包括播放历史、心情地图、歌单等，此操作不可撤销。
            </div>
            <button
              class="btn"
              style="background: var(--mood-b); border-color: var(--mood-b); color: #fff;"
              @click="showDeleteConfirm = true"
            >
              注销账号
            </button>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="showDeleteConfirm"
      style="position: fixed; inset: 0; z-index: 100; background: rgba(0,0,0,0.45); display: flex; align-items: center; justify-content: center; padding: 24px;"
      @click.self="showDeleteConfirm = false"
    >
      <div style="background: var(--paper); border: 1px solid var(--rule); border-radius: 20px; padding: 32px; max-width: 380px; width: 100%;">
        <div class="meta" style="color: var(--mood-b);">危险操作 · DANGER ZONE</div>
        <h3 :style="{ fontFamily: 'var(--serif-cn)', fontSize: '20px', margin: '12px 0 8px' }">确认注销账号？</h3>
        <p :style="{ fontFamily: 'var(--serif-cn)', fontSize: '14px', color: 'var(--ink-2)', lineHeight: 1.6, margin: '0 0 24px' }">
          此操作无法撤销，你的全部数据将被永久删除。
        </p>
        <div class="row" style="gap: 10px; justify-content: flex-end;">
          <button class="btn-pill" @click="showDeleteConfirm = false">取消</button>
          <button class="btn" style="background: var(--mood-b); border-color: var(--mood-b); color: #fff;" @click="deleteAccount">
            确认注销
          </button>
        </div>
      </div>
    </div>

    <MiniPlayer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import MiniPlayer from '@/components/common/MiniPlayer.vue'
import MoodBlob from '@/components/common/MoodBlob.vue'
import { useUserStore } from '@/stores/user'
import { useAuthStore } from '@/stores/auth'
import { userApi } from '@/api/user'

const userStore = useUserStore()
const authStore = useAuthStore()

const loading = ref(true)
const savingProfile = ref(false)
const profileSaved = ref(false)
const savingPw = ref(false)
const pwSaved = ref(false)
const pwError = ref<string | null>(null)
const showDeleteConfirm = ref(false)
const avatarPreview = ref<string | null>(null)
const avatarInput = ref<HTMLInputElement | null>(null)

const form = ref({ username: '', email: '', bio: '' })
const pwForm = ref({ old: '', new1: '', new2: '' })

onMounted(async () => {
  try {
    const user = await userStore.fetchProfile()
    form.value = { username: user?.username ?? '', email: user?.email ?? '', bio: '' }
    if (user?.avatarUrl) avatarPreview.value = user.avatarUrl
  } catch {
  } finally {
    loading.value = false
  }
})

function triggerAvatarInput() {
  avatarInput.value?.click()
}

async function onAvatarChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (!file) return
  avatarPreview.value = URL.createObjectURL(file)
  try {
    await userApi.uploadAvatar(file)
  } catch {
  }
}

async function saveProfile() {
  savingProfile.value = true
  profileSaved.value = false
  try {
    await userStore.updateProfile({ username: form.value.username })
    profileSaved.value = true
    setTimeout(() => { profileSaved.value = false }, 2500)
  } catch {
  } finally {
    savingProfile.value = false
  }
}

async function changePassword() {
  pwError.value = null
  if (!pwForm.value.old || !pwForm.value.new1 || !pwForm.value.new2) {
    pwError.value = '请填写所有密码字段'
    return
  }
  if (pwForm.value.new1 !== pwForm.value.new2) {
    pwError.value = '两次新密码不一致'
    return
  }
  if (pwForm.value.new1.length < 8) {
    pwError.value = '新密码至少 8 位'
    return
  }
  savingPw.value = true
  try {
    await userApi.changePassword({ oldPassword: pwForm.value.old, newPassword: pwForm.value.new1 })
    pwSaved.value = true
    pwForm.value = { old: '', new1: '', new2: '' }
    setTimeout(() => { pwSaved.value = false }, 2500)
  } catch (err: any) {
    pwError.value = err?.response?.data?.message ?? '修改失败，请检查旧密码'
  } finally {
    savingPw.value = false
  }
}

async function deleteAccount() {
  showDeleteConfirm.value = false
  try {
    await userApi.deleteAccount()
    authStore.logout()
  } catch {
  }
}
</script>

<style scoped>
.page-pad {
  padding: 32px 56px 0;
}

@media (max-width: 768px) {
  .page-pad {
    padding: 24px 18px 0;
  }
}

.section-card {
  border: 1px solid var(--rule);
  border-radius: 16px;
  background: var(--paper);
  overflow: hidden;
}

.section-header {
  padding: 12px 20px;
  border-bottom: 1px solid var(--rule);
  background: var(--bg-2);
}

.danger-zone {
  border-color: color-mix(in srgb, var(--mood-b) 30%, transparent);
}

.field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.field-label {
  font-family: var(--mono);
  font-size: 10px;
  letter-spacing: 0.15em;
  color: var(--ink-3);
  text-transform: uppercase;
}

.field-input {
  width: 100%;
  padding: 10px 14px;
  border: 1px solid var(--rule);
  border-radius: 8px;
  background: var(--bg);
  color: var(--ink);
  font-family: var(--serif-cn);
  font-size: 15px;
  outline: none;
  transition: border-color 0.15s;
}

.field-input:focus {
  border-color: var(--ink-3);
}

.field-input--readonly {
  color: var(--ink-3);
  cursor: default;
}

.avatar-upload-btn {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: var(--ink);
  color: var(--bg);
  border: 2px solid var(--bg);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: opacity 0.15s;
}

.avatar-upload-btn:hover {
  opacity: 0.8;
}
</style>

// moodfm-frontend/src/screens/Profile.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon } from '../components/atoms';
import { useUserStore } from '../store/userStore';
import { useAuthStore } from '../store/authStore';

function Field({ label, value, editing, onChange }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.14em', opacity: 0.45, marginBottom: 6 }}>
        {label}
      </div>
      {editing ? (
        <input
          value={value ?? ''}
          onChange={e => onChange(e.target.value)}
          style={{
            width: '100%', padding: '10px 0', background: 'transparent',
            border: 'none', borderBottom: '1px solid var(--ink)',
            color: 'var(--ink)', fontSize: 16, fontFamily: 'var(--serif-cn)',
            outline: 'none',
          }}
        />
      ) : (
        <div style={{ padding: '10px 0', borderBottom: '1px solid var(--rule)', fontSize: 16, fontFamily: 'var(--serif-cn)' }}>
          {value || <span style={{ opacity: 0.3 }}>未填写</span>}
        </div>
      )}
    </div>
  );
}

export default function Profile() {
  const navigate = useNavigate();
  const { profile, loading, fetchProfile, updateProfile, uploadAvatar } = useUserStore();
  const authUser = useAuthStore(s => s.user);
  const setAuthUser = useAuthStore(s => s.setUser);

  const [editing, setEditing]   = useState(false);
  const [saving,  setSaving]    = useState(false);
  const [toast,   setToast]     = useState(null);
  const [form,    setForm]      = useState({ username: '', email: '', phone: '' });

  useEffect(() => { fetchProfile(); }, []);

  useEffect(() => {
    if (profile) {
      setForm({ username: profile.username ?? '', email: profile.email ?? '', phone: profile.phone ?? '' });
    }
  }, [profile]);

  const showToast = (msg, ok = true) => {
    setToast({ msg, ok });
    setTimeout(() => setToast(null), 2500);
  };

  const handleSave = async () => {
    setSaving(true);
    const result = await updateProfile(form);
    setSaving(false);
    if (result.ok) {
      setEditing(false);
      setAuthUser({ ...authUser, username: form.username });
      showToast('保存成功');
    } else {
      showToast(result.error, false);
    }
  };

  const handleAvatarChange = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const result = await uploadAvatar(file);
    if (!result.ok) showToast(result.error, false);
  };

  const field = (key) => ({
    value: form[key],
    editing,
    onChange: (v) => setForm(f => ({ ...f, [key]: v })),
  });

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--ink)' }}>
      {/* Sticky top bar */}
      <div style={{ position: 'sticky', top: 0, zIndex: 5, background: 'var(--bg)', padding: '18px 24px', borderBottom: '1px solid var(--rule)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={() => navigate('/settings')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink)', display: 'flex', alignItems: 'center', gap: 6 }}>
          <Icon.chevL /> <span style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.12em' }}>设置</span>
        </button>
        <div style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.14em', opacity: 0.5 }}>PROFILE · 个人资料</div>
        {editing ? (
          <button onClick={handleSave} disabled={saving} style={{ background: 'var(--ink)', color: 'var(--bg)', border: 'none', borderRadius: 20, padding: '7px 18px', cursor: 'pointer', fontFamily: 'var(--serif-cn)', fontSize: 13 }}>
            {saving ? '保存中…' : '保存'}
          </button>
        ) : (
          <button onClick={() => setEditing(true)} style={{ background: 'none', border: '1px solid var(--rule)', borderRadius: 20, padding: '7px 18px', cursor: 'pointer', color: 'var(--ink)', fontFamily: 'var(--serif-cn)', fontSize: 13 }}>
            编辑
          </button>
        )}
      </div>

      <div style={{ padding: '32px 24px 80px', maxWidth: 760, margin: '0 auto' }}>
        {/* Title */}
        <div style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.14em', opacity: 0.4 }}>YOUR CARD · 你的卡片</div>
        <h1 style={{ fontFamily: 'var(--serif-en, serif)', fontSize: 'clamp(48px, 8vw, 96px)', margin: '8px 0 4px', lineHeight: 1, fontStyle: 'italic' }}>
          Profile<span style={{ opacity: 0.3 }}>.</span>
        </h1>
        <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, color: 'var(--ink)', opacity: 0.5, marginBottom: 36 }}>这是你在电台里的样子</div>

        {loading && !profile ? (
          <div style={{ opacity: 0.4, fontFamily: 'var(--mono)', fontSize: 12 }}>加载中…</div>
        ) : (
          <>
            {/* Avatar + name/bio row */}
            <div style={{ display: 'flex', gap: 28, marginBottom: 36, alignItems: 'flex-start', flexWrap: 'wrap' }}>
              <div style={{ position: 'relative', flexShrink: 0 }}>
                <div style={{ width: 120, height: 120, borderRadius: '50%', background: 'var(--surface, #f0f0f0)', overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 40 }}>
                  {profile?.avatarUrl
                    ? <img src={profile.avatarUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    : <span style={{ opacity: 0.3 }}>🎵</span>
                  }
                </div>
                <label style={{ position: 'absolute', bottom: 4, right: 4, background: 'var(--ink)', color: 'var(--bg)', borderRadius: 14, padding: '4px 10px', fontSize: 11, fontFamily: 'var(--mono)', cursor: 'pointer', letterSpacing: '.08em' }}>
                  更换
                  <input type="file" accept="image/*" style={{ display: 'none' }} onChange={handleAvatarChange} />
                </label>
              </div>
              <div style={{ flex: 1, minWidth: 220 }}>
                <Field label="昵称 · NAME" {...field('username')} />
              </div>
            </div>

            {/* Contact fields */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: '0 32px' }}>
              <Field label="邮箱 · EMAIL" {...field('email')} />
              <Field label="手机 · PHONE" {...field('phone')} />
            </div>

            {/* Divider */}
            <div style={{ borderTop: '1px dashed var(--rule)', margin: '32px 0 24px' }} />

            {/* Password change */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 0', borderBottom: '1px solid var(--rule)', cursor: 'pointer' }}
              onClick={() => navigate('/settings')}>
              <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>修改密码</div>
              <span style={{ opacity: 0.4 }}>›</span>
            </div>

            {/* Delete account */}
            <div style={{ marginTop: 48, textAlign: 'center' }}>
              <button style={{ background: 'none', border: 'none', color: '#e05', fontSize: 13, fontFamily: 'var(--serif-cn)', cursor: 'pointer', opacity: 0.7 }}>
                注销账号
              </button>
            </div>
          </>
        )}
      </div>

      {/* Toast */}
      {toast && (
        <div style={{
          position: 'fixed', bottom: 32, left: '50%', transform: 'translateX(-50%)',
          background: toast.ok ? 'var(--ink)' : '#e05',
          color: '#fff', borderRadius: 24, padding: '10px 22px',
          fontFamily: 'var(--serif-cn)', fontSize: 14, zIndex: 100,
          boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
        }}>
          {toast.msg}
        </div>
      )}
    </div>
  );
}
