// moodfm-frontend/src/views/settings/Settings.vue
<template>
  <div style="min-height: 100vh; background: var(--bg); padding-bottom: 100px;">
    <NavBar />

    <div class="page-pad" style="max-width: 880px;">
      <div class="meta">CONTROL ROOM · 调台室</div>
      <h1 class="display" style="font-size: clamp(52px, 7vw, 108px); margin: 10px 0 0;">Settings.</h1>
      <div class="display-cn" style="font-size: clamp(18px, 2vw, 28px); color: var(--ink-2); margin-bottom: 32px;">
        所有的旋钮 · 都在这里
      </div>

      <div v-if="loading" class="meta" style="color: var(--ink-3); padding: 24px 0;">加载中…</div>

      <div v-else>
        <div
          v-for="(g, gi) in settingGroups"
          :key="gi"
          style="margin-bottom: 32px;"
        >
          <div class="row" style="gap: 12px; align-items: baseline; margin-bottom: 14px;">
            <span class="meta">№ {{ String(gi + 1).padStart(2, '0') }}</span>
            <span class="serif-en" :style="{ fontSize: 'clamp(24px, 2.5vw, 36px)' }">
              {{ g.en.toLowerCase() }}<span style="color: var(--ink-3);">.</span>
            </span>
            <span :style="{ fontFamily: 'var(--serif-cn)', fontSize: '16px', color: 'var(--ink-2)' }">{{ g.title }}</span>
          </div>

          <div style="border: 1px solid var(--rule); border-radius: 14px; background: var(--paper); overflow: hidden;">
            <div
              v-for="(item, ii) in g.items"
              :key="ii"
              class="setting-row"
              :style="{ borderBottom: ii < g.items.length - 1 ? '1px solid var(--rule)' : 'none' }"
            >
              <div style="flex: 1; min-width: 0;">
                <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '15px', color: item.danger ? 'var(--mood-b)' : 'var(--ink)' }">{{ item.l }}</div>
                <div v-if="item.sub" class="meta" style="margin-top: 2px; color: var(--ink-3);">· {{ item.sub }}</div>
              </div>

              <button
                v-if="item.kind === 'toggle'"
                class="toggle-btn"
                :class="{ 'toggle-btn--on': item.value }"
                @click="toggleItem(item)"
              >
                <span class="toggle-thumb" :style="{ transform: item.value ? 'translateX(18px)' : 'translateX(0)' }" />
              </button>

              <div v-else-if="item.kind === 'segment'" class="segment-ctrl">
                <button
                  v-for="(opt, oi) in item.options"
                  :key="oi"
                  class="segment-opt"
                  :class="{ 'segment-opt--active': item.segValue === oi }"
                  @click="setSegment(item, oi)"
                >{{ opt }}</button>
              </div>

              <div v-else-if="item.kind === 'slider'" style="display: flex; align-items: center; gap: 10px; flex-shrink: 0;">
                <span class="mono" style="font-size: 12px; color: var(--ink-2); min-width: 28px; text-align: right;">{{ item.sliderValue }}s</span>
                <input
                  type="range"
                  :min="item.min"
                  :max="item.max"
                  :value="item.sliderValue"
                  style="width: 100px; accent-color: var(--ink);"
                  @input="setSlider(item, ($event.target as HTMLInputElement).valueAsNumber)"
                />
              </div>

              <button
                v-else-if="item.kind === 'link'"
                class="link-ctrl"
                @click="item.action && item.action()"
              >
                <span v-if="item.hint" class="meta" style="color: var(--ink-2);">{{ item.hint }}</span>
                <span style="font-size: 14px; color: var(--ink-3);">›</span>
              </button>

              <span v-else-if="item.kind === 'value'" class="mono" style="font-size: 12px; color: var(--ink-3); flex-shrink: 0;">{{ item.hint }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="showConfirm"
      style="position: fixed; inset: 0; z-index: 100; background: rgba(0,0,0,0.45); display: flex; align-items: center; justify-content: center; padding: 24px;"
      @click.self="showConfirm = false"
    >
      <div style="background: var(--paper); border: 1px solid var(--rule); border-radius: 20px; padding: 32px; max-width: 380px; width: 100%;">
        <div class="meta" style="color: var(--mood-b);">危险操作 · DANGER ZONE</div>
        <h3 :style="{ fontFamily: 'var(--serif-cn)', fontSize: '20px', margin: '12px 0 8px' }">{{ confirmTitle }}</h3>
        <p :style="{ fontFamily: 'var(--serif-cn)', fontSize: '14px', color: 'var(--ink-2)', lineHeight: 1.6, margin: '0 0 24px' }">{{ confirmBody }}</p>
        <div class="row" style="gap: 10px; justify-content: flex-end;">
          <button class="btn-pill" @click="showConfirm = false">取消</button>
          <button class="btn" style="background: var(--mood-b); border-color: var(--mood-b); color: #fff;" @click="confirmAction">确认</button>
        </div>
      </div>
    </div>

    <MiniPlayer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import NavBar from '@/components/common/NavBar.vue'
import MiniPlayer from '@/components/common/MiniPlayer.vue'
import { useUiStore } from '@/stores/ui'
import { useAuthStore } from '@/stores/auth'
import { userApi } from '@/api/user'
import type { MoodPreset, Theme } from '@/types'

const router = useRouter()
const uiStore = useUiStore()
const authStore = useAuthStore()

const loading = ref(false)
const showConfirm = ref(false)
const confirmTitle = ref('')
const confirmBody = ref('')
let pendingConfirm: (() => void) | null = null

function confirmAction() {
  pendingConfirm?.()
  showConfirm.value = false
  pendingConfirm = null
}

function askConfirm(title: string, body: string, action: () => void) {
  confirmTitle.value = title
  confirmBody.value = body
  pendingConfirm = action
  showConfirm.value = true
}

const THEME_OPTIONS = ['明', '暗', '系统']
const QUALITY_OPTIONS = ['标准', '高品', '无损']
const PRESET_OPTIONS: MoodPreset[] = ['dusk', 'melancholy', 'energetic', 'focused', 'calm']
const PRESET_LABELS = ['黄昏', '忧郁', '高能', '专注', '平静']

interface SettingItem {
  l: string
  kind: 'toggle' | 'segment' | 'slider' | 'link' | 'value'
  sub?: string
  danger?: boolean
  value?: boolean
  options?: string[]
  segValue?: number
  min?: number
  max?: number
  sliderValue?: number
  hint?: string
  action?: () => void
}

interface SettingGroup {
  title: string
  en: string
  items: SettingItem[]
}

const settingGroups = ref<SettingGroup[]>([
  {
    title: '账号',
    en: 'ACCOUNT',
    items: [
      { l: '个人资料', kind: 'link', hint: '', action: () => router.push('/profile') },
      { l: '平台管理', kind: 'link', hint: '网易云 · QQ 音乐', action: () => router.push('/bind') },
      { l: '修改密码', kind: 'link', hint: '', action: () => router.push('/profile') },
    ],
  },
  {
    title: '外观',
    en: 'APPEARANCE',
    items: [
      {
        l: '主题',
        kind: 'segment',
        options: THEME_OPTIONS,
        segValue: uiStore.theme === 'dark' ? 1 : 0,
      },
      {
        l: '心情色调',
        kind: 'segment',
        options: PRESET_LABELS,
        segValue: PRESET_OPTIONS.indexOf(uiStore.moodPreset),
      },
      { l: '减弱动效', kind: 'toggle', value: false, sub: '流体 blob、过渡都收敛' },
    ],
  },
  {
    title: '电台偏好',
    en: 'RADIO PREFERENCES',
    items: [
      { l: '流派偏好', kind: 'link', hint: 'Ambient · Folk · +5', action: () => {} },
      { l: '默认场景', kind: 'link', hint: '深夜', action: () => {} },
      { l: '露出冷门曲目', kind: 'toggle', value: true, sub: '让 AI 偶尔推荐你曲库外的歌' },
      { l: '自动续播', kind: 'toggle', value: true, sub: '听完一档自动开下一档' },
    ],
  },
  {
    title: '声音',
    en: 'AUDIO',
    items: [
      { l: '音质', kind: 'segment', options: QUALITY_OPTIONS, segValue: 1 },
      { l: '交叉渐变时长', kind: 'slider', min: 0, max: 12, sliderValue: 4 },
      { l: '按时间均衡', kind: 'toggle', value: true, sub: '夜深时自动收紧低音' },
    ],
  },
  {
    title: '隐私',
    en: 'PRIVACY',
    items: [
      { l: '分享情绪周报到公开主页', kind: 'toggle', value: false },
      { l: '匿名贡献心情数据', kind: 'toggle', value: true, sub: '帮助改善推荐 · 永不识别个人' },
      { l: '黑名单管理', kind: 'link', hint: '12 首', action: () => router.push('/blacklist') },
      { l: '清除播放历史', kind: 'link', danger: true, hint: '', action: () => askConfirm('清除播放历史', '此操作无法撤销，你的全部播放历史将被永久删除。', async () => { await userApi.getDevices() }) },
    ],
  },
  {
    title: '关于',
    en: 'ABOUT',
    items: [
      { l: '版本', kind: 'value', hint: '1.4.2 (2026.05)' },
      { l: '服务条款 · 隐私政策', kind: 'link', hint: '', action: () => {} },
      { l: '反馈与建议', kind: 'link', hint: '', action: () => {} },
      { l: '退出登录', kind: 'link', danger: true, hint: '', action: () => askConfirm('退出登录', '确认退出当前账号？', () => authStore.logout()) },
    ],
  },
])

function toggleItem(item: SettingItem) {
  item.value = !item.value
  savePreferences()
}

function setSegment(item: SettingItem, oi: number) {
  item.segValue = oi
  const groupIdx = settingGroups.value.findIndex(g => g.items.includes(item))
  if (groupIdx === 1) {
    if (item.l === '主题') {
      uiStore.setTheme(oi === 1 ? 'dark' : 'light')
    } else if (item.l === '心情色调') {
      uiStore.setMoodPreset(PRESET_OPTIONS[oi])
    }
  }
  savePreferences()
}

function setSlider(item: SettingItem, value: number) {
  item.sliderValue = value
  savePreferences()
}

let saveTimer: ReturnType<typeof setTimeout>
function savePreferences() {
  clearTimeout(saveTimer)
  saveTimer = setTimeout(async () => {
    const audioGroup = settingGroups.value.find(g => g.en === 'AUDIO')
    const prefGroup = settingGroups.value.find(g => g.en === 'RADIO PREFERENCES')
    const autoPlay = prefGroup?.items.find(i => i.l === '自动续播')?.value ?? true
    const crossfade = audioGroup?.items.find(i => i.l === '交叉渐变时长')?.sliderValue ?? 4
    try {
      await userApi.updatePreferences({ autoPlay, crossfadeDuration: crossfade, theme: uiStore.theme })
    } catch {
    }
  }, 600)
}

onMounted(async () => {
  try {
    const res = await userApi.getPreferences()
    if (res?.data) {
      const prefs = res.data
      const prefGroup = settingGroups.value.find(g => g.en === 'RADIO PREFERENCES')
      const autoPlayItem = prefGroup?.items.find(i => i.l === '自动续播')
      if (autoPlayItem) autoPlayItem.value = prefs.autoPlay ?? true
      const audioGroup = settingGroups.value.find(g => g.en === 'AUDIO')
      const crossfadeItem = audioGroup?.items.find(i => i.l === '交叉渐变时长')
      if (crossfadeItem) crossfadeItem.sliderValue = prefs.crossfadeDuration ?? 4
    }
  } catch {
  }
})
</script>

<style scoped>
.page-pad {
  padding: 40px 56px 0;
}

@media (max-width: 768px) {
  .page-pad {
    padding: 24px 18px 0;
  }
}

.setting-row {
  padding: 14px 18px;
  display: flex;
  align-items: center;
  gap: 14px;
}

.toggle-btn {
  width: 42px;
  height: 24px;
  border-radius: 999px;
  padding: 2px;
  border: none;
  background: var(--rule);
  cursor: pointer;
  position: relative;
  flex-shrink: 0;
  transition: background 0.2s;
}

.toggle-btn--on {
  background: var(--ink);
}

.toggle-thumb {
  display: block;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: var(--paper);
  transition: transform 0.2s;
}

.segment-ctrl {
  display: flex;
  gap: 0;
  border: 1px solid var(--rule);
  border-radius: 999px;
  padding: 2px;
  flex-shrink: 0;
}

.segment-opt {
  padding: 4px 10px;
  border-radius: 999px;
  border: none;
  cursor: pointer;
  background: transparent;
  color: var(--ink-2);
  font-family: var(--serif-cn);
  font-size: 12px;
  white-space: nowrap;
  transition: background 0.15s, color 0.15s;
}

.segment-opt--active {
  background: var(--ink);
  color: var(--bg);
}

.link-ctrl {
  display: flex;
  align-items: center;
  gap: 8px;
  background: transparent;
  border: none;
  cursor: pointer;
  flex-shrink: 0;
  color: var(--ink-3);
  padding: 0;
}
</style>

// moodfm-frontend/src/screens/Settings.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon } from '../components/atoms';
import { useAuthStore } from '../store/authStore';

function Toggle({ on, onChange }) {
  return (
    <button
      onClick={() => onChange(!on)}
      style={{
        width: 42, height: 24, borderRadius: 999, padding: 2, border: 'none',
        background: on ? 'var(--ink)' : 'var(--rule)', cursor: 'pointer',
        position: 'relative', flexShrink: 0, transition: 'background .2s',
      }}
    >
      <span style={{
        display: 'block', width: 20, height: 20, borderRadius: '50%',
        background: 'var(--paper)',
        transform: on ? 'translateX(18px)' : 'translateX(0)',
        transition: 'transform .2s',
      }}/>
    </button>
  );
}

function Segment({ options, value, onChange }) {
  return (
    <div style={{
      display: 'flex', gap: 0,
      border: '1px solid var(--rule)', borderRadius: 999, padding: 2, flexShrink: 0,
    }}>
      {options.map((opt, i) => (
        <button key={i} onClick={() => onChange(i)} style={{
          padding: '4px 12px', borderRadius: 999, border: 'none', cursor: 'pointer',
          background: value === i ? 'var(--ink)' : 'transparent',
          color: value === i ? 'var(--bg)' : 'var(--ink-2)',
          fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.1em',
          whiteSpace: 'nowrap', transition: 'background .15s',
        }}>{opt}</button>
      ))}
    </div>
  );
}

function SettingRow({ label, sub, value, kind, danger, onClick, children }) {
  return (
    <div
      onClick={kind === 'link' && onClick ? onClick : undefined}
      style={{
        padding: '14px 18px',
        borderBottom: '1px solid var(--rule)',
        display: 'flex', alignItems: 'center', gap: 14,
        cursor: kind === 'link' && onClick ? 'pointer' : 'default',
      }}
    >
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontFamily: 'var(--serif-cn)', fontSize: 15,
          color: danger ? 'var(--mood-b, #e05)' : 'var(--ink)',
        }}>{label}</div>
        {sub && <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· {sub}</div>}
      </div>
      {kind === 'link' && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--ink-3)', flexShrink: 0 }}>
          {value && <span className="meta" style={{ color: 'var(--ink-2)' }}>{value}</span>}
          <span style={{ fontSize: 16 }}>›</span>
        </div>
      )}
      {kind === 'value' && (
        <span className="mono" style={{ fontSize: 12, color: 'var(--ink-3)', flexShrink: 0 }}>{value}</span>
      )}
      {children}
    </div>
  );
}

function GroupHeader({ num, en, cn }) {
  return (
    <div className="row" style={{ gap: 12, alignItems: 'baseline', marginBottom: 14 }}>
      <span className="meta">№ {String(num).padStart(2, '0')}</span>
      <span className="serif-en" style={{ fontSize: 28 }}>
        {en.toLowerCase()}<span style={{ color: 'var(--ink-3)' }}>.</span>
      </span>
      <span style={{ fontFamily: 'var(--serif-cn)', fontSize: 15, color: 'var(--ink-2)' }}>{cn}</span>
    </div>
  );
}

export default function Settings() {
  const navigate = useNavigate();
  const logout   = useAuthStore(s => s.logout);

  const [radioToggle, setRadioToggle] = useState({ rare: true, autoplay: true });
  const [theme, setTheme]    = useState(1);
  const [motionOff, setMotion] = useState(false);
  const [quality, setQuality] = useState(1);
  const [eqTime, setEqTime]   = useState(true);
  const [shareWeekly, setShareWeekly] = useState(false);
  const [anonData, setAnonData]       = useState(true);

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--ink)' }}>
      {/* Sticky top bar */}
      <div style={{
        position: 'sticky', top: 0, zIndex: 5,
        background: 'var(--bg)', borderBottom: '1px solid var(--rule)',
        padding: '14px 20px',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <button
          onClick={() => navigate(-1)}
          style={{ background: 'none', border: '1px solid var(--rule)', borderRadius: 999, padding: '6px 14px', cursor: 'pointer', color: 'var(--ink)', display: 'flex', alignItems: 'center', gap: 6, fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.12em' }}
        >
          <Icon.chevL/> Home
        </button>
        <div className="meta">SECTION VIII · SETTINGS · 设置</div>
        <div style={{ width: 80 }}/>
      </div>

      <div style={{ padding: '40px 20px 80px', maxWidth: 720, margin: '0 auto' }}>
        <div className="meta">CONTROL ROOM · 调台室</div>
        <h1 className="display" style={{ fontSize: 72, margin: '10px 0 0', lineHeight: 1 }}>Settings.</h1>
        <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 20, color: 'var(--ink-2)', marginBottom: 40 }}>
          所有的旋钮 · 都在这里
        </div>

        {/* 01 账号 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={1} en="ACCOUNT" cn="账号"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <SettingRow label="个人资料" value="江野 · jiangye@gmail.com" kind="link" onClick={() => navigate('/profile')}/>
            <SettingRow label="平台管理" value="网易云 · QQ 音乐" kind="link" onClick={() => navigate('/settings/platforms')}/>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14, borderBottom: 'none' }}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15 }}>修改密码</div>
              <span style={{ fontSize: 16, color: 'var(--ink-3)' }}>›</span>
            </div>
          </div>
        </div>

        {/* 02 电台偏好 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={2} en="RADIO" cn="电台偏好"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <SettingRow label="流派偏好" value="Ambient · Folk · Indie · +5" kind="link" onClick={() => {}}/>
            <SettingRow label="语言偏好" value="中文 · English · 日本語" kind="link" onClick={() => {}}/>
            <SettingRow label="默认场景" value="深夜" kind="link" onClick={() => {}}/>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>露出冷门曲目</div>
                <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· 让 AI 偶尔推荐你曲库外的歌</div>
              </div>
              <Toggle on={radioToggle.rare} onChange={v => setRadioToggle(s => ({ ...s, rare: v }))}/>
            </div>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>自动续播</div>
                <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· 听完一档自动开下一档</div>
              </div>
              <Toggle on={radioToggle.autoplay} onChange={v => setRadioToggle(s => ({ ...s, autoplay: v }))}/>
            </div>
          </div>
        </div>

        {/* 03 外观 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={3} en="APPEARANCE" cn="外观"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15 }}>主题</div>
              <Segment options={['明', '暗', '跟随系统']} value={theme} onChange={setTheme}/>
            </div>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>减弱动效</div>
                <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· 流体 blob、过渡都收敛</div>
              </div>
              <Toggle on={motionOff} onChange={setMotion}/>
            </div>
          </div>
        </div>

        {/* 04 声音 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={4} en="AUDIO" cn="声音"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15 }}>音质</div>
              <Segment options={['标准', '高品', '无损']} value={quality} onChange={setQuality}/>
            </div>
            <SettingRow label="淡入淡出" value="4s" kind="link" onClick={() => {}}/>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>按时间均衡</div>
                <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· 夜深时自动收紧低音</div>
              </div>
              <Toggle on={eqTime} onChange={setEqTime}/>
            </div>
          </div>
        </div>

        {/* 05 隐私 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={5} en="PRIVACY" cn="隐私"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15 }}>分享情绪周报到公开主页</div>
              <Toggle on={shareWeekly} onChange={setShareWeekly}/>
            </div>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 15 }}>匿名贡献心情数据</div>
                <div className="meta" style={{ marginTop: 2, color: 'var(--ink-3)' }}>· 帮助改善推荐 · 永不识别个人</div>
              </div>
              <Toggle on={anonData} onChange={setAnonData}/>
            </div>
            <SettingRow label="黑名单管理" value="12 首 · 3 位艺人" kind="link" onClick={() => navigate('/settings/blacklist')}/>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14, cursor: 'pointer' }} onClick={() => {}}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15, color: 'var(--mood-b, #e05)' }}>清除播放历史</div>
              <span style={{ fontSize: 16, color: 'var(--ink-3)' }}>›</span>
            </div>
          </div>
        </div>

        {/* 06 关于 */}
        <div style={{ marginBottom: 36 }}>
          <GroupHeader num={6} en="ABOUT" cn="关于"/>
          <div style={{ border: '1px solid var(--rule)', borderRadius: 14, background: 'var(--paper)', overflow: 'hidden' }}>
            <SettingRow label="版本" value="1.4.2 (2026.05)" kind="value"/>
            <SettingRow label="服务条款 · 隐私政策" kind="link" onClick={() => {}}/>
            <SettingRow label="反馈与建议" kind="link" onClick={() => {}}/>
            <div style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14, cursor: 'pointer' }} onClick={handleLogout}>
              <div style={{ flex: 1, fontFamily: 'var(--serif-cn)', fontSize: 15, color: 'var(--mood-b, #e05)' }}>退出登录</div>
              <span style={{ fontSize: 16, color: 'var(--ink-3)' }}>›</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
