// moodfm-frontend/src/screens/Bind.jsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Icon, Logo } from '../components/atoms';
import { platformApi } from '../api/platform';

// ---- 真实 QR 扫码组件 ----
function QRBlock({ platform, onSuccess }) {
  const [qrImg, setQrImg] = useState('');
  const [qrKey, setQrKey] = useState('');
  const [status, setStatus] = useState('loading'); // loading | waiting | scanned | success | expired | error
  const [countdown, setCountdown] = useState(90);
  const pollRef = useRef(null);
  const countRef = useRef(null);

  const startQR = async () => {
    setStatus('loading');
    setCountdown(90);
    clearInterval(pollRef.current);
    clearInterval(countRef.current);
    try {
      const res = await platformApi.generateQR(platform);
      if (res.code === 200) {
        setQrImg(res.data.qrimg);
        setQrKey(res.data.key);
        setStatus('waiting');
        startPolling(res.data.key);
        startCountdown();
      } else {
        setStatus('error');
      }
    } catch (e) {
      console.error('QR generate failed', e);
      setStatus('error');
    }
  };

  const startPolling = (key) => {
    pollRef.current = setInterval(async () => {
      try {
        const res = await platformApi.checkQRStatus(platform, key);
        if (res.code === 200) {
          const s = res.data.status;
          setStatus(s);
          if (s === 'success') {
            clearInterval(pollRef.current);
            clearInterval(countRef.current);
            onSuccess?.();
          } else if (s === 'expired' || s === 'error') {
            clearInterval(pollRef.current);
            clearInterval(countRef.current);
          }
        }
      } catch {}
    }, 2000);
  };

  const startCountdown = () => {
    countRef.current = setInterval(() => {
      setCountdown(c => {
        if (c <= 1) {
          clearInterval(countRef.current);
          return 0;
        }
        return c - 1;
      });
    }, 1000);
  };

  useEffect(() => {
    startQR();
    return () => { clearInterval(pollRef.current); clearInterval(countRef.current); };
  }, [platform]);

  const statusText = {
    loading: '正在生成二维码…',
    waiting: `等待扫码 · ${countdown}s`,
    scanned: '已扫码，请在手机上确认',
    success: '绑定成功！',
    expired: '二维码已过期',
    error: '扫码确认成功，但凭证获取失败——请切换至 Cookie 方式完成绑定',
  }[status] || '';

  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ display: 'inline-block', position: 'relative', padding: 24, border: '1px solid var(--rule)', borderRadius: 18, background: 'var(--bg)' }}>
        <div style={{ width: 200, height: 200, position: 'relative', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {qrImg ? (
            <img src={qrImg} alt="QR Code" style={{ width: 184, height: 184 }} />
          ) : (
            <div style={{ fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-3)' }}>
              {status === 'loading' ? '加载中…' : '—'}
            </div>
          )}
          {(status === 'expired' || status === 'error') && (
            <div style={{ position: 'absolute', inset: 0, background: 'rgba(255,255,255,0.92)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 8 }}>
              <div className="meta">{status === 'expired' ? 'QR EXPIRED' : '凭证获取失败'}</div>
              {status === 'expired'
                ? <button onClick={startQR} className="btn" style={{ height: 36 }}>刷新</button>
                : <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 12, color: 'var(--ink-2)', textAlign: 'center', lineHeight: 1.5 }}>
                    扫码已确认，请切换<br/>至 <b>Cookie</b> 方式完成绑定
                  </div>
              }
            </div>
          )}
          {status === 'success' && (
            <div style={{ position: 'absolute', inset: 0, background: 'rgba(255,255,255,0.92)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
              <div style={{ fontSize: 32 }}>✓</div>
              <div className="meta" style={{ color: 'var(--ink)' }}>绑定成功</div>
            </div>
          )}
        </div>
      </div>
      <div className="meta" style={{ marginTop: 18 }}>
        STATUS · <span style={{ color: status === 'expired' || status === 'error' ? 'var(--mood-b)' : status === 'success' ? 'var(--focused)' : 'var(--ink)' }}>
          {statusText}
        </span>
      </div>
      <div style={{ marginTop: 10, fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--ink-2)' }}>
        打开{platform === 'netease' ? '网易云' : 'QQ 音乐'} App → 我的 → 扫一扫
      </div>
    </div>
  );
}

function CookieBlock({ platform, onSuccess }) {
  const [cookie, setCookie] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const submit = async () => {
    if (!cookie.trim()) { setError('请填写 Cookie'); return; }
    setLoading(true); setError('');
    try {
      const res = await platformApi.bindCookie(platform, cookie.trim());
      if (res.code === 200) onSuccess?.();
      else setError(res.message || '绑定失败');
    } catch (e) {
      setError(e?.message || '绑定失败，请检查 Cookie 格式');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      {error && <div style={{ marginBottom: 12, padding: '10px 14px', background: 'rgba(232,90,138,0.08)', border: '1px solid var(--mood-b)', borderRadius: 10, fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--mood-b)' }}>{error}</div>}
      <div style={{ marginBottom: 14 }}>
        <div className="between" style={{ marginBottom: 8 }}>
          <div className="meta">COOKIE</div>
          <span className="meta" style={{ color: 'var(--ink-2)' }}>浏览器开发者工具中复制</span>
        </div>
        <textarea className="field" value={cookie} onChange={e => setCookie(e.target.value)}
          placeholder="MUSIC_U=...; __csrf=...; NMTID=...;"
          style={{ minHeight: 160, fontFamily: 'var(--mono)', fontSize: 12 }} />
      </div>
      <button className="btn" onClick={submit} disabled={loading} style={{ width: '100%', height: 48, opacity: loading ? 0.7 : 1 }}>
        {loading ? '验证中…' : <><span>验证并保存</span> <Icon.arrow /></>}
      </button>
      <div className="meta" style={{ marginTop: 14, color: 'var(--ink-3)', lineHeight: 1.6 }}>
        · 高级方式 · 适合扫码不便时使用<br />
        · Cookie 会本地加密 · 服务端不留存明文
      </div>
    </div>
  );
}

function PhoneBlock({ platform, onSuccess }) {
  const [phone, setPhone] = useState('');
  const [code, setCode] = useState('');
  const [sent, setSent] = useState(false);
  const [countdown, setCountdown] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const timerRef = useRef(null);

  const sendCode = async () => {
    if (!phone.trim()) { setError('请输入手机号'); return; }
    setLoading(true); setError('');
    try {
      const res = await platformApi.sendPhoneCode(platform, phone.trim());
      if (res.code === 200) {
        setSent(true);
        setCountdown(60);
        timerRef.current = setInterval(() => {
          setCountdown(c => {
            if (c <= 1) { clearInterval(timerRef.current); return 0; }
            return c - 1;
          });
        }, 1000);
      } else {
        setError(res.message || '发送失败');
      }
    } catch (e) {
      setError(e?.message || '发送失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => () => clearInterval(timerRef.current), []);

  const submit = async () => {
    if (!code.trim()) { setError('请输入验证码'); return; }
    setLoading(true); setError('');
    try {
      const res = await platformApi.bindPhone(platform, { phone: phone.trim(), captcha: code.trim() });
      if (res.code === 200) onSuccess?.();
      else setError(res.message || '绑定失败');
    } catch (e) {
      setError(e?.message || '绑定失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      {error && (
        <div style={{ marginBottom: 12, padding: '10px 14px', background: 'rgba(232,90,138,0.08)', border: '1px solid var(--mood-b)', borderRadius: 10, fontFamily: 'var(--serif-cn)', fontSize: 13, color: 'var(--mood-b)' }}>
          {error}
        </div>
      )}
      <div style={{ marginBottom: 14 }}>
        <div className="between" style={{ marginBottom: 8 }}>
          <div className="meta">手机号 · PHONE</div>
          <span className="meta" style={{ color: 'var(--ink-3)' }}>
            绑定{platform === 'netease' ? '网易云' : 'QQ 音乐'}的手机号
          </span>
        </div>
        <div className="row" style={{ gap: 10 }}>
          <input className="field" value={phone} onChange={e => setPhone(e.target.value)}
            placeholder="+86 13x xxxx xxxx" style={{ flex: 1 }} />
          <button className="btn btn-ghost" onClick={sendCode} disabled={loading || countdown > 0}
            style={{ height: 46, padding: '0 16px', whiteSpace: 'nowrap', flexShrink: 0, opacity: countdown > 0 ? 0.6 : 1 }}>
            {countdown > 0 ? `${countdown}s` : sent ? '重新发送' : '发送验证码'}
          </button>
        </div>
      </div>
      {sent && (
        <div style={{ marginBottom: 14 }}>
          <div className="meta" style={{ marginBottom: 8 }}>验证码 · CODE</div>
          <input className="field" value={code} onChange={e => setCode(e.target.value)}
            placeholder="6 位验证码" maxLength={6}
            style={{ letterSpacing: '0.3em', fontSize: 18 }} />
        </div>
      )}
      <button className="btn" onClick={submit} disabled={loading || !sent}
        style={{ width: '100%', height: 48, opacity: loading || !sent ? 0.7 : 1 }}>
        {loading ? '验证中…' : <><span>验证并绑定</span> <Icon.arrow /></>}
      </button>
      <div className="meta" style={{ marginTop: 14, color: 'var(--ink-3)', lineHeight: 1.6 }}>
        · 手机号登录 · 适合国内用户<br />
        · 验证码 60 秒内有效 · 仅用于身份核验
      </div>
    </div>
  );
}

function BindModal({ tab, setTab, platform, onClose, inline, onSuccess }) {
  const platformLabel = platform === 'netease' ? '网易云音乐' : 'QQ 音乐';
  return (
    <div style={{ background: 'var(--paper)', borderRadius: inline ? 20 : 0, border: inline ? '1px solid var(--rule)' : 'none', padding: 28 }}>
      <div className="between" style={{ marginBottom: 18 }}>
        <div>
          <div className="meta">PLATFORM</div>
          <div className="display" style={{ fontSize: 36, marginTop: 4 }}><em>{platformLabel}</em></div>
        </div>
        {onClose && <button onClick={onClose} className="btn-pill">×</button>}
      </div>
      <div className="row" style={{ gap: 0, borderBottom: '1px solid var(--rule)', marginBottom: 24 }}>
        {[{ k: 'qr', l: '扫码登录', e: 'QR' }, { k: 'phone', l: '手机号', e: 'SMS' }, { k: 'cookie', l: 'Cookie', e: 'ADV' }].map(t => (
          <button key={t.k} onClick={() => setTab(t.k)} style={{
            background: 'transparent', border: 'none', padding: '12px 14px', cursor: 'pointer', position: 'relative',
            fontFamily: 'var(--serif-cn)', fontSize: 14, color: tab === t.k ? 'var(--ink)' : 'var(--ink-3)',
          }}>
            <span className="mono" style={{ fontSize: 10, letterSpacing: '.16em', color: 'var(--ink-3)', marginRight: 6 }}>{t.e}</span>
            {t.l}
            {tab === t.k && <div style={{ position: 'absolute', left: 0, right: 0, bottom: -1, height: 2, background: 'var(--ink)' }} />}
          </button>
        ))}
      </div>
      {tab === 'qr' && <QRBlock platform={platform} onSuccess={onSuccess} />}
      {tab === 'phone' && <PhoneBlock platform={platform} onSuccess={onSuccess} />}
      {tab === 'cookie' && <CookieBlock platform={platform} onSuccess={onSuccess} />}
    </div>
  );
}

function BindCard({ logo, name, en, bound, disabled, onBind }) {
  return (
    <div style={{ padding: 20, border: '1px solid var(--rule)', borderRadius: 18, background: 'var(--paper)', opacity: disabled ? 0.5 : 1 }}>
      <div className="row" style={{ gap: 14 }}>
        <div style={{
          width: 48, height: 48, borderRadius: '50%',
          background: bound ? 'linear-gradient(135deg, var(--mood-a), var(--mood-c))' : 'var(--bg-2)',
          color: bound ? '#fff' : 'var(--ink-3)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontFamily: 'var(--serif-cn)', fontSize: 20, fontWeight: 600, flexShrink: 0,
        }}>{logo}</div>
        <div style={{ flex: 1 }}>
          <div className="row" style={{ gap: 8 }}>
            <div style={{ fontFamily: 'var(--serif-cn)', fontSize: 18, fontWeight: 500 }}>{name}</div>
            {bound && <span className="meta" style={{ padding: '2px 8px', border: '1px solid var(--ink)', borderRadius: 999 }}>BOUND</span>}
          </div>
          <div className="meta" style={{ marginTop: 2 }}>{en}</div>
        </div>
        {!disabled && (
          <button onClick={onBind} className={bound ? 'btn-pill' : 'btn'} style={{ height: 38, padding: '0 16px' }}>
            {bound ? '重新绑定' : '绑定 →'}
          </button>
        )}
      </div>
      <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px dashed var(--rule)' }}>
        <span className="meta">{bound ? '· 已绑定，可正常使用' : '· 未绑定'}</span>
      </div>
    </div>
  );
}

export default function Bind() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const returnTo = params.get('returnTo');
  const [tab, setTab] = useState('qr');
  const [activePlatform, setActivePlatform] = useState('netease');
  const [bindings, setBindings] = useState([]);
  const [toast, setToast] = useState('');

  const loadBindings = () => {
    platformApi.getBindings().then(res => {
      if (res.code === 200) setBindings(res.data || []);
    }).catch(() => {});
  };

  useEffect(() => { loadBindings(); }, []);

  const isBound = (platform) => bindings.some(b => b.platform.toUpperCase() === platform.toUpperCase());

  const handleSuccess = () => {
    loadBindings();
    setToast('绑定成功！');
    setTimeout(() => setToast(''), 3000);
  };

  return (
    <div data-mood="dusk" className="mfm" style={{ minHeight: '100vh' }}>
      <div className="mood-blob drift" style={{ width: 700, height: 700, right: -200, top: -200, opacity: 0.3 }} />

      {/* Toast */}
      {toast && (
        <div style={{
          position: 'fixed', top: 24, left: '50%', transform: 'translateX(-50%)',
          padding: '12px 24px', background: 'var(--ink)', color: 'var(--bg)',
          borderRadius: 999, fontFamily: 'var(--mono)', fontSize: 12,
          letterSpacing: '.14em', zIndex: 100, boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
        }}>{toast}</div>
      )}

      {/* Top */}
      <div style={{ position: 'sticky', top: 0, zIndex: 5, background: 'var(--bg)', padding: '22px 56px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <button onClick={() => navigate('/home')} className="btn-pill"><Icon.chevL /> 返回</button>
        <div className="meta">PLATFORM · 平台绑定</div>
        <button onClick={() => navigate(returnTo === 'onboarding' ? '/onboarding?step=3' : '/home')} className="btn">
          {returnTo === 'onboarding' ? '完成绑定 → 继续引导' : '完成 → 进入电台'}
        </button>
      </div>

      <div style={{ position: 'relative', zIndex: 2, padding: '48px 56px 80px', display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 48 }}>
        {/* LEFT */}
        <div>
          <div className="meta">SECTION II · 接入</div>
          <h1 className="display" style={{ fontSize: 108, margin: '12px 0 0' }}>Plug in.</h1>
          <div className="display-cn" style={{ fontSize: 32, marginTop: 8, color: 'var(--ink-2)' }}>把你的曲库接进来。</div>
          <p style={{ marginTop: 18, fontSize: 14, lineHeight: 1.7, color: 'var(--ink-2)', maxWidth: 480, fontFamily: 'var(--serif-cn)' }}>
            支持网易云音乐与 QQ 音乐。我们读取你的曲库与红心，跨平台编排——所有凭证都本地加密，可随时解绑。
          </p>

          <div style={{ marginTop: 32, display: 'grid', gap: 14 }}>
            <BindCard logo="网" name="网易云音乐" en="NETEASE CLOUD MUSIC"
              bound={isBound('netease')}
              onBind={() => setActivePlatform('netease')} />
            <BindCard logo="Q" name="QQ 音乐" en="QQ MUSIC"
              bound={isBound('qqmusic')}
              onBind={() => setActivePlatform('qqmusic')} />
            <BindCard logo="B" name="Bilibili 音乐" en="BILIBILI MUSIC" disabled />
          </div>
        </div>

        {/* RIGHT: sticky modal */}
        <div style={{ position: 'sticky', top: 100, alignSelf: 'start' }}>
          <BindModal
            tab={tab} setTab={setTab}
            platform={activePlatform}
            inline
            onSuccess={handleSuccess} />
        </div>
      </div>
    </div>
  );
}

// moodfm-frontend/src/views/Bind.vue
<template>
  <div class="mfm" style="min-height: 100vh; position: relative; background: var(--bg); overflow: hidden;">
    <div class="mood-blob drift" style="width: 700px; height: 700px; right: -200px; top: -200px; opacity: 0.3;" />

    <div style="position: sticky; top: 0; z-index: 5; background: var(--bg); border-bottom: 1px solid var(--rule); display: flex; align-items: center; justify-content: space-between;"
      :style="{ padding: isMobile ? '16px 22px' : '22px 56px' }">
      <button class="btn-pill" @click="$router.back()">← 返回</button>
      <div class="meta">PLATFORM · 平台绑定</div>
      <button class="btn-pill" @click="$router.push('/home')">完成 →</button>
    </div>

    <div :style="{
      position: 'relative', zIndex: 2,
      padding: isMobile ? '24px 22px 60px' : '48px 56px 80px',
      display: 'grid',
      gridTemplateColumns: isMobile ? '1fr' : '1.2fr 1fr',
      gap: '48px',
    }">
      <div>
        <div class="meta">SECTION II · 接入</div>
        <h1 class="display" :style="{ fontSize: isMobile ? '52px' : '108px', margin: '12px 0 0' }">
          Plug in.
        </h1>
        <div class="display-cn" :style="{ fontSize: isMobile ? '22px' : '32px', marginTop: '8px', color: 'var(--ink-2)' }">
          把你的曲库接进来。
        </div>
        <p :style="{ marginTop: '18px', fontSize: '14px', lineHeight: 1.7, color: 'var(--ink-2)', maxWidth: '480px', fontFamily: 'var(--serif-cn)' }">
          支持网易云音乐与 QQ 音乐。我们读取你的曲库与红心，跨平台编排——所有凭证都本地加密，可随时解绑。
        </p>

        <div style="margin-top: 32px; display: grid; grid-template-columns: 1fr; gap: 14px;">
          <div v-for="p in platforms" :key="p.id"
            :style="{
              padding: '20px',
              border: '1px solid var(--rule)',
              borderRadius: '18px',
              background: 'var(--paper)',
              position: 'relative',
              opacity: p.disabled ? 0.5 : 1,
            }">
            <div class="row" style="gap: 14px;">
              <div :style="{
                width: '48px', height: '48px', borderRadius: '50%',
                background: p.bound ? 'linear-gradient(135deg, var(--mood-a), var(--mood-c))' : 'var(--bg-2)',
                color: p.bound ? '#fff' : 'var(--ink-3)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontFamily: 'var(--serif-cn)', fontSize: '20px', fontWeight: 600,
                flexShrink: 0,
              }">{{ p.logo }}</div>
              <div style="flex: 1; min-width: 0;">
                <div class="row" style="gap: 8px;">
                  <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '18px', fontWeight: 500 }">{{ p.name }}</div>
                  <span v-if="p.bound" class="meta" style="padding: 2px 8px; border: 1px solid var(--ink); border-radius: 999px; color: var(--ink);">BOUND</span>
                </div>
                <div class="meta" style="margin-top: 2px;">{{ p.en }}</div>
              </div>
              <button v-if="!p.disabled" @click="openModal(p.id)"
                :class="p.bound ? 'btn-pill' : 'btn'"
                style="height: 38px; padding: 0 16px; flex-shrink: 0;">
                {{ p.bound ? '重新绑定' : '绑定 →' }}
              </button>
            </div>
            <div class="row" style="margin-top: 16px; gap: 24px; padding-top: 16px; border-top: 1px dashed var(--rule);">
              <div>
                <div class="meta" style="color: var(--ink-3);">状态</div>
                <div :style="{
                  fontFamily: 'var(--mono)', fontSize: '13px', marginTop: '4px',
                  color: p.expired ? '#e05252' : p.expiringSoon ? '#d4a017' : 'var(--ink)'
                }">{{ p.status }}</div>
              </div>
            </div>
          </div>
        </div>

        <details style="margin-top: 28px; padding: 18px; border: 1px solid var(--rule); border-radius: 14px; background: var(--paper);">
          <summary :style="{ cursor: 'pointer', fontFamily: 'var(--serif-cn)', fontSize: '14px' }">
            <span class="meta" style="margin-right: 10px;">·</span>
            账号信息如何被加密保护？
          </summary>
          <div style="margin-top: 12px; font-size: 13px; line-height: 1.7; color: var(--ink-2); font-family: var(--serif-cn);">
            所有 Cookie 与 Token 仅存储在你的本地与端到端加密的数据库；服务端永不留存明文。每 30 天自动续期一次，过期会主动提醒你重绑。
          </div>
        </details>
      </div>

      <div v-if="!isMobile" style="position: sticky; top: 100px; align-self: start;">
        <div :style="{
          background: 'var(--paper)',
          borderRadius: '20px',
          border: '1px solid var(--rule)',
          padding: '28px',
        }">
          <div class="between" style="margin-bottom: 18px;">
            <div>
              <div class="meta">PLATFORM</div>
              <div class="display" style="font-size: 36px; margin-top: 4px;">
                <em>{{ activePlatform }}</em>
              </div>
            </div>
          </div>

          <div class="row" style="gap: 0; border-bottom: 1px solid var(--rule); margin-bottom: 24px;">
            <button
              v-for="t in tabs"
              :key="t.k"
              @click="activeTab = t.k"
              :style="{
                background: 'transparent', border: 'none', padding: '12px 14px',
                cursor: 'pointer', position: 'relative',
                fontFamily: 'var(--serif-cn)', fontSize: '14px',
                color: activeTab === t.k ? 'var(--ink)' : 'var(--ink-3)',
              }">
              <span class="mono" style="font-size: 10px; letter-spacing: .16em; color: var(--ink-3); margin-right: 6px;">{{ t.e }}</span>
              {{ t.l }}
              <div v-if="activeTab === t.k" style="position: absolute; left: 0; right: 0; bottom: -1px; height: 2px; background: var(--ink);" />
            </button>
          </div>

          <div v-if="activeTab === 'qr'" style="text-align: center;">
            <div style="display: inline-block; position: relative; padding: 24px; border: 1px solid var(--rule); border-radius: 18px; background: var(--bg);">
              <div style="width: 200px; height: 200px; position: relative; background: #fff; padding: 8px;">
                <img v-if="qrImageUrl" :src="qrImageUrl" alt="QR Code" style="width: 184px; height: 184px; display: block;" />

                <Transition name="fade">
                  <div v-if="qrStatus === 'expired'"
                    style="position: absolute; inset: 0; background: rgba(255,255,255,0.92); display: flex; flex-direction: column; align-items: center; justify-content: center;">
                    <div class="meta">QR EXPIRED</div>
                    <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '14px', marginTop: '4px', color: 'var(--ink-2)' }">二维码已过期</div>
                    <button class="btn" style="margin-top: 12px; height: 36px;" @click="refreshQr">刷新</button>
                  </div>
                </Transition>
              </div>
            </div>

            <div class="meta" style="margin-top: 18px;">
              STATUS ·
              <span :style="{
                color: qrStatus === 'waiting' ? 'var(--ink)'
                  : qrStatus === 'expired' ? 'var(--mood-b)'
                  : 'var(--mood-c)'
              }">
                <span v-if="qrStatus === 'waiting'">等待扫码</span>
                <span v-else-if="qrStatus === 'scanned'">已扫码 · 请在手机上确认</span>
                <span v-else-if="qrStatus === 'success'">登录成功</span>
                <span v-else>二维码已过期</span>
              </span>
            </div>

            <div v-if="qrStatus === 'waiting' || qrStatus === 'scanned'" :style="{ marginTop: '8px', fontFamily: 'var(--mono)', fontSize: '13px', color: 'var(--ink-2)' }">
              {{ qrCountdown }}s 后过期 · refresh in {{ qrCountdown }}s
            </div>

            <div :style="{ marginTop: '16px', fontFamily: 'var(--serif-cn)', fontSize: '13px', color: 'var(--ink-2)' }">
              打开{{ activePlatform }} App → 我的 → 扫一扫
            </div>
          </div>

          <div v-else-if="activeTab === 'phone'">
            <div style="margin-bottom: 14px;">
              <div class="meta" style="margin-bottom: 8px;">手机号 · PHONE</div>
              <input v-model="phone" class="field" placeholder="+86 138 ····" type="tel" />
            </div>

            <div style="margin-bottom: 18px; position: relative;">
              <div class="meta" style="margin-bottom: 8px;">验证码 · OTP</div>
              <input v-model="phoneCode" class="field" placeholder="6 位" style="padding-right: 130px;" />
              <button @click="sendPhoneCode" :style="{
                position: 'absolute', right: '6px', bottom: '6px',
                height: '36px', padding: '0 14px', borderRadius: '999px',
                background: phoneCountdown > 0 ? 'transparent' : 'var(--ink)',
                color: phoneCountdown > 0 ? 'var(--ink-3)' : 'var(--bg)',
                border: phoneCountdown > 0 ? '1px solid var(--rule)' : 'none',
                cursor: phoneCountdown > 0 ? 'not-allowed' : 'pointer',
                fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase',
              }">{{ phoneCountdown > 0 ? `${phoneCountdown}s` : '获取验证码' }}</button>
            </div>

            <div v-if="phoneError" class="meta" style="margin-bottom: 12px; color: var(--mood-b);">· {{ phoneError }}</div>

            <button class="btn" style="width: 100%; height: 48px;" :disabled="phoneLoading" @click="submitPhone">
              {{ phoneLoading ? '验证中...' : '验证并绑定 →' }}
            </button>
            <div class="meta" style="margin-top: 14px; color: var(--ink-3);">
              · 与 App 内手机号一致 · 验证后立即同步曲库
            </div>
          </div>

          <div v-else-if="activeTab === 'cookie'">
            <div style="margin-bottom: 14px;">
              <div class="between" style="margin-bottom: 8px;">
                <div class="meta">COOKIE</div>
                <a class="meta" style="color: var(--ink-2); text-decoration: underline; cursor: pointer;">如何获取 →</a>
              </div>
              <textarea
                v-model="cookieValue"
                class="field"
                placeholder="MUSIC_U=...; __csrf=...; NMTID=...;"
                :style="{ minHeight: '160px', fontFamily: 'var(--mono)', fontSize: '12px' }"
              />
            </div>

            <div v-if="cookieError" class="meta" style="margin-bottom: 12px; color: var(--mood-b);">· {{ cookieError }}</div>

            <button class="btn" style="width: 100%; height: 48px;" :disabled="cookieLoading" @click="submitCookie">
              {{ cookieLoading ? '验证中...' : '验证并保存 →' }}
            </button>
            <div class="meta" style="margin-top: 14px; color: var(--ink-3); line-height: 1.6;">
              · 高级方式 · 适合扫码与短信都不便时使用<br />
              · Cookie 会本地加密 · 服务端不留存明文
            </div>
          </div>
        </div>
      </div>
    </div>

    <Transition name="sheet">
      <div v-if="isMobile && modalOpen"
        style="position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 50; display: flex; align-items: flex-end;"
        @click.self="modalOpen = false">
        <div style="width: 100%; background: var(--bg); border-top-left-radius: 24px; border-top-right-radius: 24px; max-height: 88vh; overflow: auto;">
          <div style="padding: 28px;">
            <div class="between" style="margin-bottom: 18px;">
              <div>
                <div class="meta">PLATFORM</div>
                <div class="display" style="font-size: 36px; margin-top: 4px;">
                  <em>{{ activePlatform }}</em>
                </div>
              </div>
              <button class="btn-pill" @click="modalOpen = false" style="font-size: 18px; line-height: 1; padding: 0 14px;">×</button>
            </div>

            <div class="row" style="gap: 0; border-bottom: 1px solid var(--rule); margin-bottom: 24px;">
              <button
                v-for="t in tabs"
                :key="t.k"
                @click="activeTab = t.k"
                :style="{
                  background: 'transparent', border: 'none', padding: '12px 14px',
                  cursor: 'pointer', position: 'relative',
                  fontFamily: 'var(--serif-cn)', fontSize: '14px',
                  color: activeTab === t.k ? 'var(--ink)' : 'var(--ink-3)',
                }">
                <span class="mono" style="font-size: 10px; letter-spacing: .16em; color: var(--ink-3); margin-right: 6px;">{{ t.e }}</span>
                {{ t.l }}
                <div v-if="activeTab === t.k" style="position: absolute; left: 0; right: 0; bottom: -1px; height: 2px; background: var(--ink);" />
              </button>
            </div>

            <div v-if="activeTab === 'qr'" style="text-align: center;">
              <div style="display: inline-block; position: relative; padding: 24px; border: 1px solid var(--rule); border-radius: 18px; background: var(--bg);">
                <div style="width: 200px; height: 200px; position: relative; background: #fff; padding: 8px;">
                  <img v-if="qrImageUrl" :src="qrImageUrl" alt="QR Code" style="width: 184px; height: 184px; display: block;" />

                  <Transition name="fade">
                    <div v-if="qrStatus === 'expired'"
                      style="position: absolute; inset: 0; background: rgba(255,255,255,0.92); display: flex; flex-direction: column; align-items: center; justify-content: center;">
                      <div class="meta">QR EXPIRED</div>
                      <div :style="{ fontFamily: 'var(--serif-cn)', fontSize: '14px', marginTop: '4px', color: 'var(--ink-2)' }">二维码已过期</div>
                      <button class="btn" style="margin-top: 12px; height: 36px;" @click="refreshQr">刷新</button>
                    </div>
                  </Transition>
                </div>
              </div>

              <div class="meta" style="margin-top: 18px;">
                STATUS ·
                <span :style="{
                  color: qrStatus === 'waiting' ? 'var(--ink)'
                    : qrStatus === 'expired' ? 'var(--mood-b)'
                    : 'var(--mood-c)'
                }">
                  <span v-if="qrStatus === 'waiting'">等待扫码</span>
                  <span v-else-if="qrStatus === 'scanned'">已扫码 · 请在手机上确认</span>
                  <span v-else-if="qrStatus === 'success'">登录成功</span>
                  <span v-else>二维码已过期</span>
                </span>
              </div>

              <div v-if="qrStatus === 'waiting' || qrStatus === 'scanned'" :style="{ marginTop: '8px', fontFamily: 'var(--mono)', fontSize: '13px', color: 'var(--ink-2)' }">
                {{ qrCountdown }}s 后过期 · refresh in {{ qrCountdown }}s
              </div>

              <div :style="{ marginTop: '16px', fontFamily: 'var(--serif-cn)', fontSize: '13px', color: 'var(--ink-2)' }">
                打开{{ activePlatform }} App → 我的 → 扫一扫
              </div>
            </div>

            <div v-else-if="activeTab === 'phone'">
              <div style="margin-bottom: 14px;">
                <div class="meta" style="margin-bottom: 8px;">手机号 · PHONE</div>
                <input v-model="phone" class="field" placeholder="+86 138 ····" type="tel" />
              </div>

              <div style="margin-bottom: 18px; position: relative;">
                <div class="meta" style="margin-bottom: 8px;">验证码 · OTP</div>
                <input v-model="phoneCode" class="field" placeholder="6 位" style="padding-right: 130px;" />
                <button @click="sendPhoneCode" :style="{
                  position: 'absolute', right: '6px', bottom: '6px',
                  height: '36px', padding: '0 14px', borderRadius: '999px',
                  background: phoneCountdown > 0 ? 'transparent' : 'var(--ink)',
                  color: phoneCountdown > 0 ? 'var(--ink-3)' : 'var(--bg)',
                  border: phoneCountdown > 0 ? '1px solid var(--rule)' : 'none',
                  cursor: phoneCountdown > 0 ? 'not-allowed' : 'pointer',
                  fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase',
                }">{{ phoneCountdown > 0 ? `${phoneCountdown}s` : '获取验证码' }}</button>
              </div>

              <div v-if="phoneError" class="meta" style="margin-bottom: 12px; color: var(--mood-b);">· {{ phoneError }}</div>

              <button class="btn" style="width: 100%; height: 48px;" :disabled="phoneLoading" @click="submitPhone">
                {{ phoneLoading ? '验证中...' : '验证并绑定 →' }}
              </button>
              <div class="meta" style="margin-top: 14px; color: var(--ink-3);">
                · 与 App 内手机号一致 · 验证后立即同步曲库
              </div>
            </div>

            <div v-else-if="activeTab === 'cookie'">
              <div style="margin-bottom: 14px;">
                <div class="between" style="margin-bottom: 8px;">
                  <div class="meta">COOKIE</div>
                  <a class="meta" style="color: var(--ink-2); text-decoration: underline; cursor: pointer;">如何获取 →</a>
                </div>
                <textarea
                  v-model="cookieValue"
                  class="field"
                  placeholder="MUSIC_U=...; __csrf=...; NMTID=...;"
                  :style="{ minHeight: '160px', fontFamily: 'var(--mono)', fontSize: '12px' }"
                />
              </div>

              <div v-if="cookieError" class="meta" style="margin-bottom: 12px; color: var(--mood-b);">· {{ cookieError }}</div>

              <button class="btn" style="width: 100%; height: 48px;" :disabled="cookieLoading" @click="submitCookie">
                {{ cookieLoading ? '验证中...' : '验证并保存 →' }}
              </button>
              <div class="meta" style="margin-top: 14px; color: var(--ink-3); line-height: 1.6;">
                · 高级方式 · 适合扫码与短信都不便时使用<br />
                · Cookie 会本地加密 · 服务端不留存明文
              </div>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue'
import { platformApi } from '@/api/platform'

const isMobile = ref(window.innerWidth < 768)
const modalOpen = ref(false)
const activePlatform = ref('网易云音乐')
const activeTab = ref<'qr' | 'phone' | 'cookie'>('qr')

function handleResize() {
  isMobile.value = window.innerWidth < 768
}
onMounted(() => window.addEventListener('resize', handleResize))
onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
  clearQrTimers()
  if (phoneTimer) clearInterval(phoneTimer)
})

const platforms = reactive([
  { id: '网易云音乐', logo: '网', name: '网易云音乐', en: 'NETEASE CLOUD MUSIC', status: '未绑定', bound: false, disabled: false, expiringSoon: false, expired: false },
  { id: 'QQ音乐', logo: 'Q', name: 'QQ 音乐', en: 'QQ MUSIC', status: '未绑定', bound: false, disabled: false, expiringSoon: false, expired: false },
  { id: 'Bilibili', logo: 'B', name: 'Bilibili 音乐', en: 'BILIBILI MUSIC', status: '即将上线', bound: false, disabled: true, expiringSoon: false, expired: false },
])

const tabs = [
  { k: 'qr' as const, l: '扫码登录', e: 'QR' },
  { k: 'phone' as const, l: '手机号', e: 'PHONE' },
  { k: 'cookie' as const, l: 'Cookie', e: 'ADV' },
]

function openModal(platformId: string) {
  activePlatform.value = platformId
  activeTab.value = 'qr'
  if (isMobile.value) {
    modalOpen.value = true
  }
  refreshQr()
}

const PLATFORM_ID_MAP: Record<string, 'netease' | 'qqmusic'> = {
  '网易云音乐': 'netease',
  'QQ音乐': 'qqmusic',
}

function getPlatformId(name: string): 'netease' | 'qqmusic' | null {
  return PLATFORM_ID_MAP[name] ?? null
}

const qrStatus = ref<'waiting' | 'scanned' | 'success' | 'expired'>('waiting')
const qrCountdown = ref(90)
const qrImageUrl = ref('')
const qrKey = ref('')
let qrTimer: ReturnType<typeof setInterval> | null = null
let qrPollTimer: ReturnType<typeof setInterval> | null = null

function clearQrTimers() {
  if (qrTimer) { clearInterval(qrTimer); qrTimer = null }
  if (qrPollTimer) { clearInterval(qrPollTimer); qrPollTimer = null }
}

function startQrTimer() {
  if (qrTimer) clearInterval(qrTimer)
  qrTimer = setInterval(() => {
    if (qrStatus.value !== 'waiting' && qrStatus.value !== 'scanned') return
    qrCountdown.value--
    if (qrCountdown.value <= 0) {
      qrStatus.value = 'expired'
      clearQrTimers()
    }
  }, 1000)
}

function startQrPolling(platform: string) {
  if (qrPollTimer) clearInterval(qrPollTimer)
  const platformId = getPlatformId(platform)
  if (!platformId || !qrKey.value) return

  qrPollTimer = setInterval(async () => {
    try {
      const res = await platformApi.checkQRStatus(platformId, qrKey.value)
      if (res.status === 'scanned') {
        qrStatus.value = 'scanned'
      } else if (res.status === 'success') {
        qrStatus.value = 'success'
        clearQrTimers()
        loadBindings()
      } else if (res.status === 'expired') {
        qrStatus.value = 'expired'
        clearQrTimers()
      } else if (res.status === 'error') {
        qrStatus.value = 'expired'
        clearQrTimers()
      }
    } catch {
      // keep polling on transient errors
    }
  }, 2500)
}

async function refreshQr() {
  clearQrTimers()
  qrCountdown.value = 90
  qrStatus.value = 'waiting'
  qrImageUrl.value = ''

  const platformId = getPlatformId(activePlatform.value)
  if (!platformId) return

  try {
    const res = await platformApi.generateQR(platformId)
    qrKey.value = res.key
    qrImageUrl.value = res.qrimg
    startQrTimer()
    startQrPolling(activePlatform.value)
  } catch {
    qrStatus.value = 'expired'
  }
}

function daysUntil(dateStr?: string): number | null {
  if (!dateStr) return null
  const diff = new Date(dateStr).getTime() - Date.now()
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}

async function loadBindings() {
  try {
    const bindings = await platformApi.getBindings()
    for (const b of bindings) {
      const p = platforms.find(pp => PLATFORM_ID_MAP[pp.id] === b.platform)
      if (p) {
        const days = daysUntil(b.expiresAt)
        p.expired = !b.valid
        p.expiringSoon = b.valid && days !== null && days <= 7 && days >= 0
        if (!b.valid) {
          p.bound = false
          p.status = 'Cookie 已过期，请重新绑定'
        } else if (p.expiringSoon && days !== null) {
          p.bound = true
          p.status = b.platformUsername ? `已绑定 · ${b.platformUsername} · ${days}天后过期` : `已绑定 · ${days}天后过期`
        } else {
          p.bound = true
          p.status = b.platformUsername ? `已绑定 · ${b.platformUsername}` : '已绑定'
        }
      }
    }
  } catch {}
}

onMounted(loadBindings)

const phone = ref('')
const phoneCode = ref('')
const phoneCountdown = ref(0)
const phoneLoading = ref(false)
const phoneError = ref('')
const phoneTicket = ref('')
let phoneTimer: ReturnType<typeof setInterval> | null = null

async function sendPhoneCode() {
  if (phoneCountdown.value > 0 || !phone.value.trim()) return
  const pid = getPlatformId(activePlatform.value)
  if (!pid) return
  phoneError.value = ''
  try {
    const res = await platformApi.sendPhoneCode(pid, phone.value.trim())
    phoneTicket.value = res.ticket
  } catch (e: any) {
    phoneError.value = e?.response?.data?.message || e?.message || '短信发送失败，请重试'
    return
  }
  phoneCountdown.value = 60
  phoneTimer = setInterval(() => {
    phoneCountdown.value--
    if (phoneCountdown.value <= 0 && phoneTimer) {
      clearInterval(phoneTimer)
      phoneTimer = null
    }
  }, 1000)
}

async function submitPhone() {
  phoneError.value = ''
  if (!phone.value.trim()) { phoneError.value = '请输入手机号'; return }
  if (!phoneCode.value.trim()) { phoneError.value = '请输入验证码'; return }
  if (!phoneTicket.value) { phoneError.value = '请先获取验证码'; return }
  const pid = getPlatformId(activePlatform.value)
  if (!pid) return
  phoneLoading.value = true
  try {
    await platformApi.bindPhone(pid, { phone: phone.value.trim(), code: phoneCode.value.trim(), ticket: phoneTicket.value })
    phoneTicket.value = ''
    loadBindings()
  } catch (e: any) {
    phoneError.value = e?.response?.data?.message || e?.message || '绑定失败，请重试'
  } finally {
    phoneLoading.value = false
  }
}

const cookieValue = ref('')
const cookieLoading = ref(false)
const cookieError = ref('')

async function submitCookie() {
  cookieError.value = ''
  if (!cookieValue.value.trim()) { cookieError.value = '请粘贴 Cookie 内容'; return }
  const pid = getPlatformId(activePlatform.value)
  if (!pid) return
  cookieLoading.value = true
  try {
    await platformApi.bindCookie(pid, cookieValue.value.trim())
    loadBindings()
  } catch (e: any) {
    cookieError.value = e?.response?.data?.message || e?.message || '验证失败，请检查 Cookie 是否有效'
  } finally {
    cookieLoading.value = false
  }
}
</script>

<style scoped>
.sheet-enter-active, .sheet-leave-active { transition: opacity .2s; }
.sheet-enter-from, .sheet-leave-to { opacity: 0; }
.fade-enter-active, .fade-leave-active { transition: opacity .2s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
